# Generated source list for freetype
# GODOT_THIRDPARTY_FREETYPE_SOURCES - Source files for freetype
set(GODOT_THIRDPARTY_FREETYPE_SOURCES
  freetype/src/autofit/afblue.c
  freetype/src/autofit/afcjk.c
  freetype/src/autofit/afdummy.c
  freetype/src/autofit/afglobal.c
  freetype/src/autofit/afhints.c
  freetype/src/autofit/afindic.c
  freetype/src/autofit/aflatin.c
  freetype/src/autofit/afloader.c
  freetype/src/autofit/afmodule.c
  freetype/src/autofit/afranges.c
  freetype/src/autofit/afshaper.c
  freetype/src/autofit/autofit.c
  freetype/src/autofit/ft-hb.c
  freetype/src/base/ftadvanc.c
  freetype/src/base/ftbase.c
  freetype/src/base/ftbbox.c
  freetype/src/base/ftbdf.c
  freetype/src/base/ftbitmap.c
  freetype/src/base/ftcalc.c
  freetype/src/base/ftcid.c
  freetype/src/base/ftcolor.c
  freetype/src/base/ftdbgmem.c
  freetype/src/base/ftdebug.c
  freetype/src/base/fterrors.c
  freetype/src/base/ftfntfmt.c
  freetype/src/base/ftfstype.c
  freetype/src/base/ftgasp.c
  freetype/src/base/ftgloadr.c
  freetype/src/base/ftglyph.c
  freetype/src/base/ftgxval.c
  freetype/src/base/fthash.c
  freetype/src/base/ftinit.c
  freetype/src/base/ftlcdfil.c
  freetype/src/base/ftmac.c
  freetype/src/base/ftmm.c
  freetype/src/base/ftobjs.c
  freetype/src/base/ftotval.c
  freetype/src/base/ftoutln.c
  freetype/src/base/ftpatent.c
  freetype/src/base/ftpfr.c
  freetype/src/base/ftpsprop.c
  freetype/src/base/ftrfork.c
  freetype/src/base/ftsnames.c
  freetype/src/base/ftstream.c
  freetype/src/base/ftstroke.c
  freetype/src/base/ftsynth.c
  freetype/src/base/ftsystem.c
  freetype/src/base/fttrigon.c
  freetype/src/base/fttype1.c
  freetype/src/base/ftutil.c
  freetype/src/base/ftwinfnt.c
  freetype/src/base/md5.c
  freetype/src/bdf/bdf.c
  freetype/src/bdf/bdfdrivr.c
  freetype/src/bdf/bdflib.c
  freetype/src/bzip2/ftbzip2.c
  freetype/src/cache/ftcache.c
  freetype/src/cache/ftcbasic.c
  freetype/src/cache/ftccache.c
  freetype/src/cache/ftccmap.c
  freetype/src/cache/ftcglyph.c
  freetype/src/cache/ftcimage.c
  freetype/src/cache/ftcmanag.c
  freetype/src/cache/ftcmru.c
  freetype/src/cache/ftcsbits.c
  freetype/src/cff/cff.c
  freetype/src/cff/cffcmap.c
  freetype/src/cff/cffdrivr.c
  freetype/src/cff/cffgload.c
  freetype/src/cff/cffload.c
  freetype/src/cff/cffobjs.c
  freetype/src/cff/cffparse.c
  freetype/src/cid/cidgload.c
  freetype/src/cid/cidload.c
  freetype/src/cid/cidobjs.c
  freetype/src/cid/cidparse.c
  freetype/src/cid/cidriver.c
  freetype/src/cid/type1cid.c
  freetype/src/gxvalid/gxvalid.c
  freetype/src/gxvalid/gxvbsln.c
  freetype/src/gxvalid/gxvcommn.c
  freetype/src/gxvalid/gxvfeat.c
  freetype/src/gxvalid/gxvfgen.c
  freetype/src/gxvalid/gxvjust.c
  freetype/src/gxvalid/gxvkern.c
  freetype/src/gxvalid/gxvlcar.c
  freetype/src/gxvalid/gxvmod.c
  freetype/src/gxvalid/gxvmort.c
  freetype/src/gxvalid/gxvmort0.c
  freetype/src/gxvalid/gxvmort1.c
  freetype/src/gxvalid/gxvmort2.c
  freetype/src/gxvalid/gxvmort4.c
  freetype/src/gxvalid/gxvmort5.c
  freetype/src/gxvalid/gxvmorx.c
  freetype/src/gxvalid/gxvmorx0.c
  freetype/src/gxvalid/gxvmorx1.c
  freetype/src/gxvalid/gxvmorx2.c
  freetype/src/gxvalid/gxvmorx4.c
  freetype/src/gxvalid/gxvmorx5.c
  freetype/src/gxvalid/gxvopbd.c
  freetype/src/gxvalid/gxvprop.c
  freetype/src/gxvalid/gxvtrak.c
  freetype/src/gzip/ftgzip.c
  freetype/src/lzw/ftlzw.c
  freetype/src/lzw/ftzopen.c
  freetype/src/otvalid/otvalid.c
  freetype/src/otvalid/otvbase.c
  freetype/src/otvalid/otvcommn.c
  freetype/src/otvalid/otvgdef.c
  freetype/src/otvalid/otvgpos.c
  freetype/src/otvalid/otvgsub.c
  freetype/src/otvalid/otvjstf.c
  freetype/src/otvalid/otvmath.c
  freetype/src/otvalid/otvmod.c
  freetype/src/pcf/pcf.c
  freetype/src/pcf/pcfdrivr.c
  freetype/src/pcf/pcfread.c
  freetype/src/pcf/pcfutil.c
  freetype/src/pfr/pfr.c
  freetype/src/pfr/pfrcmap.c
  freetype/src/pfr/pfrdrivr.c
  freetype/src/pfr/pfrgload.c
  freetype/src/pfr/pfrload.c
  freetype/src/pfr/pfrobjs.c
  freetype/src/pfr/pfrsbit.c
  freetype/src/psaux/afmparse.c
  freetype/src/psaux/cffdecode.c
  freetype/src/psaux/psarrst.c
  freetype/src/psaux/psaux.c
  freetype/src/psaux/psauxmod.c
  freetype/src/psaux/psblues.c
  freetype/src/psaux/psconv.c
  freetype/src/psaux/pserror.c
  freetype/src/psaux/psfont.c
  freetype/src/psaux/psft.c
  freetype/src/psaux/pshints.c
  freetype/src/psaux/psintrp.c
  freetype/src/psaux/psobjs.c
  freetype/src/psaux/psread.c
  freetype/src/psaux/psstack.c
  freetype/src/psaux/t1cmap.c
  freetype/src/psaux/t1decode.c
  freetype/src/pshinter/pshalgo.c
  freetype/src/pshinter/pshglob.c
  freetype/src/pshinter/pshinter.c
  freetype/src/pshinter/pshmod.c
  freetype/src/pshinter/pshrec.c
  freetype/src/psnames/psmodule.c
  freetype/src/psnames/psnames.c
  freetype/src/raster/ftraster.c
  freetype/src/raster/ftrend1.c
  freetype/src/raster/raster.c
  freetype/src/sdf/ftbsdf.c
  freetype/src/sdf/ftsdf.c
  freetype/src/sdf/ftsdfcommon.c
  freetype/src/sdf/ftsdfrend.c
  freetype/src/sdf/sdf.c
  freetype/src/sfnt/pngshim.c
  freetype/src/sfnt/sfdriver.c
  freetype/src/sfnt/sfnt.c
  freetype/src/sfnt/sfobjs.c
  freetype/src/sfnt/sfwoff.c
  freetype/src/sfnt/sfwoff2.c
  freetype/src/sfnt/ttbdf.c
  freetype/src/sfnt/ttcmap.c
  freetype/src/sfnt/ttcolr.c
  freetype/src/sfnt/ttcpal.c
  freetype/src/sfnt/ttgpos.c
  freetype/src/sfnt/ttkern.c
  freetype/src/sfnt/ttload.c
  freetype/src/sfnt/ttmtx.c
  freetype/src/sfnt/ttpost.c
  freetype/src/sfnt/ttsbit.c
  freetype/src/sfnt/ttsvg.c
  freetype/src/sfnt/woff2tags.c
  freetype/src/smooth/ftgrays.c
  freetype/src/smooth/ftsmooth.c
  freetype/src/smooth/smooth.c
  freetype/src/svg/ftsvg.c
  freetype/src/svg/svg.c
  freetype/src/truetype/truetype.c
  freetype/src/truetype/ttdriver.c
  freetype/src/truetype/ttgload.c
  freetype/src/truetype/ttgxvar.c
  freetype/src/truetype/ttinterp.c
  freetype/src/truetype/ttobjs.c
  freetype/src/truetype/ttpload.c
  freetype/src/type1/t1afm.c
  freetype/src/type1/t1driver.c
  freetype/src/type1/t1gload.c
  freetype/src/type1/t1load.c
  freetype/src/type1/t1objs.c
  freetype/src/type1/t1parse.c
  freetype/src/type1/type1.c
  freetype/src/type42/t42drivr.c
  freetype/src/type42/t42objs.c
  freetype/src/type42/t42parse.c
  freetype/src/type42/type42.c
  freetype/src/winfonts/winfnt.c
)

# GODOT_THIRDPARTY_FREETYPE_HEADERS - Header files for freetype
set(GODOT_THIRDPARTY_FREETYPE_HEADERS
  freetype/include/freetype/config/ftconfig.h
  freetype/include/freetype/config/ftheader.h
  freetype/include/freetype/config/ftmodule.h
  freetype/include/freetype/config/ftoption.h
  freetype/include/freetype/config/ftstdlib.h
  freetype/include/freetype/config/integer-types.h
  freetype/include/freetype/config/mac-support.h
  freetype/include/freetype/config/public-macros.h
  freetype/include/freetype/freetype.h
  freetype/include/freetype/ftadvanc.h
  freetype/include/freetype/ftbbox.h
  freetype/include/freetype/ftbdf.h
  freetype/include/freetype/ftbitmap.h
  freetype/include/freetype/ftbzip2.h
  freetype/include/freetype/ftcache.h
  freetype/include/freetype/ftchapters.h
  freetype/include/freetype/ftcid.h
  freetype/include/freetype/ftcolor.h
  freetype/include/freetype/ftdriver.h
  freetype/include/freetype/fterrdef.h
  freetype/include/freetype/fterrors.h
  freetype/include/freetype/ftfntfmt.h
  freetype/include/freetype/ftgasp.h
  freetype/include/freetype/ftglyph.h
  freetype/include/freetype/ftgxval.h
  freetype/include/freetype/ftgzip.h
  freetype/include/freetype/ftimage.h
  freetype/include/freetype/ftincrem.h
  freetype/include/freetype/ftlcdfil.h
  freetype/include/freetype/ftlist.h
  freetype/include/freetype/ftlogging.h
  freetype/include/freetype/ftlzw.h
  freetype/include/freetype/ftmac.h
  freetype/include/freetype/ftmm.h
  freetype/include/freetype/ftmodapi.h
  freetype/include/freetype/ftmoderr.h
  freetype/include/freetype/ftotval.h
  freetype/include/freetype/ftoutln.h
  freetype/include/freetype/ftparams.h
  freetype/include/freetype/ftpfr.h
  freetype/include/freetype/ftrender.h
  freetype/include/freetype/ftsizes.h
  freetype/include/freetype/ftsnames.h
  freetype/include/freetype/ftstroke.h
  freetype/include/freetype/ftsynth.h
  freetype/include/freetype/ftsystem.h
  freetype/include/freetype/fttrigon.h
  freetype/include/freetype/fttypes.h
  freetype/include/freetype/ftwinfnt.h
  freetype/include/freetype/internal/autohint.h
  freetype/include/freetype/internal/cffotypes.h
  freetype/include/freetype/internal/cfftypes.h
  freetype/include/freetype/internal/compiler-macros.h
  freetype/include/freetype/internal/ftcalc.h
  freetype/include/freetype/internal/ftdebug.h
  freetype/include/freetype/internal/ftdrv.h
  freetype/include/freetype/internal/ftgloadr.h
  freetype/include/freetype/internal/fthash.h
  freetype/include/freetype/internal/ftmemory.h
  freetype/include/freetype/internal/ftmmtypes.h
  freetype/include/freetype/internal/ftobjs.h
  freetype/include/freetype/internal/ftpsprop.h
  freetype/include/freetype/internal/ftrfork.h
  freetype/include/freetype/internal/ftserv.h
  freetype/include/freetype/internal/ftstream.h
  freetype/include/freetype/internal/fttrace.h
  freetype/include/freetype/internal/ftvalid.h
  freetype/include/freetype/internal/psaux.h
  freetype/include/freetype/internal/pshints.h
  freetype/include/freetype/internal/services/svbdf.h
  freetype/include/freetype/internal/services/svcfftl.h
  freetype/include/freetype/internal/services/svcid.h
  freetype/include/freetype/internal/services/svfntfmt.h
  freetype/include/freetype/internal/services/svgldict.h
  freetype/include/freetype/internal/services/svgxval.h
  freetype/include/freetype/internal/services/svkern.h
  freetype/include/freetype/internal/services/svmetric.h
  freetype/include/freetype/internal/services/svmm.h
  freetype/include/freetype/internal/services/svotval.h
  freetype/include/freetype/internal/services/svpfr.h
  freetype/include/freetype/internal/services/svpostnm.h
  freetype/include/freetype/internal/services/svprop.h
  freetype/include/freetype/internal/services/svpscmap.h
  freetype/include/freetype/internal/services/svpsinfo.h
  freetype/include/freetype/internal/services/svsfnt.h
  freetype/include/freetype/internal/services/svttcmap.h
  freetype/include/freetype/internal/services/svtteng.h
  freetype/include/freetype/internal/services/svttglyf.h
  freetype/include/freetype/internal/services/svwinfnt.h
  freetype/include/freetype/internal/sfnt.h
  freetype/include/freetype/internal/svginterface.h
  freetype/include/freetype/internal/t1types.h
  freetype/include/freetype/internal/tttypes.h
  freetype/include/freetype/internal/wofftypes.h
  freetype/include/freetype/otsvg.h
  freetype/include/freetype/t1tables.h
  freetype/include/freetype/ttnameid.h
  freetype/include/freetype/tttables.h
  freetype/include/freetype/tttags.h
  freetype/include/ft2build.h
  freetype/src/autofit/afblue.h
  freetype/src/autofit/afcjk.h
  freetype/src/autofit/afcover.h
  freetype/src/autofit/afdummy.h
  freetype/src/autofit/aferrors.h
  freetype/src/autofit/afglobal.h
  freetype/src/autofit/afhints.h
  freetype/src/autofit/afindic.h
  freetype/src/autofit/aflatin.h
  freetype/src/autofit/afloader.h
  freetype/src/autofit/afmodule.h
  freetype/src/autofit/afranges.h
  freetype/src/autofit/afscript.h
  freetype/src/autofit/afshaper.h
  freetype/src/autofit/afstyles.h
  freetype/src/autofit/aftypes.h
  freetype/src/autofit/afws-decl.h
  freetype/src/autofit/afws-iter.h
  freetype/src/autofit/ft-hb.h
  freetype/src/base/ftbase.h
  freetype/src/base/md5.h
  freetype/src/bdf/bdf.h
  freetype/src/bdf/bdfdrivr.h
  freetype/src/bdf/bdferror.h
  freetype/src/cache/ftccache.h
  freetype/src/cache/ftccback.h
  freetype/src/cache/ftcerror.h
  freetype/src/cache/ftcglyph.h
  freetype/src/cache/ftcimage.h
  freetype/src/cache/ftcmanag.h
  freetype/src/cache/ftcmru.h
  freetype/src/cache/ftcsbits.h
  freetype/src/cff/cffcmap.h
  freetype/src/cff/cffdrivr.h
  freetype/src/cff/cfferrs.h
  freetype/src/cff/cffgload.h
  freetype/src/cff/cffload.h
  freetype/src/cff/cffobjs.h
  freetype/src/cff/cffparse.h
  freetype/src/cff/cfftoken.h
  freetype/src/cid/ciderrs.h
  freetype/src/cid/cidgload.h
  freetype/src/cid/cidload.h
  freetype/src/cid/cidobjs.h
  freetype/src/cid/cidparse.h
  freetype/src/cid/cidriver.h
  freetype/src/cid/cidtoken.h
  freetype/src/gxvalid/gxvalid.h
  freetype/src/gxvalid/gxvcommn.h
  freetype/src/gxvalid/gxverror.h
  freetype/src/gxvalid/gxvfeat.h
  freetype/src/gxvalid/gxvmod.h
  freetype/src/gxvalid/gxvmort.h
  freetype/src/gxvalid/gxvmorx.h
  freetype/src/lzw/ftzopen.h
  freetype/src/otvalid/otvalid.h
  freetype/src/otvalid/otvcommn.h
  freetype/src/otvalid/otverror.h
  freetype/src/otvalid/otvgpos.h
  freetype/src/otvalid/otvmod.h
  freetype/src/pcf/pcf.h
  freetype/src/pcf/pcfdrivr.h
  freetype/src/pcf/pcferror.h
  freetype/src/pcf/pcfread.h
  freetype/src/pcf/pcfutil.h
  freetype/src/pfr/pfrcmap.h
  freetype/src/pfr/pfrdrivr.h
  freetype/src/pfr/pfrerror.h
  freetype/src/pfr/pfrgload.h
  freetype/src/pfr/pfrload.h
  freetype/src/pfr/pfrobjs.h
  freetype/src/pfr/pfrsbit.h
  freetype/src/pfr/pfrtypes.h
  freetype/src/psaux/afmparse.h
  freetype/src/psaux/cffdecode.h
  freetype/src/psaux/psarrst.h
  freetype/src/psaux/psauxerr.h
  freetype/src/psaux/psauxmod.h
  freetype/src/psaux/psblues.h
  freetype/src/psaux/psconv.h
  freetype/src/psaux/pserror.h
  freetype/src/psaux/psfixed.h
  freetype/src/psaux/psfont.h
  freetype/src/psaux/psft.h
  freetype/src/psaux/psglue.h
  freetype/src/psaux/pshints.h
  freetype/src/psaux/psintrp.h
  freetype/src/psaux/psobjs.h
  freetype/src/psaux/psread.h
  freetype/src/psaux/psstack.h
  freetype/src/psaux/pstypes.h
  freetype/src/psaux/t1cmap.h
  freetype/src/psaux/t1decode.h
  freetype/src/pshinter/pshalgo.h
  freetype/src/pshinter/pshglob.h
  freetype/src/pshinter/pshmod.h
  freetype/src/pshinter/pshnterr.h
  freetype/src/pshinter/pshrec.h
  freetype/src/psnames/psmodule.h
  freetype/src/psnames/psnamerr.h
  freetype/src/psnames/pstables.h
  freetype/src/raster/ftmisc.h
  freetype/src/raster/ftraster.h
  freetype/src/raster/ftrend1.h
  freetype/src/raster/rasterrs.h
  freetype/src/sdf/ftsdf.h
  freetype/src/sdf/ftsdfcommon.h
  freetype/src/sdf/ftsdferrs.h
  freetype/src/sdf/ftsdfrend.h
  freetype/src/sfnt/pngshim.h
  freetype/src/sfnt/sfdriver.h
  freetype/src/sfnt/sferrors.h
  freetype/src/sfnt/sfobjs.h
  freetype/src/sfnt/sfwoff.h
  freetype/src/sfnt/sfwoff2.h
  freetype/src/sfnt/ttbdf.h
  freetype/src/sfnt/ttcmap.h
  freetype/src/sfnt/ttcmapc.h
  freetype/src/sfnt/ttcolr.h
  freetype/src/sfnt/ttcpal.h
  freetype/src/sfnt/ttgpos.h
  freetype/src/sfnt/ttkern.h
  freetype/src/sfnt/ttload.h
  freetype/src/sfnt/ttmtx.h
  freetype/src/sfnt/ttpost.h
  freetype/src/sfnt/ttsbit.h
  freetype/src/sfnt/ttsvg.h
  freetype/src/sfnt/woff2tags.h
  freetype/src/smooth/ftgrays.h
  freetype/src/smooth/ftsmerrs.h
  freetype/src/smooth/ftsmooth.h
  freetype/src/svg/ftsvg.h
  freetype/src/svg/svgtypes.h
  freetype/src/truetype/ttdriver.h
  freetype/src/truetype/tterrors.h
  freetype/src/truetype/ttgload.h
  freetype/src/truetype/ttgxvar.h
  freetype/src/truetype/ttinterp.h
  freetype/src/truetype/ttobjs.h
  freetype/src/truetype/ttpload.h
  freetype/src/type1/t1afm.h
  freetype/src/type1/t1driver.h
  freetype/src/type1/t1errors.h
  freetype/src/type1/t1gload.h
  freetype/src/type1/t1load.h
  freetype/src/type1/t1objs.h
  freetype/src/type1/t1parse.h
  freetype/src/type1/t1tokens.h
  freetype/src/type42/t42drivr.h
  freetype/src/type42/t42error.h
  freetype/src/type42/t42objs.h
  freetype/src/type42/t42parse.h
  freetype/src/type42/t42types.h
  freetype/src/winfonts/fnterrs.h
  freetype/src/winfonts/winfnt.h
)

# GODOT_THIRDPARTY_FREETYPE_FILES - All files for freetype
set(GODOT_THIRDPARTY_FREETYPE_FILES
  ${GODOT_THIRDPARTY_FREETYPE_SOURCES}
  ${GODOT_THIRDPARTY_FREETYPE_HEADERS}
)
