# Generated source list for platform
# GODOT_PLATFORM_SOURCES - Source files for platform
set(GODOT_PLATFORM_SOURCES
  android/android_input_handler.cpp
  android/android_keys_utils.cpp
  android/api/api.cpp
  android/audio_driver_opensl.cpp
  android/dialog_utils_jni.cpp
  android/dir_access_jandroid.cpp
  android/display_server_android.cpp
  android/export/export_plugin.cpp
  android/export/export.cpp
  android/export/godot_plugin_config.cpp
  android/export/gradle_export_util.cpp
  android/file_access_android.cpp
  android/file_access_filesystem_jandroid.cpp
  android/game_menu_utils_jni.cpp
  android/java_class_wrapper.cpp
  android/java_godot_io_wrapper.cpp
  android/java_godot_lib_jni.cpp
  android/java_godot_view_wrapper.cpp
  android/java_godot_wrapper.cpp
  android/jni_utils.cpp
  android/net_socket_android.cpp
  android/os_android.cpp
  android/plugin/godot_plugin_jni.cpp
  android/rendering_context_driver_vulkan_android.cpp
  android/thread_jandroid.cpp
  android/tts_android.cpp
  android/variant/callable_jni.cpp
  ios/api/api.cpp
  ios/app_delegate.mm
  ios/device_metrics.m
  ios/display_layer.mm
  ios/display_server_ios.mm
  ios/export/export_plugin.cpp
  ios/export/export.cpp
  ios/export/godot_plugin_config.cpp
  ios/godot_app_delegate.m
  ios/godot_ios.mm
  ios/godot_view_renderer.mm
  ios/godot_view.mm
  ios/ios_terminal_logger.mm
  ios/ios.mm
  ios/key_mapping_ios.mm
  ios/keyboard_input_view.mm
  ios/main.m
  ios/os_ios.mm
  ios/rendering_context_driver_vulkan_ios.mm
  ios/tts_ios.mm
  ios/view_controller.mm
  linuxbsd/crash_handler_linuxbsd.cpp
  linuxbsd/dbus-so_wrap.c
  linuxbsd/export/export_plugin.cpp
  linuxbsd/export/export.cpp
  linuxbsd/fontconfig-so_wrap.c
  linuxbsd/freedesktop_at_spi_monitor.cpp
  linuxbsd/freedesktop_portal_desktop.cpp
  linuxbsd/freedesktop_screensaver.cpp
  linuxbsd/godot_linuxbsd.cpp
  linuxbsd/joypad_linux.cpp
  linuxbsd/libudev-so_wrap.c
  linuxbsd/os_linuxbsd.cpp
  linuxbsd/speechd-so_wrap.c
  linuxbsd/tts_linux.cpp
  linuxbsd/wayland/detect_prime_egl.cpp
  linuxbsd/wayland/display_server_wayland.cpp
  linuxbsd/wayland/dynwrappers/libdecor-so_wrap.c
  linuxbsd/wayland/dynwrappers/wayland-client-core-so_wrap.c
  linuxbsd/wayland/dynwrappers/wayland-cursor-so_wrap.c
  linuxbsd/wayland/dynwrappers/wayland-egl-core-so_wrap.c
  linuxbsd/wayland/egl_manager_wayland_gles.cpp
  linuxbsd/wayland/egl_manager_wayland.cpp
  linuxbsd/wayland/key_mapping_xkb.cpp
  linuxbsd/wayland/rendering_context_driver_vulkan_wayland.cpp
  linuxbsd/wayland/wayland_thread.cpp
  linuxbsd/x11/detect_prime_x11.cpp
  linuxbsd/x11/display_server_x11.cpp
  linuxbsd/x11/dynwrappers/xcursor-so_wrap.c
  linuxbsd/x11/dynwrappers/xext-so_wrap.c
  linuxbsd/x11/dynwrappers/xinerama-so_wrap.c
  linuxbsd/x11/dynwrappers/xinput2-so_wrap.c
  linuxbsd/x11/dynwrappers/xlib-so_wrap.c
  linuxbsd/x11/dynwrappers/xrandr-so_wrap.c
  linuxbsd/x11/dynwrappers/xrender-so_wrap.c
  linuxbsd/x11/gl_manager_x11_egl.cpp
  linuxbsd/x11/gl_manager_x11.cpp
  linuxbsd/x11/key_mapping_x11.cpp
  linuxbsd/x11/rendering_context_driver_vulkan_x11.cpp
  linuxbsd/xkbcommon-so_wrap.c
  macos/crash_handler_macos.mm
  macos/dir_access_macos.mm
  macos/display_server_embedded.mm
  macos/display_server_macos.mm
  macos/editor/embedded_game_view_plugin.mm
  macos/editor/embedded_process_macos.mm
  macos/embedded_debugger.mm
  macos/embedded_gl_manager.mm
  macos/export/export_plugin.cpp
  macos/export/export.cpp
  macos/gl_manager_macos_angle.mm
  macos/gl_manager_macos_legacy.mm
  macos/godot_application_delegate.mm
  macos/godot_application.mm
  macos/godot_button_view.mm
  macos/godot_content_view.mm
  macos/godot_main_macos.mm
  macos/godot_menu_delegate.mm
  macos/godot_menu_item.mm
  macos/godot_open_save_delegate.mm
  macos/godot_status_item.mm
  macos/godot_window_delegate.mm
  macos/godot_window.mm
  macos/key_mapping_macos.mm
  macos/macos_terminal_logger.mm
  macos/native_menu_macos.mm
  macos/os_macos.mm
  macos/rendering_context_driver_vulkan_macos.mm
  macos/tts_macos.mm
  web/api/api.cpp
  web/audio_driver_web.cpp
  web/display_server_web.cpp
  web/editor/web_tools_editor_plugin.cpp
  web/export/editor_http_server.cpp
  web/export/export_plugin.cpp
  web/export/export.cpp
  web/http_client_web.cpp
  web/ip_web.cpp
  web/javascript_bridge_singleton.cpp
  web/net_socket_web.cpp
  web/os_web.cpp
  web/web_main.cpp
  web/web_runtime.cpp
  web/webmidi_driver.cpp
  windows/console_wrapper_windows.cpp
  windows/crash_handler_windows_seh.cpp
  windows/crash_handler_windows_signal.cpp
  windows/display_server_windows.cpp
  windows/drop_target_windows.cpp
  windows/export/export_plugin.cpp
  windows/export/export.cpp
  windows/gl_manager_windows_angle.cpp
  windows/gl_manager_windows_native.cpp
  windows/godot_windows.cpp
  windows/joypad_windows.cpp
  windows/key_mapping_windows.cpp
  windows/native_menu_windows.cpp
  windows/os_windows.cpp
  windows/rendering_context_driver_vulkan_windows.cpp
  windows/tts_windows.cpp
  windows/wgl_detect_version.cpp
  windows/windows_terminal_logger.cpp
  windows/windows_utils.cpp
)

# GODOT_PLATFORM_HEADERS - Header files for platform
set(GODOT_PLATFORM_HEADERS
  android/android_input_handler.h
  android/android_keys_utils.h
  android/api/api.h
  android/api/java_class_wrapper.h
  android/api/jni_singleton.h
  android/audio_driver_opensl.h
  android/dialog_utils_jni.h
  android/dir_access_jandroid.h
  android/display_server_android.h
  android/export/export_plugin.h
  android/export/export.h
  android/export/godot_plugin_config.h
  android/export/gradle_export_util.h
  android/file_access_android.h
  android/file_access_filesystem_jandroid.h
  android/game_menu_utils_jni.h
  android/java_godot_io_wrapper.h
  android/java_godot_lib_jni.h
  android/java_godot_view_wrapper.h
  android/java_godot_wrapper.h
  android/jni_utils.h
  android/net_socket_android.h
  android/os_android.h
  android/platform_config.h
  android/platform_gl.h
  android/plugin/godot_plugin_jni.h
  android/rendering_context_driver_vulkan_android.h
  android/thread_jandroid.h
  android/tts_android.h
  android/variant/callable_jni.h
  ios/api/api.h
  ios/app_delegate.h
  ios/device_metrics.h
  ios/display_layer.h
  ios/display_server_ios.h
  ios/export/export_plugin.h
  ios/export/export.h
  ios/export/godot_plugin_config.h
  ios/godot_app_delegate.h
  ios/godot_view_renderer.h
  ios/godot_view.h
  ios/ios_terminal_logger.h
  ios/ios.h
  ios/key_mapping_ios.h
  ios/keyboard_input_view.h
  ios/os_ios.h
  ios/platform_config.h
  ios/platform_gl.h
  ios/platform_thread.h
  ios/rendering_context_driver_vulkan_ios.h
  ios/tts_ios.h
  ios/view_controller.h
  linuxbsd/crash_handler_linuxbsd.h
  linuxbsd/dbus-so_wrap.h
  linuxbsd/export/export_plugin.h
  linuxbsd/export/export.h
  linuxbsd/fontconfig-so_wrap.h
  linuxbsd/freedesktop_at_spi_monitor.h
  linuxbsd/freedesktop_portal_desktop.h
  linuxbsd/freedesktop_screensaver.h
  linuxbsd/joypad_linux.h
  linuxbsd/libudev-so_wrap.h
  linuxbsd/os_linuxbsd.h
  linuxbsd/platform_config.h
  linuxbsd/platform_gl.h
  linuxbsd/speechd-so_wrap.h
  linuxbsd/tts_linux.h
  linuxbsd/wayland/detect_prime_egl.h
  linuxbsd/wayland/display_server_wayland.h
  linuxbsd/wayland/dynwrappers/libdecor-so_wrap.h
  linuxbsd/wayland/dynwrappers/wayland-client-core-so_wrap.h
  linuxbsd/wayland/dynwrappers/wayland-cursor-so_wrap.h
  linuxbsd/wayland/dynwrappers/wayland-egl-core-so_wrap.h
  linuxbsd/wayland/egl_manager_wayland_gles.h
  linuxbsd/wayland/egl_manager_wayland.h
  linuxbsd/wayland/key_mapping_xkb.h
  linuxbsd/wayland/rendering_context_driver_vulkan_wayland.h
  linuxbsd/wayland/wayland_thread.h
  linuxbsd/x11/detect_prime_x11.h
  linuxbsd/x11/display_server_x11.h
  linuxbsd/x11/dynwrappers/xcursor-so_wrap.h
  linuxbsd/x11/dynwrappers/xext-so_wrap.h
  linuxbsd/x11/dynwrappers/xinerama-so_wrap.h
  linuxbsd/x11/dynwrappers/xinput2-so_wrap.h
  linuxbsd/x11/dynwrappers/xlib-so_wrap.h
  linuxbsd/x11/dynwrappers/xrandr-so_wrap.h
  linuxbsd/x11/dynwrappers/xrender-so_wrap.h
  linuxbsd/x11/gl_manager_x11_egl.h
  linuxbsd/x11/gl_manager_x11.h
  linuxbsd/x11/key_mapping_x11.h
  linuxbsd/x11/rendering_context_driver_vulkan_x11.h
  linuxbsd/xkbcommon-so_wrap.h
  macos/crash_handler_macos.h
  macos/dir_access_macos.h
  macos/display_server_embedded.h
  macos/display_server_macos.h
  macos/editor/embedded_game_view_plugin.h
  macos/editor/embedded_process_macos.h
  macos/embedded_debugger.h
  macos/embedded_gl_manager.h
  macos/export/export_plugin.h
  macos/export/export.h
  macos/gl_manager_macos_angle.h
  macos/gl_manager_macos_legacy.h
  macos/godot_application_delegate.h
  macos/godot_application.h
  macos/godot_button_view.h
  macos/godot_content_view.h
  macos/godot_menu_delegate.h
  macos/godot_menu_item.h
  macos/godot_open_save_delegate.h
  macos/godot_status_item.h
  macos/godot_window_delegate.h
  macos/godot_window.h
  macos/key_mapping_macos.h
  macos/macos_quartz_core_spi.h
  macos/macos_terminal_logger.h
  macos/native_menu_macos.h
  macos/os_macos.h
  macos/platform_config.h
  macos/platform_gl.h
  macos/platform_thread.h
  macos/rendering_context_driver_vulkan_macos.h
  macos/tts_macos.h
  register_platform_apis.h
  web/api/api.h
  web/api/javascript_bridge_singleton.h
  web/audio_driver_web.h
  web/display_server_web.h
  web/editor/web_tools_editor_plugin.h
  web/export/editor_http_server.h
  web/export/export_plugin.h
  web/export/export.h
  web/godot_audio.h
  web/godot_js.h
  web/godot_midi.h
  web/godot_webgl2.h
  web/http_client_web.h
  web/ip_web.h
  web/net_socket_web.h
  web/os_web.h
  web/platform_config.h
  web/platform_gl.h
  web/webmidi_driver.h
  windows/crash_handler_windows.h
  windows/display_server_windows.h
  windows/drop_target_windows.h
  windows/export/export_plugin.h
  windows/export/export.h
  windows/gl_manager_windows_angle.h
  windows/gl_manager_windows_native.h
  windows/joypad_windows.h
  windows/key_mapping_windows.h
  windows/lang_table.h
  windows/native_menu_windows.h
  windows/os_windows.h
  windows/platform_config.h
  windows/platform_gl.h
  windows/rendering_context_driver_vulkan_windows.h
  windows/tts_windows.h
  windows/wgl_detect_version.h
  windows/windows_terminal_logger.h
  windows/windows_utils.h
)

# GODOT_PLATFORM_FILES - All files for platform
set(GODOT_PLATFORM_FILES
  ${GODOT_PLATFORM_SOURCES}
  ${GODOT_PLATFORM_HEADERS}
)
