# Generated source list for scene
# GODOT_SCENE_SOURCES - Source files for scene
set(GODOT_SCENE_SOURCES
  2d/animated_sprite_2d.cpp
  2d/audio_listener_2d.cpp
  2d/audio_stream_player_2d.cpp
  2d/back_buffer_copy.cpp
  2d/camera_2d.cpp
  2d/canvas_group.cpp
  2d/canvas_modulate.cpp
  2d/cpu_particles_2d.cpp
  2d/gpu_particles_2d.cpp
  2d/light_2d.cpp
  2d/light_occluder_2d.cpp
  2d/line_2d.cpp
  2d/line_builder.cpp
  2d/marker_2d.cpp
  2d/mesh_instance_2d.cpp
  2d/multimesh_instance_2d.cpp
  2d/navigation/navigation_agent_2d.cpp
  2d/navigation/navigation_link_2d.cpp
  2d/navigation/navigation_obstacle_2d.cpp
  2d/navigation/navigation_region_2d.cpp
  2d/node_2d.cpp
  2d/parallax_2d.cpp
  2d/parallax_background.cpp
  2d/parallax_layer.cpp
  2d/path_2d.cpp
  2d/physics/animatable_body_2d.cpp
  2d/physics/area_2d.cpp
  2d/physics/character_body_2d.cpp
  2d/physics/collision_object_2d.cpp
  2d/physics/collision_polygon_2d.cpp
  2d/physics/collision_shape_2d.cpp
  2d/physics/joints/damped_spring_joint_2d.cpp
  2d/physics/joints/groove_joint_2d.cpp
  2d/physics/joints/joint_2d.cpp
  2d/physics/joints/pin_joint_2d.cpp
  2d/physics/kinematic_collision_2d.cpp
  2d/physics/physical_bone_2d.cpp
  2d/physics/physics_body_2d.cpp
  2d/physics/ray_cast_2d.cpp
  2d/physics/rigid_body_2d.cpp
  2d/physics/shape_cast_2d.cpp
  2d/physics/static_body_2d.cpp
  2d/physics/touch_screen_button.cpp
  2d/polygon_2d.cpp
  2d/remote_transform_2d.cpp
  2d/skeleton_2d.cpp
  2d/sprite_2d.cpp
  2d/tile_map_layer.cpp
  2d/tile_map.cpp
  2d/visible_on_screen_notifier_2d.cpp
  3d/audio_listener_3d.cpp
  3d/audio_stream_player_3d.cpp
  3d/bone_attachment_3d.cpp
  3d/camera_3d.cpp
  3d/cpu_particles_3d.cpp
  3d/decal.cpp
  3d/fog_volume.cpp
  3d/gpu_particles_3d.cpp
  3d/gpu_particles_collision_3d.cpp
  3d/importer_mesh_instance_3d.cpp
  3d/label_3d.cpp
  3d/light_3d.cpp
  3d/lightmap_gi.cpp
  3d/lightmap_probe.cpp
  3d/lightmapper.cpp
  3d/look_at_modifier_3d.cpp
  3d/marker_3d.cpp
  3d/mesh_instance_3d.cpp
  3d/multimesh_instance_3d.cpp
  3d/navigation/navigation_agent_3d.cpp
  3d/navigation/navigation_link_3d.cpp
  3d/navigation/navigation_obstacle_3d.cpp
  3d/navigation/navigation_region_3d.cpp
  3d/node_3d.cpp
  3d/occluder_instance_3d.cpp
  3d/path_3d.cpp
  3d/physics/animatable_body_3d.cpp
  3d/physics/area_3d.cpp
  3d/physics/character_body_3d.cpp
  3d/physics/collision_object_3d.cpp
  3d/physics/collision_polygon_3d.cpp
  3d/physics/collision_shape_3d.cpp
  3d/physics/joints/cone_twist_joint_3d.cpp
  3d/physics/joints/generic_6dof_joint_3d.cpp
  3d/physics/joints/hinge_joint_3d.cpp
  3d/physics/joints/joint_3d.cpp
  3d/physics/joints/pin_joint_3d.cpp
  3d/physics/joints/slider_joint_3d.cpp
  3d/physics/kinematic_collision_3d.cpp
  3d/physics/physical_bone_3d.cpp
  3d/physics/physical_bone_simulator_3d.cpp
  3d/physics/physics_body_3d.cpp
  3d/physics/ray_cast_3d.cpp
  3d/physics/rigid_body_3d.cpp
  3d/physics/shape_cast_3d.cpp
  3d/physics/soft_body_3d.cpp
  3d/physics/spring_arm_3d.cpp
  3d/physics/static_body_3d.cpp
  3d/physics/vehicle_body_3d.cpp
  3d/reflection_probe.cpp
  3d/remote_transform_3d.cpp
  3d/retarget_modifier_3d.cpp
  3d/skeleton_3d.cpp
  3d/skeleton_ik_3d.cpp
  3d/skeleton_modifier_3d.cpp
  3d/spring_bone_collision_3d.cpp
  3d/spring_bone_collision_capsule_3d.cpp
  3d/spring_bone_collision_plane_3d.cpp
  3d/spring_bone_collision_sphere_3d.cpp
  3d/spring_bone_simulator_3d.cpp
  3d/sprite_3d.cpp
  3d/velocity_tracker_3d.cpp
  3d/visible_on_screen_notifier_3d.cpp
  3d/visual_instance_3d.cpp
  3d/voxel_gi.cpp
  3d/voxelizer.cpp
  3d/world_environment.cpp
  3d/xr/xr_body_modifier_3d.cpp
  3d/xr/xr_face_modifier_3d.cpp
  3d/xr/xr_hand_modifier_3d.cpp
  3d/xr/xr_nodes.cpp
  animation/animation_blend_space_1d.cpp
  animation/animation_blend_space_2d.cpp
  animation/animation_blend_tree.cpp
  animation/animation_mixer.cpp
  animation/animation_node_extension.cpp
  animation/animation_node_state_machine.cpp
  animation/animation_player.cpp
  animation/animation_tree.cpp
  animation/root_motion_view.cpp
  animation/tween.cpp
  audio/audio_stream_player_internal.cpp
  audio/audio_stream_player.cpp
  debugger/scene_debugger.cpp
  gui/aspect_ratio_container.cpp
  gui/base_button.cpp
  gui/box_container.cpp
  gui/button.cpp
  gui/center_container.cpp
  gui/check_box.cpp
  gui/check_button.cpp
  gui/code_edit.cpp
  gui/color_mode.cpp
  gui/color_picker_shape.cpp
  gui/color_picker.cpp
  gui/color_rect.cpp
  gui/container.cpp
  gui/control.cpp
  gui/dialogs.cpp
  gui/file_dialog.cpp
  gui/flow_container.cpp
  gui/foldable_container.cpp
  gui/graph_edit_arranger.cpp
  gui/graph_edit.cpp
  gui/graph_element.cpp
  gui/graph_frame.cpp
  gui/graph_node.cpp
  gui/grid_container.cpp
  gui/item_list.cpp
  gui/label.cpp
  gui/line_edit.cpp
  gui/link_button.cpp
  gui/margin_container.cpp
  gui/menu_bar.cpp
  gui/menu_button.cpp
  gui/nine_patch_rect.cpp
  gui/option_button.cpp
  gui/panel_container.cpp
  gui/panel.cpp
  gui/popup_menu.cpp
  gui/popup.cpp
  gui/progress_bar.cpp
  gui/range.cpp
  gui/reference_rect.cpp
  gui/rich_text_effect.cpp
  gui/rich_text_label.cpp
  gui/scroll_bar.cpp
  gui/scroll_container.cpp
  gui/separator.cpp
  gui/slider.cpp
  gui/spin_box.cpp
  gui/split_container.cpp
  gui/subviewport_container.cpp
  gui/tab_bar.cpp
  gui/tab_container.cpp
  gui/text_edit.cpp
  gui/texture_button.cpp
  gui/texture_progress_bar.cpp
  gui/texture_rect.cpp
  gui/tree.cpp
  gui/video_stream_player.cpp
  gui/view_panner.cpp
  main/canvas_item.cpp
  main/canvas_layer.cpp
  main/http_request.cpp
  main/instance_placeholder.cpp
  main/missing_node.cpp
  main/multiplayer_api.cpp
  main/multiplayer_peer.cpp
  main/node.cpp
  main/resource_preloader.cpp
  main/scene_tree_fti.cpp
  main/scene_tree.cpp
  main/shader_globals_override.cpp
  main/status_indicator.cpp
  main/timer.cpp
  main/viewport.cpp
  main/window.cpp
  property_list_helper.cpp
  property_utils.cpp
  register_scene_types.cpp
  resources/2d/capsule_shape_2d.cpp
  resources/2d/circle_shape_2d.cpp
  resources/2d/concave_polygon_shape_2d.cpp
  resources/2d/convex_polygon_shape_2d.cpp
  resources/2d/navigation_mesh_source_geometry_data_2d.cpp
  resources/2d/navigation_polygon.cpp
  resources/2d/polygon_path_finder.cpp
  resources/2d/rectangle_shape_2d.cpp
  resources/2d/segment_shape_2d.cpp
  resources/2d/separation_ray_shape_2d.cpp
  resources/2d/shape_2d.cpp
  resources/2d/skeleton/skeleton_modification_2d_ccdik.cpp
  resources/2d/skeleton/skeleton_modification_2d_fabrik.cpp
  resources/2d/skeleton/skeleton_modification_2d_jiggle.cpp
  resources/2d/skeleton/skeleton_modification_2d_lookat.cpp
  resources/2d/skeleton/skeleton_modification_2d_physicalbones.cpp
  resources/2d/skeleton/skeleton_modification_2d_stackholder.cpp
  resources/2d/skeleton/skeleton_modification_2d_twoboneik.cpp
  resources/2d/skeleton/skeleton_modification_2d.cpp
  resources/2d/skeleton/skeleton_modification_stack_2d.cpp
  resources/2d/tile_set.cpp
  resources/2d/world_boundary_shape_2d.cpp
  resources/3d/box_shape_3d.cpp
  resources/3d/capsule_shape_3d.cpp
  resources/3d/concave_polygon_shape_3d.cpp
  resources/3d/convex_polygon_shape_3d.cpp
  resources/3d/cylinder_shape_3d.cpp
  resources/3d/fog_material.cpp
  resources/3d/height_map_shape_3d.cpp
  resources/3d/importer_mesh.cpp
  resources/3d/mesh_library.cpp
  resources/3d/navigation_mesh_source_geometry_data_3d.cpp
  resources/3d/primitive_meshes.cpp
  resources/3d/separation_ray_shape_3d.cpp
  resources/3d/shape_3d.cpp
  resources/3d/skin.cpp
  resources/3d/sky_material.cpp
  resources/3d/sphere_shape_3d.cpp
  resources/3d/world_3d.cpp
  resources/3d/world_boundary_shape_3d.cpp
  resources/animated_texture.cpp
  resources/animation_library.cpp
  resources/animation.cpp
  resources/atlas_texture.cpp
  resources/audio_stream_polyphonic.cpp
  resources/audio_stream_wav.cpp
  resources/bit_map.cpp
  resources/bone_map.cpp
  resources/camera_attributes.cpp
  resources/camera_texture.cpp
  resources/canvas_item_material.cpp
  resources/color_palette.cpp
  resources/compositor.cpp
  resources/compressed_texture.cpp
  resources/curve_texture.cpp
  resources/curve.cpp
  resources/environment.cpp
  resources/external_texture.cpp
  resources/font.cpp
  resources/gradient_texture.cpp
  resources/gradient.cpp
  resources/image_texture.cpp
  resources/immediate_mesh.cpp
  resources/label_settings.cpp
  resources/material.cpp
  resources/mesh_data_tool.cpp
  resources/mesh_texture.cpp
  resources/mesh.cpp
  resources/multimesh.cpp
  resources/navigation_mesh.cpp
  resources/packed_scene.cpp
  resources/particle_process_material.cpp
  resources/physics_material.cpp
  resources/placeholder_textures.cpp
  resources/portable_compressed_texture.cpp
  resources/resource_format_text.cpp
  resources/shader_include.cpp
  resources/shader.cpp
  resources/skeleton_profile.cpp
  resources/sky.cpp
  resources/sprite_frames.cpp
  resources/style_box_flat.cpp
  resources/style_box_line.cpp
  resources/style_box_texture.cpp
  resources/style_box.cpp
  resources/surface_tool.cpp
  resources/svg_texture.cpp
  resources/syntax_highlighter.cpp
  resources/text_file.cpp
  resources/text_line.cpp
  resources/text_paragraph.cpp
  resources/texture_rd.cpp
  resources/texture.cpp
  resources/theme.cpp
  resources/video_stream.cpp
  resources/visual_shader_nodes.cpp
  resources/visual_shader_particle_nodes.cpp
  resources/visual_shader_sdf_nodes.cpp
  resources/visual_shader.cpp
  resources/world_2d.cpp
  theme/default_theme.cpp
  theme/theme_db.cpp
  theme/theme_owner.cpp
)

# GODOT_SCENE_HEADERS - Header files for scene
set(GODOT_SCENE_HEADERS
  2d/animated_sprite_2d.h
  2d/audio_listener_2d.h
  2d/audio_stream_player_2d.h
  2d/back_buffer_copy.h
  2d/camera_2d.h
  2d/canvas_group.h
  2d/canvas_modulate.h
  2d/cpu_particles_2d.h
  2d/gpu_particles_2d.h
  2d/light_2d.h
  2d/light_occluder_2d.h
  2d/line_2d.h
  2d/line_builder.h
  2d/marker_2d.h
  2d/mesh_instance_2d.h
  2d/multimesh_instance_2d.h
  2d/navigation/navigation_agent_2d.h
  2d/navigation/navigation_link_2d.h
  2d/navigation/navigation_obstacle_2d.h
  2d/navigation/navigation_region_2d.h
  2d/node_2d.h
  2d/parallax_2d.h
  2d/parallax_background.h
  2d/parallax_layer.h
  2d/path_2d.h
  2d/physics/animatable_body_2d.h
  2d/physics/area_2d.h
  2d/physics/character_body_2d.h
  2d/physics/collision_object_2d.h
  2d/physics/collision_polygon_2d.h
  2d/physics/collision_shape_2d.h
  2d/physics/joints/damped_spring_joint_2d.h
  2d/physics/joints/groove_joint_2d.h
  2d/physics/joints/joint_2d.h
  2d/physics/joints/pin_joint_2d.h
  2d/physics/kinematic_collision_2d.h
  2d/physics/physical_bone_2d.h
  2d/physics/physics_body_2d.h
  2d/physics/ray_cast_2d.h
  2d/physics/rigid_body_2d.h
  2d/physics/shape_cast_2d.h
  2d/physics/static_body_2d.h
  2d/physics/touch_screen_button.h
  2d/polygon_2d.h
  2d/remote_transform_2d.h
  2d/skeleton_2d.h
  2d/sprite_2d.h
  2d/tile_map_layer.h
  2d/tile_map.h
  2d/visible_on_screen_notifier_2d.h
  3d/audio_listener_3d.h
  3d/audio_stream_player_3d.h
  3d/bone_attachment_3d.h
  3d/camera_3d.h
  3d/cpu_particles_3d.h
  3d/decal.h
  3d/fog_volume.h
  3d/gpu_particles_3d.h
  3d/gpu_particles_collision_3d.h
  3d/importer_mesh_instance_3d.h
  3d/label_3d.h
  3d/light_3d.h
  3d/lightmap_gi.h
  3d/lightmap_probe.h
  3d/lightmapper.h
  3d/look_at_modifier_3d.h
  3d/marker_3d.h
  3d/mesh_instance_3d.h
  3d/multimesh_instance_3d.h
  3d/navigation/navigation_agent_3d.h
  3d/navigation/navigation_link_3d.h
  3d/navigation/navigation_obstacle_3d.h
  3d/navigation/navigation_region_3d.h
  3d/node_3d.h
  3d/occluder_instance_3d.h
  3d/path_3d.h
  3d/physics/animatable_body_3d.h
  3d/physics/area_3d.h
  3d/physics/character_body_3d.h
  3d/physics/collision_object_3d.h
  3d/physics/collision_polygon_3d.h
  3d/physics/collision_shape_3d.h
  3d/physics/joints/cone_twist_joint_3d.h
  3d/physics/joints/generic_6dof_joint_3d.h
  3d/physics/joints/hinge_joint_3d.h
  3d/physics/joints/joint_3d.h
  3d/physics/joints/pin_joint_3d.h
  3d/physics/joints/slider_joint_3d.h
  3d/physics/kinematic_collision_3d.h
  3d/physics/physical_bone_3d.h
  3d/physics/physical_bone_simulator_3d.h
  3d/physics/physics_body_3d.h
  3d/physics/ray_cast_3d.h
  3d/physics/rigid_body_3d.h
  3d/physics/shape_cast_3d.h
  3d/physics/soft_body_3d.h
  3d/physics/spring_arm_3d.h
  3d/physics/static_body_3d.h
  3d/physics/vehicle_body_3d.h
  3d/reflection_probe.h
  3d/remote_transform_3d.h
  3d/retarget_modifier_3d.h
  3d/skeleton_3d.h
  3d/skeleton_ik_3d.h
  3d/skeleton_modifier_3d.h
  3d/spring_bone_collision_3d.h
  3d/spring_bone_collision_capsule_3d.h
  3d/spring_bone_collision_plane_3d.h
  3d/spring_bone_collision_sphere_3d.h
  3d/spring_bone_simulator_3d.h
  3d/sprite_3d.h
  3d/velocity_tracker_3d.h
  3d/visible_on_screen_notifier_3d.h
  3d/visual_instance_3d.h
  3d/voxel_gi.h
  3d/voxelizer.h
  3d/world_environment.h
  3d/xr/xr_body_modifier_3d.h
  3d/xr/xr_face_modifier_3d.h
  3d/xr/xr_hand_modifier_3d.h
  3d/xr/xr_nodes.h
  animation/animation_blend_space_1d.h
  animation/animation_blend_space_2d.h
  animation/animation_blend_tree.h
  animation/animation_mixer.h
  animation/animation_node_extension.h
  animation/animation_node_state_machine.h
  animation/animation_player.h
  animation/animation_tree.h
  animation/easing_equations.h
  animation/root_motion_view.h
  animation/tween.h
  audio/audio_stream_player_internal.h
  audio/audio_stream_player.h
  debugger/scene_debugger.h
  gui/aspect_ratio_container.h
  gui/base_button.h
  gui/box_container.h
  gui/button.h
  gui/center_container.h
  gui/check_box.h
  gui/check_button.h
  gui/code_edit.h
  gui/color_mode.h
  gui/color_picker_shape.h
  gui/color_picker.h
  gui/color_rect.h
  gui/container.h
  gui/control.h
  gui/dialogs.h
  gui/file_dialog.h
  gui/flow_container.h
  gui/foldable_container.h
  gui/graph_edit_arranger.h
  gui/graph_edit.h
  gui/graph_element.h
  gui/graph_frame.h
  gui/graph_node.h
  gui/grid_container.h
  gui/item_list.h
  gui/label.h
  gui/line_edit.h
  gui/link_button.h
  gui/margin_container.h
  gui/menu_bar.h
  gui/menu_button.h
  gui/nine_patch_rect.h
  gui/option_button.h
  gui/panel_container.h
  gui/panel.h
  gui/popup_menu.h
  gui/popup.h
  gui/progress_bar.h
  gui/range.h
  gui/reference_rect.h
  gui/rich_text_effect.h
  gui/rich_text_label.h
  gui/scroll_bar.h
  gui/scroll_container.h
  gui/separator.h
  gui/slider.h
  gui/spin_box.h
  gui/split_container.h
  gui/subviewport_container.h
  gui/tab_bar.h
  gui/tab_container.h
  gui/text_edit.h
  gui/texture_button.h
  gui/texture_progress_bar.h
  gui/texture_rect.h
  gui/tree.h
  gui/video_stream_player.h
  gui/view_panner.h
  main/canvas_item.h
  main/canvas_layer.h
  main/http_request.h
  main/instance_placeholder.h
  main/missing_node.h
  main/multiplayer_api.h
  main/multiplayer_peer.h
  main/node.h
  main/resource_preloader.h
  main/scene_tree_fti.h
  main/scene_tree.h
  main/shader_globals_override.h
  main/status_indicator.h
  main/timer.h
  main/viewport.h
  main/window.h
  property_list_helper.h
  property_utils.h
  register_scene_types.h
  resources/2d/capsule_shape_2d.h
  resources/2d/circle_shape_2d.h
  resources/2d/concave_polygon_shape_2d.h
  resources/2d/convex_polygon_shape_2d.h
  resources/2d/navigation_mesh_source_geometry_data_2d.h
  resources/2d/navigation_polygon.h
  resources/2d/polygon_path_finder.h
  resources/2d/rectangle_shape_2d.h
  resources/2d/segment_shape_2d.h
  resources/2d/separation_ray_shape_2d.h
  resources/2d/shape_2d.h
  resources/2d/skeleton/skeleton_modification_2d_ccdik.h
  resources/2d/skeleton/skeleton_modification_2d_fabrik.h
  resources/2d/skeleton/skeleton_modification_2d_jiggle.h
  resources/2d/skeleton/skeleton_modification_2d_lookat.h
  resources/2d/skeleton/skeleton_modification_2d_physicalbones.h
  resources/2d/skeleton/skeleton_modification_2d_stackholder.h
  resources/2d/skeleton/skeleton_modification_2d_twoboneik.h
  resources/2d/skeleton/skeleton_modification_2d.h
  resources/2d/skeleton/skeleton_modification_stack_2d.h
  resources/2d/tile_set.h
  resources/2d/world_boundary_shape_2d.h
  resources/3d/box_shape_3d.h
  resources/3d/capsule_shape_3d.h
  resources/3d/concave_polygon_shape_3d.h
  resources/3d/convex_polygon_shape_3d.h
  resources/3d/cylinder_shape_3d.h
  resources/3d/fog_material.h
  resources/3d/height_map_shape_3d.h
  resources/3d/importer_mesh.h
  resources/3d/mesh_library.h
  resources/3d/navigation_mesh_source_geometry_data_3d.h
  resources/3d/primitive_meshes.h
  resources/3d/separation_ray_shape_3d.h
  resources/3d/shape_3d.h
  resources/3d/skin.h
  resources/3d/sky_material.h
  resources/3d/sphere_shape_3d.h
  resources/3d/world_3d.h
  resources/3d/world_boundary_shape_3d.h
  resources/animated_texture.h
  resources/animation_library.h
  resources/animation.h
  resources/atlas_texture.h
  resources/audio_stream_polyphonic.h
  resources/audio_stream_wav.h
  resources/bit_map.h
  resources/bone_map.h
  resources/camera_attributes.h
  resources/camera_texture.h
  resources/canvas_item_material.h
  resources/color_palette.h
  resources/compositor.h
  resources/compressed_texture.h
  resources/curve_texture.h
  resources/curve.h
  resources/environment.h
  resources/external_texture.h
  resources/font.h
  resources/gradient_texture.h
  resources/gradient.h
  resources/image_texture.h
  resources/immediate_mesh.h
  resources/label_settings.h
  resources/material.h
  resources/mesh_data_tool.h
  resources/mesh_texture.h
  resources/mesh.h
  resources/multimesh.h
  resources/navigation_mesh.h
  resources/packed_scene.h
  resources/particle_process_material.h
  resources/physics_material.h
  resources/placeholder_textures.h
  resources/portable_compressed_texture.h
  resources/resource_format_text.h
  resources/shader_include.h
  resources/shader.h
  resources/skeleton_profile.h
  resources/sky.h
  resources/sprite_frames.h
  resources/style_box_flat.h
  resources/style_box_line.h
  resources/style_box_texture.h
  resources/style_box.h
  resources/surface_tool.h
  resources/svg_texture.h
  resources/syntax_highlighter.h
  resources/text_file.h
  resources/text_line.h
  resources/text_paragraph.h
  resources/texture_rd.h
  resources/texture.h
  resources/theme.h
  resources/video_stream.h
  resources/visual_shader_nodes.h
  resources/visual_shader_particle_nodes.h
  resources/visual_shader_sdf_nodes.h
  resources/visual_shader.h
  resources/world_2d.h
  scene_string_names.h
  theme/default_theme.h
  theme/theme_db.h
  theme/theme_owner.h
)

# GODOT_SCENE_FILES - All files for scene
set(GODOT_SCENE_FILES
  ${GODOT_SCENE_SOURCES}
  ${GODOT_SCENE_HEADERS}
)
