# Generated source list for drivers
# GODOT_DRIVERS_SOURCES - Source files for drivers
set(GODOT_DRIVERS_SOURCES
  accesskit/accessibility_driver_accesskit.cpp
  accesskit/dynwrappers/accesskit-dll_wrap.c
  accesskit/dynwrappers/accesskit-dylib_wrap.c
  accesskit/dynwrappers/accesskit-so_wrap.c
  alsa/asound-so_wrap.c
  alsa/audio_driver_alsa.cpp
  alsamidi/midi_driver_alsamidi.cpp
  apple/joypad_apple.mm
  apple/thread_apple.cpp
  coreaudio/audio_driver_coreaudio.mm
  coremidi/midi_driver_coremidi.mm
  d3d12/d3d12_hooks.cpp
  d3d12/d3d12ma.cpp
  d3d12/dxil_hash.cpp
  d3d12/rendering_context_driver_d3d12.cpp
  d3d12/rendering_device_driver_d3d12.cpp
  egl/egl_manager.cpp
  gles3/effects/copy_effects.cpp
  gles3/effects/cubemap_filter.cpp
  gles3/effects/feed_effects.cpp
  gles3/effects/glow.cpp
  gles3/effects/post_effects.cpp
  gles3/environment/fog.cpp
  gles3/environment/gi.cpp
  gles3/rasterizer_canvas_gles3.cpp
  gles3/rasterizer_gles3.cpp
  gles3/rasterizer_scene_gles3.cpp
  gles3/shader_gles3.cpp
  gles3/storage/config.cpp
  gles3/storage/light_storage.cpp
  gles3/storage/material_storage.cpp
  gles3/storage/mesh_storage.cpp
  gles3/storage/particles_storage.cpp
  gles3/storage/render_scene_buffers_gles3.cpp
  gles3/storage/texture_storage.cpp
  gles3/storage/utilities.cpp
  metal/metal_device_properties.mm
  metal/metal_objects.mm
  metal/pixel_formats.mm
  metal/rendering_context_driver_metal.mm
  metal/rendering_device_driver_metal.mm
  png/image_loader_png.cpp
  png/png_driver_common.cpp
  png/resource_saver_png.cpp
  pulseaudio/audio_driver_pulseaudio.cpp
  pulseaudio/pulse-so_wrap.c
  register_driver_types.cpp
  unix/dir_access_unix.cpp
  unix/file_access_unix_pipe.cpp
  unix/file_access_unix.cpp
  unix/ip_unix.cpp
  unix/net_socket_unix.cpp
  unix/os_unix.cpp
  unix/syslog_logger.cpp
  unix/thread_posix.cpp
  vulkan/rendering_context_driver_vulkan.cpp
  vulkan/rendering_device_driver_vulkan.cpp
  vulkan/vulkan_hooks.cpp
  wasapi/audio_driver_wasapi.cpp
  windows/dir_access_windows.cpp
  windows/file_access_windows_pipe.cpp
  windows/file_access_windows.cpp
  windows/ip_windows.cpp
  windows/net_socket_winsock.cpp
  windows/thread_windows.cpp
  winmidi/midi_driver_winmidi.cpp
  xaudio2/audio_driver_xaudio2.cpp
)

# GODOT_DRIVERS_HEADERS - Header files for drivers
set(GODOT_DRIVERS_HEADERS
  accesskit/accessibility_driver_accesskit.h
  accesskit/dynwrappers/accesskit-dll_wrap.h
  accesskit/dynwrappers/accesskit-dylib_wrap.h
  accesskit/dynwrappers/accesskit-so_wrap.h
  alsa/asound-so_wrap.h
  alsa/audio_driver_alsa.h
  alsamidi/midi_driver_alsamidi.h
  apple/joypad_apple.h
  apple/thread_apple.h
  coreaudio/audio_driver_coreaudio.h
  coremidi/midi_driver_coremidi.h
  d3d12/d3d12_godot_nir_bridge.h
  d3d12/d3d12_hooks.h
  d3d12/dxil_hash.h
  d3d12/rendering_context_driver_d3d12.h
  d3d12/rendering_device_driver_d3d12.h
  egl/egl_manager.h
  gles3/effects/copy_effects.h
  gles3/effects/cubemap_filter.h
  gles3/effects/feed_effects.h
  gles3/effects/glow.h
  gles3/effects/post_effects.h
  gles3/environment/fog.h
  gles3/environment/gi.h
  gles3/rasterizer_canvas_gles3.h
  gles3/rasterizer_gles3.h
  gles3/rasterizer_scene_gles3.h
  gles3/shader_gles3.h
  gles3/storage/config.h
  gles3/storage/light_storage.h
  gles3/storage/material_storage.h
  gles3/storage/mesh_storage.h
  gles3/storage/particles_storage.h
  gles3/storage/render_scene_buffers_gles3.h
  gles3/storage/texture_storage.h
  gles3/storage/utilities.h
  metal/inflection_map.h
  metal/metal_device_properties.h
  metal/metal_objects.h
  metal/metal_utils.h
  metal/pixel_formats.h
  metal/rendering_context_driver_metal.h
  metal/rendering_device_driver_metal.h
  png/image_loader_png.h
  png/png_driver_common.h
  png/resource_saver_png.h
  pulseaudio/audio_driver_pulseaudio.h
  pulseaudio/pulse-so_wrap.h
  register_driver_types.h
  unix/dir_access_unix.h
  unix/file_access_unix_pipe.h
  unix/file_access_unix.h
  unix/ip_unix.h
  unix/net_socket_unix.h
  unix/os_unix.h
  unix/syslog_logger.h
  unix/thread_posix.h
  vulkan/godot_vulkan.h
  vulkan/rendering_context_driver_vulkan.h
  vulkan/rendering_device_driver_vulkan.h
  vulkan/vulkan_hooks.h
  wasapi/audio_driver_wasapi.h
  windows/dir_access_windows.h
  windows/file_access_windows_pipe.h
  windows/file_access_windows.h
  windows/ip_windows.h
  windows/net_socket_winsock.h
  windows/thread_windows.h
  winmidi/midi_driver_winmidi.h
  xaudio2/audio_driver_xaudio2.h
)

# GODOT_DRIVERS_FILES - All files for drivers
set(GODOT_DRIVERS_FILES
  ${GODOT_DRIVERS_SOURCES}
  ${GODOT_DRIVERS_HEADERS}
)
