# Generated source list for servers (component-relative paths)
# GODOT_SERVERS_SOURCES - Source files for servers
set(GODOT_SERVERS_SOURCES
  audio_server.cpp
  audio/audio_driver_dummy.cpp
  audio/audio_effect.cpp
  audio/audio_filter_sw.cpp
  audio/audio_rb_resampler.cpp
  audio/audio_stream.cpp
  audio/effects/audio_effect_amplify.cpp
  audio/effects/audio_effect_capture.cpp
  audio/effects/audio_effect_chorus.cpp
  audio/effects/audio_effect_compressor.cpp
  audio/effects/audio_effect_delay.cpp
  audio/effects/audio_effect_distortion.cpp
  audio/effects/audio_effect_eq.cpp
  audio/effects/audio_effect_filter.cpp
  audio/effects/audio_effect_hard_limiter.cpp
  audio/effects/audio_effect_limiter.cpp
  audio/effects/audio_effect_panner.cpp
  audio/effects/audio_effect_phaser.cpp
  audio/effects/audio_effect_pitch_shift.cpp
  audio/effects/audio_effect_record.cpp
  audio/effects/audio_effect_reverb.cpp
  audio/effects/audio_effect_spectrum_analyzer.cpp
  audio/effects/audio_effect_stereo_enhance.cpp
  audio/effects/audio_stream_generator.cpp
  audio/effects/eq_filter.cpp
  audio/effects/reverb_filter.cpp
  camera_server.cpp
  camera/camera_feed.cpp
  debugger/servers_debugger.cpp
  display_server.cpp
  display/native_menu.cpp
  extensions/physics_server_2d_extension.cpp
  extensions/physics_server_3d_extension.cpp
  movie_writer/movie_writer_mjpeg.cpp
  movie_writer/movie_writer_pngwav.cpp
  movie_writer/movie_writer.cpp
  navigation_server_2d.cpp
  navigation_server_3d.cpp
  navigation/navigation_path_query_parameters_2d.cpp
  navigation/navigation_path_query_parameters_3d.cpp
  navigation/navigation_path_query_result_2d.cpp
  navigation/navigation_path_query_result_3d.cpp
  physics_server_2d_wrap_mt.cpp
  physics_server_2d.cpp
  physics_server_3d_wrap_mt.cpp
  physics_server_3d.cpp
  register_server_types.cpp
  rendering_server.cpp
  rendering/dummy/storage/light_storage.cpp
  rendering/dummy/storage/material_storage.cpp
  rendering/dummy/storage/mesh_storage.cpp
  rendering/dummy/storage/texture_storage.cpp
  rendering/dummy/storage/utilities.cpp
  rendering/instance_uniforms.cpp
  rendering/renderer_canvas_cull.cpp
  rendering/renderer_canvas_render.cpp
  rendering/renderer_compositor.cpp
  rendering/renderer_geometry_instance.cpp
  rendering/renderer_rd/cluster_builder_rd.cpp
  rendering/renderer_rd/effects/bokeh_dof.cpp
  rendering/renderer_rd/effects/copy_effects.cpp
  rendering/renderer_rd/effects/debug_effects.cpp
  rendering/renderer_rd/effects/fsr.cpp
  rendering/renderer_rd/effects/fsr2.cpp
  rendering/renderer_rd/effects/luminance.cpp
  rendering/renderer_rd/effects/metal_fx.mm
  rendering/renderer_rd/effects/motion_vectors_store.cpp
  rendering/renderer_rd/effects/resolve.cpp
  rendering/renderer_rd/effects/roughness_limiter.cpp
  rendering/renderer_rd/effects/sort_effects.cpp
  rendering/renderer_rd/effects/ss_effects.cpp
  rendering/renderer_rd/effects/taa.cpp
  rendering/renderer_rd/effects/tone_mapper.cpp
  rendering/renderer_rd/effects/vrs.cpp
  rendering/renderer_rd/environment/fog.cpp
  rendering/renderer_rd/environment/gi.cpp
  rendering/renderer_rd/environment/sky.cpp
  rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
  rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp
  rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp
  rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp
  rendering/renderer_rd/framebuffer_cache_rd.cpp
  rendering/renderer_rd/pipeline_cache_rd.cpp
  rendering/renderer_rd/renderer_canvas_render_rd.cpp
  rendering/renderer_rd/renderer_compositor_rd.cpp
  rendering/renderer_rd/renderer_scene_render_rd.cpp
  rendering/renderer_rd/shader_rd.cpp
  rendering/renderer_rd/storage_rd/forward_id_storage.cpp
  rendering/renderer_rd/storage_rd/light_storage.cpp
  rendering/renderer_rd/storage_rd/material_storage.cpp
  rendering/renderer_rd/storage_rd/mesh_storage.cpp
  rendering/renderer_rd/storage_rd/particles_storage.cpp
  rendering/renderer_rd/storage_rd/render_data_rd.cpp
  rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp
  rendering/renderer_rd/storage_rd/render_scene_data_rd.cpp
  rendering/renderer_rd/storage_rd/texture_storage.cpp
  rendering/renderer_rd/storage_rd/utilities.cpp
  rendering/renderer_rd/uniform_set_cache_rd.cpp
  rendering/renderer_scene_cull.cpp
  rendering/renderer_scene_occlusion_cull.cpp
  rendering/renderer_scene_render.cpp
  rendering/renderer_viewport.cpp
  rendering/rendering_context_driver.cpp
  rendering/rendering_device_binds.cpp
  rendering/rendering_device_commons.cpp
  rendering/rendering_device_driver.cpp
  rendering/rendering_device_graph.cpp
  rendering/rendering_device.cpp
  rendering/rendering_light_culler.cpp
  rendering/rendering_method.cpp
  rendering/rendering_server_default.cpp
  rendering/rendering_server_globals.cpp
  rendering/shader_compiler.cpp
  rendering/shader_include_db.cpp
  rendering/shader_language.cpp
  rendering/shader_preprocessor.cpp
  rendering/shader_types.cpp
  rendering/shader_warnings.cpp
  rendering/storage/camera_attributes_storage.cpp
  rendering/storage/compositor_storage.cpp
  rendering/storage/environment_storage.cpp
  rendering/storage/mesh_storage.cpp
  rendering/storage/render_data.cpp
  rendering/storage/render_scene_buffers.cpp
  rendering/storage/render_scene_data.cpp
  rendering/storage/utilities.cpp
  text_server.cpp
  text/text_server_extension.cpp
  xr_server.cpp
  xr/xr_body_tracker.cpp
  xr/xr_controller_tracker.cpp
  xr/xr_face_tracker.cpp
  xr/xr_hand_tracker.cpp
  xr/xr_interface_extension.cpp
  xr/xr_interface.cpp
  xr/xr_pose.cpp
  xr/xr_positional_tracker.cpp
  xr/xr_tracker.cpp
  xr/xr_vrs.cpp
)

# GODOT_SERVERS_HEADERS - Header files for servers
set(GODOT_SERVERS_HEADERS
  audio_server.h
  audio/audio_driver_dummy.h
  audio/audio_effect.h
  audio/audio_filter_sw.h
  audio/audio_rb_resampler.h
  audio/audio_stream.h
  audio/effects/audio_effect_amplify.h
  audio/effects/audio_effect_capture.h
  audio/effects/audio_effect_chorus.h
  audio/effects/audio_effect_compressor.h
  audio/effects/audio_effect_delay.h
  audio/effects/audio_effect_distortion.h
  audio/effects/audio_effect_eq.h
  audio/effects/audio_effect_filter.h
  audio/effects/audio_effect_hard_limiter.h
  audio/effects/audio_effect_limiter.h
  audio/effects/audio_effect_panner.h
  audio/effects/audio_effect_phaser.h
  audio/effects/audio_effect_pitch_shift.h
  audio/effects/audio_effect_record.h
  audio/effects/audio_effect_reverb.h
  audio/effects/audio_effect_spectrum_analyzer.h
  audio/effects/audio_effect_stereo_enhance.h
  audio/effects/audio_stream_generator.h
  audio/effects/eq_filter.h
  audio/effects/reverb_filter.h
  camera_server.h
  camera/camera_feed.h
  debugger/servers_debugger.h
  display_server_headless.h
  display_server.h
  display/native_menu.h
  extensions/physics_server_2d_extension.h
  extensions/physics_server_3d_extension.h
  movie_writer/movie_writer_mjpeg.h
  movie_writer/movie_writer_pngwav.h
  movie_writer/movie_writer.h
  navigation_server_2d_dummy.h
  navigation_server_2d.h
  navigation_server_3d_dummy.h
  navigation_server_3d.h
  navigation/nav_heap.h
  navigation/navigation_globals.h
  navigation/navigation_path_query_parameters_2d.h
  navigation/navigation_path_query_parameters_3d.h
  navigation/navigation_path_query_result_2d.h
  navigation/navigation_path_query_result_3d.h
  navigation/navigation_utilities.h
  physics_server_2d_dummy.h
  physics_server_2d_wrap_mt.h
  physics_server_2d.h
  physics_server_3d_dummy.h
  physics_server_3d_wrap_mt.h
  physics_server_3d.h
  register_server_types.h
  rendering_server.h
  rendering/dummy/environment/fog.h
  rendering/dummy/environment/gi.h
  rendering/dummy/rasterizer_canvas_dummy.h
  rendering/dummy/rasterizer_dummy.h
  rendering/dummy/rasterizer_scene_dummy.h
  rendering/dummy/storage/light_storage.h
  rendering/dummy/storage/material_storage.h
  rendering/dummy/storage/mesh_storage.h
  rendering/dummy/storage/particles_storage.h
  rendering/dummy/storage/texture_storage.h
  rendering/dummy/storage/utilities.h
  rendering/environment/renderer_fog.h
  rendering/environment/renderer_gi.h
  rendering/instance_uniforms.h
  rendering/renderer_canvas_cull.h
  rendering/renderer_canvas_render.h
  rendering/renderer_compositor.h
  rendering/renderer_geometry_instance.h
  rendering/renderer_rd/cluster_builder_rd.h
  rendering/renderer_rd/effects/bokeh_dof.h
  rendering/renderer_rd/effects/copy_effects.h
  rendering/renderer_rd/effects/debug_effects.h
  rendering/renderer_rd/effects/fsr.h
  rendering/renderer_rd/effects/fsr2.h
  rendering/renderer_rd/effects/luminance.h
  rendering/renderer_rd/effects/metal_fx.h
  rendering/renderer_rd/effects/motion_vectors_store.h
  rendering/renderer_rd/effects/resolve.h
  rendering/renderer_rd/effects/roughness_limiter.h
  rendering/renderer_rd/effects/sort_effects.h
  rendering/renderer_rd/effects/spatial_upscaler.h
  rendering/renderer_rd/effects/ss_effects.h
  rendering/renderer_rd/effects/taa.h
  rendering/renderer_rd/effects/tone_mapper.h
  rendering/renderer_rd/effects/vrs.h
  rendering/renderer_rd/environment/fog.h
  rendering/renderer_rd/environment/gi.h
  rendering/renderer_rd/environment/sky.h
  rendering/renderer_rd/forward_clustered/render_forward_clustered.h
  rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.h
  rendering/renderer_rd/forward_mobile/render_forward_mobile.h
  rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.h
  rendering/renderer_rd/framebuffer_cache_rd.h
  rendering/renderer_rd/pipeline_cache_rd.h
  rendering/renderer_rd/pipeline_hash_map_rd.h
  rendering/renderer_rd/renderer_canvas_render_rd.h
  rendering/renderer_rd/renderer_compositor_rd.h
  rendering/renderer_rd/renderer_scene_render_rd.h
  rendering/renderer_rd/shader_rd.h
  rendering/renderer_rd/storage_rd/forward_id_storage.h
  rendering/renderer_rd/storage_rd/light_storage.h
  rendering/renderer_rd/storage_rd/material_storage.h
  rendering/renderer_rd/storage_rd/mesh_storage.h
  rendering/renderer_rd/storage_rd/particles_storage.h
  rendering/renderer_rd/storage_rd/render_buffer_custom_data_rd.h
  rendering/renderer_rd/storage_rd/render_data_rd.h
  rendering/renderer_rd/storage_rd/render_scene_buffers_rd.h
  rendering/renderer_rd/storage_rd/render_scene_data_rd.h
  rendering/renderer_rd/storage_rd/texture_storage.h
  rendering/renderer_rd/storage_rd/utilities.h
  rendering/renderer_rd/uniform_set_cache_rd.h
  rendering/renderer_scene_cull.h
  rendering/renderer_scene_occlusion_cull.h
  rendering/renderer_scene_render.h
  rendering/renderer_viewport.h
  rendering/rendering_context_driver.h
  rendering/rendering_device_binds.h
  rendering/rendering_device_commons.h
  rendering/rendering_device_driver.h
  rendering/rendering_device_graph.h
  rendering/rendering_device.h
  rendering/rendering_light_culler.h
  rendering/rendering_method.h
  rendering/rendering_server_constants.h
  rendering/rendering_server_default.h
  rendering/rendering_server_globals.h
  rendering/shader_compiler.h
  rendering/shader_include_db.h
  rendering/shader_language.h
  rendering/shader_preprocessor.h
  rendering/shader_types.h
  rendering/shader_warnings.h
  rendering/storage/camera_attributes_storage.h
  rendering/storage/compositor_storage.h
  rendering/storage/environment_storage.h
  rendering/storage/light_storage.h
  rendering/storage/material_storage.h
  rendering/storage/mesh_storage.h
  rendering/storage/particles_storage.h
  rendering/storage/render_data.h
  rendering/storage/render_scene_buffers.h
  rendering/storage/render_scene_data.h
  rendering/storage/texture_storage.h
  rendering/storage/utilities.h
  rendering/storage/variant_converters.h
  server_wrap_mt_common.h
  text_server.h
  text/text_server_dummy.h
  text/text_server_extension.h
  xr_server.h
  xr/xr_body_tracker.h
  xr/xr_controller_tracker.h
  xr/xr_face_tracker.h
  xr/xr_hand_tracker.h
  xr/xr_interface_extension.h
  xr/xr_interface.h
  xr/xr_pose.h
  xr/xr_positional_tracker.h
  xr/xr_tracker.h
  xr/xr_vrs.h
)

# GODOT_SERVERS_FILES - All files for servers
set(GODOT_SERVERS_FILES
  ${GODOT_SERVERS_SOURCES}
  ${GODOT_SERVERS_HEADERS}
)
