# Generated source list for thirdparty/mbedtls (component-relative paths)
# GODOT_THIRDPARTY_MBEDTLS_SOURCES - Source files for thirdparty/mbedtls
set(GODOT_THIRDPARTY_MBEDTLS_SOURCES
  mbedtls/library/aes.c
  mbedtls/library/aesce.c
  mbedtls/library/aesni.c
  mbedtls/library/aria.c
  mbedtls/library/asn1parse.c
  mbedtls/library/asn1write.c
  mbedtls/library/base64.c
  mbedtls/library/bignum_core.c
  mbedtls/library/bignum_mod_raw.c
  mbedtls/library/bignum.c
  mbedtls/library/camellia.c
  mbedtls/library/ccm.c
  mbedtls/library/chacha20.c
  mbedtls/library/chachapoly.c
  mbedtls/library/cipher_wrap.c
  mbedtls/library/cipher.c
  mbedtls/library/cmac.c
  mbedtls/library/constant_time.c
  mbedtls/library/ctr_drbg.c
  mbedtls/library/debug.c
  mbedtls/library/des.c
  mbedtls/library/dhm.c
  mbedtls/library/ecdh.c
  mbedtls/library/ecdsa.c
  mbedtls/library/ecjpake.c
  mbedtls/library/ecp_curves.c
  mbedtls/library/ecp.c
  mbedtls/library/entropy_poll.c
  mbedtls/library/entropy.c
  mbedtls/library/error.c
  mbedtls/library/gcm.c
  mbedtls/library/godot_core_mbedtls_platform.c
  mbedtls/library/hkdf.c
  mbedtls/library/hmac_drbg.c
  mbedtls/library/md.c
  mbedtls/library/md5.c
  mbedtls/library/memory_buffer_alloc.c
  mbedtls/library/mps_reader.c
  mbedtls/library/mps_trace.c
  mbedtls/library/net_sockets.c
  mbedtls/library/nist_kw.c
  mbedtls/library/oid.c
  mbedtls/library/padlock.c
  mbedtls/library/pem.c
  mbedtls/library/pk_ecc.c
  mbedtls/library/pk_wrap.c
  mbedtls/library/pk.c
  mbedtls/library/pkcs12.c
  mbedtls/library/pkcs5.c
  mbedtls/library/pkcs7.c
  mbedtls/library/pkparse.c
  mbedtls/library/pkwrite.c
  mbedtls/library/platform_util.c
  mbedtls/library/platform.c
  mbedtls/library/poly1305.c
  mbedtls/library/psa_crypto_aead.c
  mbedtls/library/psa_crypto_cipher.c
  mbedtls/library/psa_crypto_client.c
  mbedtls/library/psa_crypto_driver_wrappers_no_static.c
  mbedtls/library/psa_crypto_ecp.c
  mbedtls/library/psa_crypto_ffdh.c
  mbedtls/library/psa_crypto_hash.c
  mbedtls/library/psa_crypto_mac.c
  mbedtls/library/psa_crypto_pake.c
  mbedtls/library/psa_crypto_rsa.c
  mbedtls/library/psa_crypto_se.c
  mbedtls/library/psa_crypto_slot_management.c
  mbedtls/library/psa_crypto_storage.c
  mbedtls/library/psa_crypto.c
  mbedtls/library/psa_its_file.c
  mbedtls/library/psa_util.c
  mbedtls/library/ripemd160.c
  mbedtls/library/rsa_alt_helpers.c
  mbedtls/library/rsa.c
  mbedtls/library/sha1.c
  mbedtls/library/sha256.c
  mbedtls/library/sha3.c
  mbedtls/library/sha512.c
  mbedtls/library/ssl_cache.c
  mbedtls/library/ssl_ciphersuites.c
  mbedtls/library/ssl_client.c
  mbedtls/library/ssl_cookie.c
  mbedtls/library/ssl_debug_helpers_generated.c
  mbedtls/library/ssl_msg.c
  mbedtls/library/ssl_ticket.c
  mbedtls/library/ssl_tls.c
  mbedtls/library/ssl_tls12_client.c
  mbedtls/library/ssl_tls12_server.c
  mbedtls/library/ssl_tls13_client.c
  mbedtls/library/ssl_tls13_generic.c
  mbedtls/library/ssl_tls13_keys.c
  mbedtls/library/ssl_tls13_server.c
  mbedtls/library/threading.c
  mbedtls/library/timing.c
  mbedtls/library/version_features.c
  mbedtls/library/version.c
  mbedtls/library/x509_create.c
  mbedtls/library/x509_crl.c
  mbedtls/library/x509_crt.c
  mbedtls/library/x509_csr.c
  mbedtls/library/x509.c
  mbedtls/library/x509write_crt.c
  mbedtls/library/x509write_csr.c
  mbedtls/library/x509write.c
)

# GODOT_THIRDPARTY_MBEDTLS_HEADERS - Header files for thirdparty/mbedtls
set(GODOT_THIRDPARTY_MBEDTLS_HEADERS
  mbedtls/include/godot_core_mbedtls_config.h
  mbedtls/include/godot_module_mbedtls_config.h
  mbedtls/include/mbedtls/aes.h
  mbedtls/include/mbedtls/aria.h
  mbedtls/include/mbedtls/asn1.h
  mbedtls/include/mbedtls/asn1write.h
  mbedtls/include/mbedtls/base64.h
  mbedtls/include/mbedtls/bignum.h
  mbedtls/include/mbedtls/block_cipher.h
  mbedtls/include/mbedtls/build_info.h
  mbedtls/include/mbedtls/camellia.h
  mbedtls/include/mbedtls/ccm.h
  mbedtls/include/mbedtls/chacha20.h
  mbedtls/include/mbedtls/chachapoly.h
  mbedtls/include/mbedtls/check_config.h
  mbedtls/include/mbedtls/cipher.h
  mbedtls/include/mbedtls/cmac.h
  mbedtls/include/mbedtls/compat-2.x.h
  mbedtls/include/mbedtls/config_adjust_legacy_crypto.h
  mbedtls/include/mbedtls/config_adjust_legacy_from_psa.h
  mbedtls/include/mbedtls/config_adjust_psa_from_legacy.h
  mbedtls/include/mbedtls/config_adjust_psa_superset_legacy.h
  mbedtls/include/mbedtls/config_adjust_ssl.h
  mbedtls/include/mbedtls/config_adjust_x509.h
  mbedtls/include/mbedtls/config_psa.h
  mbedtls/include/mbedtls/constant_time.h
  mbedtls/include/mbedtls/ctr_drbg.h
  mbedtls/include/mbedtls/debug.h
  mbedtls/include/mbedtls/des.h
  mbedtls/include/mbedtls/dhm.h
  mbedtls/include/mbedtls/ecdh.h
  mbedtls/include/mbedtls/ecdsa.h
  mbedtls/include/mbedtls/ecjpake.h
  mbedtls/include/mbedtls/ecp.h
  mbedtls/include/mbedtls/entropy.h
  mbedtls/include/mbedtls/error.h
  mbedtls/include/mbedtls/gcm.h
  mbedtls/include/mbedtls/hkdf.h
  mbedtls/include/mbedtls/hmac_drbg.h
  mbedtls/include/mbedtls/lms.h
  mbedtls/include/mbedtls/mbedtls_config.h
  mbedtls/include/mbedtls/md.h
  mbedtls/include/mbedtls/md5.h
  mbedtls/include/mbedtls/memory_buffer_alloc.h
  mbedtls/include/mbedtls/net_sockets.h
  mbedtls/include/mbedtls/nist_kw.h
  mbedtls/include/mbedtls/oid.h
  mbedtls/include/mbedtls/pem.h
  mbedtls/include/mbedtls/pk.h
  mbedtls/include/mbedtls/pkcs12.h
  mbedtls/include/mbedtls/pkcs5.h
  mbedtls/include/mbedtls/pkcs7.h
  mbedtls/include/mbedtls/platform_time.h
  mbedtls/include/mbedtls/platform_util.h
  mbedtls/include/mbedtls/platform.h
  mbedtls/include/mbedtls/poly1305.h
  mbedtls/include/mbedtls/private_access.h
  mbedtls/include/mbedtls/psa_util.h
  mbedtls/include/mbedtls/ripemd160.h
  mbedtls/include/mbedtls/rsa.h
  mbedtls/include/mbedtls/sha1.h
  mbedtls/include/mbedtls/sha256.h
  mbedtls/include/mbedtls/sha3.h
  mbedtls/include/mbedtls/sha512.h
  mbedtls/include/mbedtls/ssl_cache.h
  mbedtls/include/mbedtls/ssl_ciphersuites.h
  mbedtls/include/mbedtls/ssl_cookie.h
  mbedtls/include/mbedtls/ssl_ticket.h
  mbedtls/include/mbedtls/ssl.h
  mbedtls/include/mbedtls/threading.h
  mbedtls/include/mbedtls/timing.h
  mbedtls/include/mbedtls/version.h
  mbedtls/include/mbedtls/x509_crl.h
  mbedtls/include/mbedtls/x509_crt.h
  mbedtls/include/mbedtls/x509_csr.h
  mbedtls/include/mbedtls/x509.h
  mbedtls/include/psa/build_info.h
  mbedtls/include/psa/crypto_adjust_auto_enabled.h
  mbedtls/include/psa/crypto_adjust_config_dependencies.h
  mbedtls/include/psa/crypto_adjust_config_key_pair_types.h
  mbedtls/include/psa/crypto_adjust_config_synonyms.h
  mbedtls/include/psa/crypto_builtin_composites.h
  mbedtls/include/psa/crypto_builtin_key_derivation.h
  mbedtls/include/psa/crypto_builtin_primitives.h
  mbedtls/include/psa/crypto_compat.h
  mbedtls/include/psa/crypto_config.h
  mbedtls/include/psa/crypto_driver_common.h
  mbedtls/include/psa/crypto_driver_contexts_composites.h
  mbedtls/include/psa/crypto_driver_contexts_key_derivation.h
  mbedtls/include/psa/crypto_driver_contexts_primitives.h
  mbedtls/include/psa/crypto_extra.h
  mbedtls/include/psa/crypto_legacy.h
  mbedtls/include/psa/crypto_platform.h
  mbedtls/include/psa/crypto_se_driver.h
  mbedtls/include/psa/crypto_sizes.h
  mbedtls/include/psa/crypto_struct.h
  mbedtls/include/psa/crypto_types.h
  mbedtls/include/psa/crypto_values.h
  mbedtls/include/psa/crypto.h
  mbedtls/include/threading_alt.h
  mbedtls/library/aesce.h
  mbedtls/library/aesni.h
  mbedtls/library/alignment.h
  mbedtls/library/base64_internal.h
  mbedtls/library/bignum_core.h
  mbedtls/library/bignum_internal.h
  mbedtls/library/bignum_mod_raw_invasive.h
  mbedtls/library/bignum_mod_raw.h
  mbedtls/library/bignum_mod.h
  mbedtls/library/block_cipher_internal.h
  mbedtls/library/bn_mul.h
  mbedtls/library/check_crypto_config.h
  mbedtls/library/cipher_wrap.h
  mbedtls/library/common.h
  mbedtls/library/constant_time_impl.h
  mbedtls/library/constant_time_internal.h
  mbedtls/library/ctr.h
  mbedtls/library/debug_internal.h
  mbedtls/library/ecp_internal_alt.h
  mbedtls/library/ecp_invasive.h
  mbedtls/library/entropy_poll.h
  mbedtls/library/lmots.h
  mbedtls/library/md_psa.h
  mbedtls/library/md_wrap.h
  mbedtls/library/mps_common.h
  mbedtls/library/mps_error.h
  mbedtls/library/mps_reader.h
  mbedtls/library/mps_trace.h
  mbedtls/library/padlock.h
  mbedtls/library/pk_internal.h
  mbedtls/library/pk_wrap.h
  mbedtls/library/pkwrite.h
  mbedtls/library/psa_crypto_aead.h
  mbedtls/library/psa_crypto_cipher.h
  mbedtls/library/psa_crypto_core_common.h
  mbedtls/library/psa_crypto_core.h
  mbedtls/library/psa_crypto_driver_wrappers_no_static.h
  mbedtls/library/psa_crypto_driver_wrappers.h
  mbedtls/library/psa_crypto_ecp.h
  mbedtls/library/psa_crypto_ffdh.h
  mbedtls/library/psa_crypto_hash.h
  mbedtls/library/psa_crypto_invasive.h
  mbedtls/library/psa_crypto_its.h
  mbedtls/library/psa_crypto_mac.h
  mbedtls/library/psa_crypto_pake.h
  mbedtls/library/psa_crypto_random_impl.h
  mbedtls/library/psa_crypto_rsa.h
  mbedtls/library/psa_crypto_se.h
  mbedtls/library/psa_crypto_slot_management.h
  mbedtls/library/psa_crypto_storage.h
  mbedtls/library/psa_util_internal.h
  mbedtls/library/rsa_alt_helpers.h
  mbedtls/library/rsa_internal.h
  mbedtls/library/ssl_ciphersuites_internal.h
  mbedtls/library/ssl_client.h
  mbedtls/library/ssl_debug_helpers.h
  mbedtls/library/ssl_misc.h
  mbedtls/library/ssl_tls13_invasive.h
  mbedtls/library/ssl_tls13_keys.h
  mbedtls/library/x509_internal.h
)

# GODOT_THIRDPARTY_MBEDTLS_FILES - All files for thirdparty/mbedtls
set(GODOT_THIRDPARTY_MBEDTLS_FILES
  ${GODOT_THIRDPARTY_MBEDTLS_SOURCES}
  ${GODOT_THIRDPARTY_MBEDTLS_HEADERS}
)
