# Generated source list for editor (component-relative paths)
# GODOT_EDITOR_SOURCES - Source files for editor
set(GODOT_EDITOR_SOURCES
  action_map_editor.cpp
  add_metadata_dialog.cpp
  animation_bezier_editor.cpp
  animation_track_editor_plugins.cpp
  animation_track_editor.cpp
  audio_stream_preview.cpp
  code_editor.cpp
  connections_dialog.cpp
  create_dialog.cpp
  credits_roll.cpp
  debugger/debug_adapter/debug_adapter_parser.cpp
  debugger/debug_adapter/debug_adapter_protocol.cpp
  debugger/debug_adapter/debug_adapter_server.cpp
  debugger/editor_debugger_inspector.cpp
  debugger/editor_debugger_node.cpp
  debugger/editor_debugger_server.cpp
  debugger/editor_debugger_tree.cpp
  debugger/editor_expression_evaluator.cpp
  debugger/editor_file_server.cpp
  debugger/editor_performance_profiler.cpp
  debugger/editor_profiler.cpp
  debugger/editor_visual_profiler.cpp
  debugger/script_editor_debugger.cpp
  dependency_editor.cpp
  directory_create_dialog.cpp
  doc_tools.cpp
  editor_about.cpp
  editor_asset_installer.cpp
  editor_atlas_packer.cpp
  editor_audio_buses.cpp
  editor_autoload_settings.cpp
  editor_build_profile.cpp
  editor_command_palette.cpp
  editor_data.cpp
  editor_dock_manager.cpp
  editor_feature_profile.cpp
  editor_file_system.cpp
  editor_folding.cpp
  editor_help_search.cpp
  editor_help.cpp
  editor_inspector.cpp
  editor_interface.cpp
  editor_layouts_dialog.cpp
  editor_locale_dialog.cpp
  editor_log.cpp
  editor_main_screen.cpp
  editor_native_shader_source_visualizer.cpp
  editor_node.cpp
  editor_paths.cpp
  editor_properties_array_dict.cpp
  editor_properties_vector.cpp
  editor_properties.cpp
  editor_property_name_processor.cpp
  editor_resource_picker.cpp
  editor_resource_preview.cpp
  editor_run_native.cpp
  editor_run.cpp
  editor_script.cpp
  editor_sectioned_inspector.cpp
  editor_settings_dialog.cpp
  editor_settings.cpp
  editor_translation_parser.cpp
  editor_translation.cpp
  editor_undo_redo_manager.cpp
  editor_vcs_interface.cpp
  engine_update_label.cpp
  event_listener_line_edit.cpp
  export/codesign.cpp
  export/editor_export_platform_extension.cpp
  export/editor_export_platform_pc.cpp
  export/editor_export_platform.cpp
  export/editor_export_plugin.cpp
  export/editor_export_preset.cpp
  export/editor_export.cpp
  export/export_template_manager.cpp
  export/lipo.cpp
  export/macho.cpp
  export/project_export.cpp
  export/project_zip_packer.cpp
  fbx_importer_manager.cpp
  file_info.cpp
  filesystem_dock.cpp
  find_in_files.cpp
  group_settings_editor.cpp
  groups_editor.cpp
  gui/editor_bottom_panel.cpp
  gui/editor_dir_dialog.cpp
  gui/editor_file_dialog.cpp
  gui/editor_object_selector.cpp
  gui/editor_quick_open_dialog.cpp
  gui/editor_run_bar.cpp
  gui/editor_scene_tabs.cpp
  gui/editor_spin_slider.cpp
  gui/editor_title_bar.cpp
  gui/editor_toaster.cpp
  gui/editor_validation_panel.cpp
  gui/editor_version_button.cpp
  gui/editor_zoom_widget.cpp
  gui/scene_tree_editor.cpp
  gui/touch_actions_panel.cpp
  history_dock.cpp
  import_defaults_editor.cpp
  import_dock.cpp
  import/3d/collada.cpp
  import/3d/editor_import_collada.cpp
  import/3d/post_import_plugin_skeleton_renamer.cpp
  import/3d/post_import_plugin_skeleton_rest_fixer.cpp
  import/3d/post_import_plugin_skeleton_track_organizer.cpp
  import/3d/resource_importer_obj.cpp
  import/3d/resource_importer_scene.cpp
  import/3d/scene_import_settings.cpp
  import/audio_stream_import_settings.cpp
  import/dynamic_font_import_settings.cpp
  import/editor_import_plugin.cpp
  import/resource_importer_bitmask.cpp
  import/resource_importer_bmfont.cpp
  import/resource_importer_csv_translation.cpp
  import/resource_importer_dynamic_font.cpp
  import/resource_importer_image.cpp
  import/resource_importer_imagefont.cpp
  import/resource_importer_layered_texture.cpp
  import/resource_importer_shader_file.cpp
  import/resource_importer_svg.cpp
  import/resource_importer_texture_atlas.cpp
  import/resource_importer_texture_settings.cpp
  import/resource_importer_texture.cpp
  import/resource_importer_wav.cpp
  input_event_configuration_dialog.cpp
  inspector_dock.cpp
  localization_editor.cpp
  multi_node_edit.cpp
  node_dock.cpp
  plugins/abstract_polygon_2d_editor.cpp
  plugins/animation_blend_space_1d_editor.cpp
  plugins/animation_blend_space_2d_editor.cpp
  plugins/animation_blend_tree_editor_plugin.cpp
  plugins/animation_library_editor.cpp
  plugins/animation_player_editor_plugin.cpp
  plugins/animation_state_machine_editor.cpp
  plugins/animation_tree_editor_plugin.cpp
  plugins/asset_library_editor_plugin.cpp
  plugins/audio_stream_editor_plugin.cpp
  plugins/audio_stream_randomizer_editor_plugin.cpp
  plugins/bit_map_editor_plugin.cpp
  plugins/bone_map_editor_plugin.cpp
  plugins/camera_2d_editor_plugin.cpp
  plugins/camera_3d_editor_plugin.cpp
  plugins/canvas_item_editor_plugin.cpp
  plugins/cast_2d_editor_plugin.cpp
  plugins/collision_polygon_2d_editor_plugin.cpp
  plugins/collision_shape_2d_editor_plugin.cpp
  plugins/color_channel_selector.cpp
  plugins/control_editor_plugin.cpp
  plugins/curve_editor_plugin.cpp
  plugins/debugger_editor_plugin.cpp
  plugins/dedicated_server_export_plugin.cpp
  plugins/editor_context_menu_plugin.cpp
  plugins/editor_debugger_plugin.cpp
  plugins/editor_plugin_settings.cpp
  plugins/editor_plugin.cpp
  plugins/editor_preview_plugins.cpp
  plugins/editor_resource_conversion_plugin.cpp
  plugins/editor_resource_tooltip_plugins.cpp
  plugins/embedded_process.cpp
  plugins/font_config_plugin.cpp
  plugins/game_view_plugin.cpp
  plugins/gizmos/audio_listener_3d_gizmo_plugin.cpp
  plugins/gizmos/audio_stream_player_3d_gizmo_plugin.cpp
  plugins/gizmos/camera_3d_gizmo_plugin.cpp
  plugins/gizmos/collision_object_3d_gizmo_plugin.cpp
  plugins/gizmos/collision_polygon_3d_gizmo_plugin.cpp
  plugins/gizmos/collision_shape_3d_gizmo_plugin.cpp
  plugins/gizmos/cpu_particles_3d_gizmo_plugin.cpp
  plugins/gizmos/decal_gizmo_plugin.cpp
  plugins/gizmos/fog_volume_gizmo_plugin.cpp
  plugins/gizmos/geometry_instance_3d_gizmo_plugin.cpp
  plugins/gizmos/gizmo_3d_helper.cpp
  plugins/gizmos/gpu_particles_3d_gizmo_plugin.cpp
  plugins/gizmos/gpu_particles_collision_3d_gizmo_plugin.cpp
  plugins/gizmos/joint_3d_gizmo_plugin.cpp
  plugins/gizmos/label_3d_gizmo_plugin.cpp
  plugins/gizmos/light_3d_gizmo_plugin.cpp
  plugins/gizmos/lightmap_gi_gizmo_plugin.cpp
  plugins/gizmos/lightmap_probe_gizmo_plugin.cpp
  plugins/gizmos/marker_3d_gizmo_plugin.cpp
  plugins/gizmos/mesh_instance_3d_gizmo_plugin.cpp
  plugins/gizmos/occluder_instance_3d_gizmo_plugin.cpp
  plugins/gizmos/particles_3d_emission_shape_gizmo_plugin.cpp
  plugins/gizmos/physics_bone_3d_gizmo_plugin.cpp
  plugins/gizmos/ray_cast_3d_gizmo_plugin.cpp
  plugins/gizmos/reflection_probe_gizmo_plugin.cpp
  plugins/gizmos/shape_cast_3d_gizmo_plugin.cpp
  plugins/gizmos/soft_body_3d_gizmo_plugin.cpp
  plugins/gizmos/spring_arm_3d_gizmo_plugin.cpp
  plugins/gizmos/spring_bone_3d_gizmo_plugin.cpp
  plugins/gizmos/sprite_base_3d_gizmo_plugin.cpp
  plugins/gizmos/vehicle_body_3d_gizmo_plugin.cpp
  plugins/gizmos/visible_on_screen_notifier_3d_gizmo_plugin.cpp
  plugins/gizmos/voxel_gi_gizmo_plugin.cpp
  plugins/gpu_particles_collision_sdf_editor_plugin.cpp
  plugins/gradient_editor_plugin.cpp
  plugins/gradient_texture_2d_editor_plugin.cpp
  plugins/input_event_editor_plugin.cpp
  plugins/light_occluder_2d_editor_plugin.cpp
  plugins/lightmap_gi_editor_plugin.cpp
  plugins/line_2d_editor_plugin.cpp
  plugins/material_editor_plugin.cpp
  plugins/mesh_editor_plugin.cpp
  plugins/mesh_instance_3d_editor_plugin.cpp
  plugins/mesh_library_editor_plugin.cpp
  plugins/multimesh_editor_plugin.cpp
  plugins/node_3d_editor_gizmos.cpp
  plugins/node_3d_editor_plugin.cpp
  plugins/occluder_instance_3d_editor_plugin.cpp
  plugins/packed_scene_editor_plugin.cpp
  plugins/packed_scene_translation_parser_plugin.cpp
  plugins/parallax_background_editor_plugin.cpp
  plugins/particle_process_material_editor_plugin.cpp
  plugins/particles_editor_plugin.cpp
  plugins/path_2d_editor_plugin.cpp
  plugins/path_3d_editor_plugin.cpp
  plugins/physical_bone_3d_editor_plugin.cpp
  plugins/plugin_config_dialog.cpp
  plugins/polygon_2d_editor_plugin.cpp
  plugins/polygon_3d_editor_plugin.cpp
  plugins/resource_preloader_editor_plugin.cpp
  plugins/root_motion_editor_plugin.cpp
  plugins/script_editor_plugin.cpp
  plugins/script_text_editor.cpp
  plugins/shader_editor_plugin.cpp
  plugins/shader_file_editor_plugin.cpp
  plugins/skeleton_2d_editor_plugin.cpp
  plugins/skeleton_3d_editor_plugin.cpp
  plugins/skeleton_ik_3d_editor_plugin.cpp
  plugins/sprite_2d_editor_plugin.cpp
  plugins/sprite_frames_editor_plugin.cpp
  plugins/style_box_editor_plugin.cpp
  plugins/sub_viewport_preview_editor_plugin.cpp
  plugins/text_editor.cpp
  plugins/text_shader_editor.cpp
  plugins/texture_3d_editor_plugin.cpp
  plugins/texture_editor_plugin.cpp
  plugins/texture_layered_editor_plugin.cpp
  plugins/texture_region_editor_plugin.cpp
  plugins/theme_editor_plugin.cpp
  plugins/theme_editor_preview.cpp
  plugins/tiles/atlas_merging_dialog.cpp
  plugins/tiles/tile_atlas_view.cpp
  plugins/tiles/tile_data_editors.cpp
  plugins/tiles/tile_map_layer_editor.cpp
  plugins/tiles/tile_proxies_manager_dialog.cpp
  plugins/tiles/tile_set_atlas_source_editor.cpp
  plugins/tiles/tile_set_editor.cpp
  plugins/tiles/tile_set_scenes_collection_source_editor.cpp
  plugins/tiles/tiles_editor_plugin.cpp
  plugins/tool_button_editor_plugin.cpp
  plugins/version_control_editor_plugin.cpp
  plugins/visual_shader_editor_plugin.cpp
  plugins/voxel_gi_editor_plugin.cpp
  pot_generator.cpp
  progress_dialog.cpp
  project_converter_3_to_4.cpp
  project_manager.cpp
  project_manager/project_dialog.cpp
  project_manager/project_list.cpp
  project_manager/project_tag.cpp
  project_manager/quick_settings_dialog.cpp
  project_settings_editor.cpp
  project_upgrade_tool.cpp
  property_selector.cpp
  register_editor_types.cpp
  rename_dialog.cpp
  renames_map_3_to_4.cpp
  reparent_dialog.cpp
  run_instances_dialog.cpp
  scene_create_dialog.cpp
  scene_tree_dock.cpp
  script_create_dialog.cpp
  shader_create_dialog.cpp
  shader_globals_editor.cpp
  themes/editor_color_map.cpp
  themes/editor_fonts.cpp
  themes/editor_icons.cpp
  themes/editor_scale.cpp
  themes/editor_theme_manager.cpp
  themes/editor_theme.cpp
  window_wrapper.cpp
)

# GODOT_EDITOR_HEADERS - Header files for editor
set(GODOT_EDITOR_HEADERS
  action_map_editor.h
  add_metadata_dialog.h
  animation_bezier_editor.h
  animation_track_editor_plugins.h
  animation_track_editor.h
  audio_stream_preview.h
  code_editor.h
  connections_dialog.h
  create_dialog.h
  credits_roll.h
  debugger/debug_adapter/debug_adapter_parser.h
  debugger/debug_adapter/debug_adapter_protocol.h
  debugger/debug_adapter/debug_adapter_server.h
  debugger/debug_adapter/debug_adapter_types.h
  debugger/editor_debugger_inspector.h
  debugger/editor_debugger_node.h
  debugger/editor_debugger_server.h
  debugger/editor_debugger_tree.h
  debugger/editor_expression_evaluator.h
  debugger/editor_file_server.h
  debugger/editor_performance_profiler.h
  debugger/editor_profiler.h
  debugger/editor_visual_profiler.h
  debugger/script_editor_debugger.h
  dependency_editor.h
  directory_create_dialog.h
  doc_tools.h
  editor_about.h
  editor_asset_installer.h
  editor_atlas_packer.h
  editor_audio_buses.h
  editor_autoload_settings.h
  editor_build_profile.h
  editor_command_palette.h
  editor_data.h
  editor_dock_manager.h
  editor_feature_profile.h
  editor_file_system.h
  editor_folding.h
  editor_help_search.h
  editor_help.h
  editor_inspector.h
  editor_interface.h
  editor_layouts_dialog.h
  editor_locale_dialog.h
  editor_log.h
  editor_main_screen.h
  editor_native_shader_source_visualizer.h
  editor_node.h
  editor_paths.h
  editor_properties_array_dict.h
  editor_properties_vector.h
  editor_properties.h
  editor_property_name_processor.h
  editor_resource_picker.h
  editor_resource_preview.h
  editor_run_native.h
  editor_run.h
  editor_script.h
  editor_sectioned_inspector.h
  editor_settings_dialog.h
  editor_settings.h
  editor_string_names.h
  editor_translation_parser.h
  editor_translation.h
  editor_undo_redo_manager.h
  editor_vcs_interface.h
  engine_update_label.h
  event_listener_line_edit.h
  export/codesign.h
  export/editor_export_platform_extension.h
  export/editor_export_platform_pc.h
  export/editor_export_platform.h
  export/editor_export_plugin.h
  export/editor_export_preset.h
  export/editor_export.h
  export/export_template_manager.h
  export/lipo.h
  export/macho.h
  export/project_export.h
  export/project_zip_packer.h
  fbx_importer_manager.h
  file_info.h
  filesystem_dock.h
  find_in_files.h
  group_settings_editor.h
  groups_editor.h
  gui/editor_bottom_panel.h
  gui/editor_dir_dialog.h
  gui/editor_file_dialog.h
  gui/editor_object_selector.h
  gui/editor_quick_open_dialog.h
  gui/editor_run_bar.h
  gui/editor_scene_tabs.h
  gui/editor_spin_slider.h
  gui/editor_title_bar.h
  gui/editor_toaster.h
  gui/editor_validation_panel.h
  gui/editor_version_button.h
  gui/editor_zoom_widget.h
  gui/scene_tree_editor.h
  gui/touch_actions_panel.h
  history_dock.h
  import_defaults_editor.h
  import_dock.h
  import/3d/collada.h
  import/3d/editor_import_collada.h
  import/3d/post_import_plugin_skeleton_renamer.h
  import/3d/post_import_plugin_skeleton_rest_fixer.h
  import/3d/post_import_plugin_skeleton_track_organizer.h
  import/3d/resource_importer_obj.h
  import/3d/resource_importer_scene.h
  import/3d/scene_import_settings.h
  import/audio_stream_import_settings.h
  import/dynamic_font_import_settings.h
  import/editor_import_plugin.h
  import/resource_importer_bitmask.h
  import/resource_importer_bmfont.h
  import/resource_importer_csv_translation.h
  import/resource_importer_dynamic_font.h
  import/resource_importer_image.h
  import/resource_importer_imagefont.h
  import/resource_importer_layered_texture.h
  import/resource_importer_shader_file.h
  import/resource_importer_svg.h
  import/resource_importer_texture_atlas.h
  import/resource_importer_texture_settings.h
  import/resource_importer_texture.h
  import/resource_importer_wav.h
  input_event_configuration_dialog.h
  inspector_dock.h
  localization_editor.h
  multi_node_edit.h
  node_dock.h
  plugins/abstract_polygon_2d_editor.h
  plugins/animation_blend_space_1d_editor.h
  plugins/animation_blend_space_2d_editor.h
  plugins/animation_blend_tree_editor_plugin.h
  plugins/animation_library_editor.h
  plugins/animation_player_editor_plugin.h
  plugins/animation_state_machine_editor.h
  plugins/animation_tree_editor_plugin.h
  plugins/asset_library_editor_plugin.h
  plugins/audio_stream_editor_plugin.h
  plugins/audio_stream_randomizer_editor_plugin.h
  plugins/bit_map_editor_plugin.h
  plugins/bone_map_editor_plugin.h
  plugins/camera_2d_editor_plugin.h
  plugins/camera_3d_editor_plugin.h
  plugins/canvas_item_editor_plugin.h
  plugins/cast_2d_editor_plugin.h
  plugins/collision_polygon_2d_editor_plugin.h
  plugins/collision_shape_2d_editor_plugin.h
  plugins/color_channel_selector.h
  plugins/control_editor_plugin.h
  plugins/curve_editor_plugin.h
  plugins/debugger_editor_plugin.h
  plugins/dedicated_server_export_plugin.h
  plugins/editor_context_menu_plugin.h
  plugins/editor_debugger_plugin.h
  plugins/editor_plugin_settings.h
  plugins/editor_plugin.h
  plugins/editor_preview_plugins.h
  plugins/editor_resource_conversion_plugin.h
  plugins/editor_resource_tooltip_plugins.h
  plugins/embedded_process.h
  plugins/font_config_plugin.h
  plugins/game_view_plugin.h
  plugins/gdextension_export_plugin.h
  plugins/gizmos/audio_listener_3d_gizmo_plugin.h
  plugins/gizmos/audio_stream_player_3d_gizmo_plugin.h
  plugins/gizmos/camera_3d_gizmo_plugin.h
  plugins/gizmos/collision_object_3d_gizmo_plugin.h
  plugins/gizmos/collision_polygon_3d_gizmo_plugin.h
  plugins/gizmos/collision_shape_3d_gizmo_plugin.h
  plugins/gizmos/cpu_particles_3d_gizmo_plugin.h
  plugins/gizmos/decal_gizmo_plugin.h
  plugins/gizmos/fog_volume_gizmo_plugin.h
  plugins/gizmos/geometry_instance_3d_gizmo_plugin.h
  plugins/gizmos/gizmo_3d_helper.h
  plugins/gizmos/gpu_particles_3d_gizmo_plugin.h
  plugins/gizmos/gpu_particles_collision_3d_gizmo_plugin.h
  plugins/gizmos/joint_3d_gizmo_plugin.h
  plugins/gizmos/label_3d_gizmo_plugin.h
  plugins/gizmos/light_3d_gizmo_plugin.h
  plugins/gizmos/lightmap_gi_gizmo_plugin.h
  plugins/gizmos/lightmap_probe_gizmo_plugin.h
  plugins/gizmos/marker_3d_gizmo_plugin.h
  plugins/gizmos/mesh_instance_3d_gizmo_plugin.h
  plugins/gizmos/occluder_instance_3d_gizmo_plugin.h
  plugins/gizmos/particles_3d_emission_shape_gizmo_plugin.h
  plugins/gizmos/physics_bone_3d_gizmo_plugin.h
  plugins/gizmos/ray_cast_3d_gizmo_plugin.h
  plugins/gizmos/reflection_probe_gizmo_plugin.h
  plugins/gizmos/shape_cast_3d_gizmo_plugin.h
  plugins/gizmos/soft_body_3d_gizmo_plugin.h
  plugins/gizmos/spring_arm_3d_gizmo_plugin.h
  plugins/gizmos/spring_bone_3d_gizmo_plugin.h
  plugins/gizmos/sprite_base_3d_gizmo_plugin.h
  plugins/gizmos/vehicle_body_3d_gizmo_plugin.h
  plugins/gizmos/visible_on_screen_notifier_3d_gizmo_plugin.h
  plugins/gizmos/voxel_gi_gizmo_plugin.h
  plugins/gpu_particles_collision_sdf_editor_plugin.h
  plugins/gradient_editor_plugin.h
  plugins/gradient_texture_2d_editor_plugin.h
  plugins/input_event_editor_plugin.h
  plugins/light_occluder_2d_editor_plugin.h
  plugins/lightmap_gi_editor_plugin.h
  plugins/line_2d_editor_plugin.h
  plugins/material_editor_plugin.h
  plugins/mesh_editor_plugin.h
  plugins/mesh_instance_3d_editor_plugin.h
  plugins/mesh_library_editor_plugin.h
  plugins/multimesh_editor_plugin.h
  plugins/node_3d_editor_gizmos.h
  plugins/node_3d_editor_plugin.h
  plugins/occluder_instance_3d_editor_plugin.h
  plugins/packed_scene_editor_plugin.h
  plugins/packed_scene_translation_parser_plugin.h
  plugins/parallax_background_editor_plugin.h
  plugins/particle_process_material_editor_plugin.h
  plugins/particles_editor_plugin.h
  plugins/path_2d_editor_plugin.h
  plugins/path_3d_editor_plugin.h
  plugins/physical_bone_3d_editor_plugin.h
  plugins/plugin_config_dialog.h
  plugins/polygon_2d_editor_plugin.h
  plugins/polygon_3d_editor_plugin.h
  plugins/resource_preloader_editor_plugin.h
  plugins/root_motion_editor_plugin.h
  plugins/script_editor_plugin.h
  plugins/script_text_editor.h
  plugins/shader_editor_plugin.h
  plugins/shader_file_editor_plugin.h
  plugins/shader/shader_editor.h
  plugins/skeleton_2d_editor_plugin.h
  plugins/skeleton_3d_editor_plugin.h
  plugins/skeleton_ik_3d_editor_plugin.h
  plugins/sprite_2d_editor_plugin.h
  plugins/sprite_frames_editor_plugin.h
  plugins/style_box_editor_plugin.h
  plugins/sub_viewport_preview_editor_plugin.h
  plugins/text_editor.h
  plugins/text_shader_editor.h
  plugins/texture_3d_editor_plugin.h
  plugins/texture_editor_plugin.h
  plugins/texture_layered_editor_plugin.h
  plugins/texture_region_editor_plugin.h
  plugins/theme_editor_plugin.h
  plugins/theme_editor_preview.h
  plugins/tiles/atlas_merging_dialog.h
  plugins/tiles/tile_atlas_view.h
  plugins/tiles/tile_data_editors.h
  plugins/tiles/tile_map_layer_editor.h
  plugins/tiles/tile_proxies_manager_dialog.h
  plugins/tiles/tile_set_atlas_source_editor.h
  plugins/tiles/tile_set_editor.h
  plugins/tiles/tile_set_scenes_collection_source_editor.h
  plugins/tiles/tiles_editor_plugin.h
  plugins/tool_button_editor_plugin.h
  plugins/version_control_editor_plugin.h
  plugins/visual_shader_editor_plugin.h
  plugins/voxel_gi_editor_plugin.h
  pot_generator.h
  progress_dialog.h
  project_converter_3_to_4.h
  project_manager.h
  project_manager/project_dialog.h
  project_manager/project_list.h
  project_manager/project_tag.h
  project_manager/quick_settings_dialog.h
  project_settings_editor.h
  project_upgrade_tool.h
  property_selector.h
  register_editor_types.h
  register_exporters.h
  rename_dialog.h
  renames_map_3_to_4.h
  reparent_dialog.h
  run_instances_dialog.h
  scene_create_dialog.h
  scene_tree_dock.h
  script_create_dialog.h
  shader_create_dialog.h
  shader_globals_editor.h
  themes/editor_color_map.h
  themes/editor_fonts.h
  themes/editor_icons.h
  themes/editor_scale.h
  themes/editor_theme_manager.h
  themes/editor_theme.h
  window_wrapper.h
)

# GODOT_EDITOR_FILES - All files for editor
set(GODOT_EDITOR_FILES
  ${GODOT_EDITOR_SOURCES}
  ${GODOT_EDITOR_HEADERS}
)
