# Generated source list for core (component-relative paths)
# GODOT_CORE_SOURCES - Source files for core
set(GODOT_CORE_SOURCES
  config/engine.cpp
  config/project_settings.cpp
  core_bind.cpp
  core_constants.cpp
  crypto/aes_context.cpp
  crypto/crypto_core.cpp
  crypto/crypto.cpp
  crypto/hashing_context.cpp
  debugger/debugger_marshalls.cpp
  debugger/engine_debugger.cpp
  debugger/engine_profiler.cpp
  debugger/local_debugger.cpp
  debugger/remote_debugger_peer.cpp
  debugger/remote_debugger.cpp
  debugger/script_debugger.cpp
  doc_data.cpp
  error/error_list.cpp
  error/error_macros.cpp
  extension/extension_api_dump.cpp
  extension/gdextension_interface.cpp
  extension/gdextension_library_loader.cpp
  extension/gdextension_manager.cpp
  extension/gdextension_special_compat_hashes.cpp
  extension/gdextension.cpp
  input/input_event_codec.cpp
  input/input_event.cpp
  input/input_map.cpp
  input/input.cpp
  input/shortcut.cpp
  io/compression.cpp
  io/config_file.cpp
  io/dir_access.cpp
  io/dtls_server.cpp
  io/file_access_compressed.cpp
  io/file_access_encrypted.cpp
  io/file_access_memory.cpp
  io/file_access_pack.cpp
  io/file_access_zip.cpp
  io/file_access.cpp
  io/http_client_tcp.cpp
  io/http_client.cpp
  io/image_loader.cpp
  io/image.cpp
  io/ip_address.cpp
  io/ip.cpp
  io/json.cpp
  io/logger.cpp
  io/marshalls.cpp
  io/missing_resource.cpp
  io/net_socket.cpp
  io/packed_data_container.cpp
  io/packet_peer_dtls.cpp
  io/packet_peer_udp.cpp
  io/packet_peer.cpp
  io/pck_packer.cpp
  io/plist.cpp
  io/remote_filesystem_client.cpp
  io/resource_format_binary.cpp
  io/resource_importer.cpp
  io/resource_loader.cpp
  io/resource_saver.cpp
  io/resource_uid.cpp
  io/resource.cpp
  io/stream_peer_gzip.cpp
  io/stream_peer_tcp.cpp
  io/stream_peer_tls.cpp
  io/stream_peer.cpp
  io/tcp_server.cpp
  io/translation_loader_po.cpp
  io/udp_server.cpp
  io/xml_parser.cpp
  io/zip_io.cpp
  math/a_star_grid_2d.cpp
  math/a_star.cpp
  math/aabb.cpp
  math/basis.cpp
  math/color.cpp
  math/convex_hull.cpp
  math/dynamic_bvh.cpp
  math/expression.cpp
  math/face3.cpp
  math/geometry_2d.cpp
  math/geometry_3d.cpp
  math/math_fieldwise.cpp
  math/math_funcs.cpp
  math/plane.cpp
  math/projection.cpp
  math/quaternion.cpp
  math/quick_hull.cpp
  math/random_number_generator.cpp
  math/random_pcg.cpp
  math/rect2.cpp
  math/rect2i.cpp
  math/static_raycaster.cpp
  math/transform_2d.cpp
  math/transform_3d.cpp
  math/transform_interpolator.cpp
  math/triangle_mesh.cpp
  math/triangulate.cpp
  math/vector2.cpp
  math/vector2i.cpp
  math/vector3.cpp
  math/vector3i.cpp
  math/vector4.cpp
  math/vector4i.cpp
  object/callable_method_pointer.cpp
  object/class_db.cpp
  object/message_queue.cpp
  object/method_bind.cpp
  object/object.cpp
  object/ref_counted.cpp
  object/script_backtrace.cpp
  object/script_instance.cpp
  object/script_language_extension.cpp
  object/script_language.cpp
  object/undo_redo.cpp
  object/worker_thread_pool.cpp
  os/keyboard.cpp
  os/main_loop.cpp
  os/memory.cpp
  os/midi_driver.cpp
  os/mutex.cpp
  os/os.cpp
  os/thread_safe.cpp
  os/thread.cpp
  os/time.cpp
  register_core_types.cpp
  string/fuzzy_search.cpp
  string/node_path.cpp
  string/optimized_translation.cpp
  string/print_string.cpp
  string/string_builder.cpp
  string/string_name.cpp
  string/translation_domain.cpp
  string/translation_po.cpp
  string/translation_server.cpp
  string/translation.cpp
  string/ustring.cpp
  templates/a_hash_map.cpp
  templates/command_queue_mt.cpp
  templates/hash_map.cpp
  templates/interpolated_property.cpp
  templates/rid_owner.cpp
  variant/array.cpp
  variant/callable_bind.cpp
  variant/callable.cpp
  variant/dictionary.cpp
  variant/variant_call.cpp
  variant/variant_callable.cpp
  variant/variant_construct.cpp
  variant/variant_destruct.cpp
  variant/variant_op.cpp
  variant/variant_parser.cpp
  variant/variant_setget.cpp
  variant/variant_utility.cpp
  variant/variant.cpp
)

# GODOT_CORE_HEADERS - Header files for core
set(GODOT_CORE_HEADERS
  config/engine.h
  config/project_settings.h
  core_bind.h
  core_constants.h
  core_globals.h
  core_string_names.h
  crypto/aes_context.h
  crypto/crypto_core.h
  crypto/crypto.h
  crypto/hashing_context.h
  debugger/debugger_marshalls.h
  debugger/engine_debugger.h
  debugger/engine_profiler.h
  debugger/local_debugger.h
  debugger/remote_debugger_peer.h
  debugger/remote_debugger.h
  debugger/script_debugger.h
  doc_data.h
  error/error_list.h
  error/error_macros.h
  extension/extension_api_dump.h
  extension/gdextension_interface.h
  extension/gdextension_library_loader.h
  extension/gdextension_loader.h
  extension/gdextension_manager.h
  extension/gdextension_special_compat_hashes.h
  extension/gdextension.h
  input/default_controller_mappings.h
  input/input_enums.h
  input/input_event_codec.h
  input/input_event.h
  input/input_map.h
  input/input.h
  input/shortcut.h
  io/compression.h
  io/config_file.h
  io/dir_access.h
  io/dtls_server.h
  io/file_access_compressed.h
  io/file_access_encrypted.h
  io/file_access_memory.h
  io/file_access_pack.h
  io/file_access_zip.h
  io/file_access.h
  io/http_client_tcp.h
  io/http_client.h
  io/image_loader.h
  io/image.h
  io/ip_address.h
  io/ip.h
  io/json.h
  io/logger.h
  io/marshalls.h
  io/missing_resource.h
  io/net_socket.h
  io/packed_data_container.h
  io/packet_peer_dtls.h
  io/packet_peer_udp.h
  io/packet_peer.h
  io/pck_packer.h
  io/plist.h
  io/remote_filesystem_client.h
  io/resource_format_binary.h
  io/resource_importer.h
  io/resource_loader.h
  io/resource_saver.h
  io/resource_uid.h
  io/resource.h
  io/stream_peer_gzip.h
  io/stream_peer_tcp.h
  io/stream_peer_tls.h
  io/stream_peer.h
  io/tcp_server.h
  io/translation_loader_po.h
  io/udp_server.h
  io/xml_parser.h
  io/zip_io.h
  math/a_star_grid_2d.h
  math/a_star.h
  math/aabb.h
  math/audio_frame.h
  math/basis.h
  math/bvh_abb.h
  math/bvh_tree.h
  math/bvh.h
  math/color.h
  math/convex_hull.h
  math/delaunay_2d.h
  math/delaunay_3d.h
  math/disjoint_set.h
  math/dynamic_bvh.h
  math/expression.h
  math/face3.h
  math/geometry_2d.h
  math/geometry_3d.h
  math/math_defs.h
  math/math_fieldwise.h
  math/math_funcs.h
  math/plane.h
  math/projection.h
  math/quaternion.h
  math/quick_hull.h
  math/random_number_generator.h
  math/random_pcg.h
  math/rect2.h
  math/rect2i.h
  math/static_raycaster.h
  math/transform_2d.h
  math/transform_3d.h
  math/transform_interpolator.h
  math/triangle_mesh.h
  math/triangulate.h
  math/vector2.h
  math/vector2i.h
  math/vector3.h
  math/vector3i.h
  math/vector4.h
  math/vector4i.h
  object/callable_method_pointer.h
  object/class_db.h
  object/message_queue.h
  object/method_bind.h
  object/object_id.h
  object/object.h
  object/ref_counted.h
  object/script_backtrace.h
  object/script_instance.h
  object/script_language_extension.h
  object/script_language.h
  object/undo_redo.h
  object/worker_thread_pool.h
  os/condition_variable.h
  os/keyboard.h
  os/main_loop.h
  os/memory.h
  os/midi_driver.h
  os/mutex.h
  os/os.h
  os/rw_lock.h
  os/safe_binary_mutex.h
  os/semaphore.h
  os/shared_object.h
  os/spin_lock.h
  os/thread_safe.h
  os/thread.h
  os/time_enums.h
  os/time.h
  register_core_types.h
  string/alt_codes.h
  string/char_utils.h
  string/fuzzy_search.h
  string/locales.h
  string/node_path.h
  string/optimized_translation.h
  string/print_string.h
  string/string_buffer.h
  string/string_builder.h
  string/string_name.h
  string/translation_domain.h
  string/translation_po.h
  string/translation_server.h
  string/translation.h
  string/ucaps.h
  string/ustring.h
  templates/a_hash_map.h
  templates/bin_sorted_array.h
  templates/bit_field.h
  templates/command_queue_mt.h
  templates/cowdata.h
  templates/fixed_vector.h
  templates/hash_map.h
  templates/hash_set.h
  templates/hashfuncs.h
  templates/interpolated_property.h
  templates/list.h
  templates/local_vector.h
  templates/lru.h
  templates/oa_hash_map.h
  templates/paged_allocator.h
  templates/paged_array.h
  templates/pair.h
  templates/pass_func.h
  templates/pooled_list.h
  templates/rb_map.h
  templates/rb_set.h
  templates/rid_owner.h
  templates/rid.h
  templates/ring_buffer.h
  templates/safe_list.h
  templates/safe_refcount.h
  templates/search_array.h
  templates/self_list.h
  templates/simple_type.h
  templates/sort_array.h
  templates/span.h
  templates/tuple.h
  templates/vector.h
  templates/vset.h
  typedefs.h
  variant/array.h
  variant/binder_common.h
  variant/callable_bind.h
  variant/callable.h
  variant/container_type_validate.h
  variant/dictionary.h
  variant/method_ptrcall.h
  variant/native_ptr.h
  variant/type_info.h
  variant/typed_array.h
  variant/typed_dictionary.h
  variant/variant_callable.h
  variant/variant_construct.h
  variant/variant_destruct.h
  variant/variant_internal.h
  variant/variant_op.h
  variant/variant_parser.h
  variant/variant_setget.h
  variant/variant_utility.h
  variant/variant.h
  version.h
)

# GODOT_CORE_FILES - All files for core
set(GODOT_CORE_FILES
  ${GODOT_CORE_SOURCES}
  ${GODOT_CORE_HEADERS}
)
