#!/usr/bin/env python3
# compile_shader.py
# Script to compile GLSL shaders to C++ header files for inclusion in Godot

import os
import sys
import re

def main():
    # Check arguments
    if len(sys.argv) != 4:
        print("Usage: {} <shader_path> <output_path> <shader_type>".format(sys.argv[0]))
        sys.exit(1)
    
    shader_path = sys.argv[1]
    output_path = sys.argv[2]
    shader_type = sys.argv[3]
    
    # Check if the shader file exists
    if not os.path.exists(shader_path):
        print("Error: Shader file not found: {}".format(shader_path))
        sys.exit(1)
    
    # Create the output directory if it doesn't exist
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Read the shader file
    with open(shader_path, 'r') as shader_file:
        shader_content = shader_file.read()
    
    # Escape double quotes and backslashes
    shader_content = shader_content.replace('\\', '\\\\').replace('"', '\\"')
    
    # Split the content into lines for C++ array
    shader_lines = []
    for line in shader_content.splitlines():
        escaped_line = line.replace('\\', '\\\\').replace('"', '\\"')
        shader_lines.append('"{0}",'.format(escaped_line))
    
    # Create a unique variable name based on the shader filename
    shader_name = os.path.splitext(os.path.basename(shader_path))[0]
    header_guard = "SHADER_{}_GLSL_GEN_H".format(shader_name.upper())
    variable_name = "shader_{}_glsl_source".format(shader_name)
    
    # Generate the header file content
    header_content = """/* GENERATED FILE - DO NOT EDIT */
/* Generated by compile_shader.py */

#ifndef {0}
#define {0}

namespace {{

static const char *{1}[] = {{
{2}
}};

}} // namespace

#endif // {0}
""".format(header_guard, variable_name, "\n".join(shader_lines))
    
    # Write the output file
    with open(output_path, 'w') as output_file:
        output_file.write(header_content)
    
    print("Compiled shader: {} -> {}".format(shader_path, output_path))

if __name__ == "__main__":
    main() 