#!/usr/bin/env pwsh
# CompileShader.ps1
# Script to compile GLSL shaders to C++ header files for inclusion in Godot

param(
    [Parameter(Mandatory=$true)]
    [string]$ShaderPath,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputPath,
    
    [Parameter(Mandatory=$true)]
    [string]$ShaderType
)

# Check if the shader file exists
if (-not (Test-Path $ShaderPath)) {
    Write-Error "Error: Shader file not found: $ShaderPath"
    exit 1
}

# Create the output directory if it doesn't exist
$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# Read the shader file
$shaderContent = Get-Content -Path $ShaderPath -Raw

# Escape double quotes and backslashes
$shaderContent = $shaderContent -replace '\\', '\\\\' -replace '"', '\"'

# Split the content into lines for C++ array
$shaderLines = $shaderContent -split "`n" | ForEach-Object {
    if ($_ -match "`r$") {
        $_ = $_ -replace "`r", ""
    }
    $escapedLine = $_ -replace '\\', '\\\\' -replace '"', '\"'
    "`"$escapedLine`","
}

# Create a unique variable name based on the shader filename
$shaderName = [System.IO.Path]::GetFileNameWithoutExtension($ShaderPath)
$headerGuard = "SHADER_" + $shaderName.ToUpper() + "_GLSL_GEN_H"
$variableName = "shader_" + $shaderName + "_glsl_source"

# Generate the header file content
$headerContent = @"
/* GENERATED FILE - DO NOT EDIT */
/* Generated by CompileShader.ps1 */

#ifndef $headerGuard
#define $headerGuard

namespace {

static const char *$variableName = {
$($shaderLines -join "`n")
};

} // namespace

#endif // $headerGuard
"@

# Write the output file
$headerContent | Out-File -FilePath $OutputPath -Encoding utf8

Write-Output "Compiled shader: $ShaderPath -> $OutputPath" 