#!/usr/bin/env pwsh
# EmbedResource.ps1
# Script to embed binary resources into C++ header files for Godot

param(
    [Parameter(Mandatory=$true)]
    [string]$ResourcePath,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputPath,
    
    [Parameter(Mandatory=$true)]
    [string]$VariableName
)

# Check if the resource file exists
if (-not (Test-Path $ResourcePath)) {
    Write-Error "Error: Resource file not found: $ResourcePath"
    exit 1
}

# Create the output directory if it doesn't exist
$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# Read the resource file as bytes
$resourceBytes = [System.IO.File]::ReadAllBytes($ResourcePath)
$resourceSize = $resourceBytes.Length

# Create a hex string representation of the bytes
$hexChunks = @()
for ($i = 0; $i -lt $resourceBytes.Length; $i += 16) {
    $chunk = ""
    for ($j = 0; $j -lt 16 -and ($i + $j) -lt $resourceBytes.Length; $j++) {
        $chunk += "0x{0:X2}, " -f $resourceBytes[$i + $j]
    }
    $hexChunks += "    $chunk"
}

# Create a unique header guard based on the variable name
$headerGuard = "RESOURCE_" + $VariableName.ToUpper() + "_GEN_H"

# Generate the header file content
$headerContent = @"
/* GENERATED FILE - DO NOT EDIT */
/* Generated by EmbedResource.ps1 */

#ifndef $headerGuard
#define $headerGuard

namespace {

static const unsigned char ${VariableName}_data[] = {
$($hexChunks -join "`n")
};

static const int ${VariableName}_size = $resourceSize;

} // namespace

#endif // $headerGuard
"@

# Write the output file
$headerContent | Out-File -FilePath $OutputPath -Encoding utf8

Write-Output "Embedded resource: $ResourcePath -> $OutputPath" 