#!/usr/bin/env python3
# embed_resource.py
# Script to embed binary resources into C++ header files for Godot

import os
import sys

def main():
    # Check arguments
    if len(sys.argv) != 4:
        print("Usage: {} <resource_path> <output_path> <variable_name>".format(sys.argv[0]))
        sys.exit(1)
    
    resource_path = sys.argv[1]
    output_path = sys.argv[2]
    variable_name = sys.argv[3]
    
    # Check if the resource file exists
    if not os.path.exists(resource_path):
        print("Error: Resource file not found: {}".format(resource_path))
        sys.exit(1)
    
    # Create the output directory if it doesn't exist
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Read the resource file as bytes
    with open(resource_path, 'rb') as resource_file:
        resource_bytes = resource_file.read()
    
    resource_size = len(resource_bytes)
    
    # Create a hex string representation of the bytes
    hex_chunks = []
    for i in range(0, resource_size, 16):
        chunk = ""
        for j in range(16):
            if i + j < resource_size:
                chunk += "0x{:02X}, ".format(resource_bytes[i + j])
        hex_chunks.append("    {}".format(chunk))
    
    # Create a unique header guard based on the variable name
    header_guard = "RESOURCE_" + variable_name.upper() + "_GEN_H"
    
    # Generate the header file content
    header_content = """/* GENERATED FILE - DO NOT EDIT */
/* Generated by embed_resource.py */

#ifndef {0}
#define {0}

namespace {{

static const unsigned char {1}_data[] = {{
{2}
}};

static const int {1}_size = {3};

}} // namespace

#endif // {0}
""".format(header_guard, variable_name, "\n".join(hex_chunks), resource_size)
    
    # Write the output file
    with open(output_path, 'w') as output_file:
        output_file.write(header_content)
    
    print("Embedded resource: {} -> {}".format(resource_path, output_path))

if __name__ == "__main__":
    main() 