#!/usr/bin/env pwsh
# PowerShell script to compile GLSL shaders into C++ headers
# This is designed to be cross-platform (Windows, macOS, Linux)

param(
    [Parameter(Mandatory=$true)]
    [string]$ShaderFile,
    
    [Parameter(Mandatory=$true)]
    [string]$HeaderFile,
    
    [Parameter(Mandatory=$true)]
    [string]$VariableName
)

# Ensure the directory exists
$HeaderDir = Split-Path -Path $HeaderFile -Parent
if (-not (Test-Path -Path $HeaderDir)) {
    New-Item -ItemType Directory -Path $HeaderDir -Force | Out-Null
}

# Read the shader file
$ShaderContent = Get-Content -Raw -Path $ShaderFile -Encoding UTF8

# Process the shader content (strip comments, normalize line endings)
$ShaderContent = $ShaderContent -replace '\/\/.*$', '' -replace '[\r\n]+', "`n"

# Escape special characters
$ShaderContent = $ShaderContent -replace '\\', '\\\\' -replace '"', '\"' -replace '\n', '\n" LINE_CONT\n"'

# Generate the header content
$HeaderContent = @"
/* Generated by Godot CMake shader compiler */
/* File: $ShaderFile */

#ifndef ${VariableName}_H
#define ${VariableName}_H

#define LINE_CONT

static const char *${VariableName} = 
"${ShaderContent}";

#undef LINE_CONT

#endif // ${VariableName}_H

"@

# Write the header file (make sure to use UTF-8 without BOM)
$Utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($HeaderFile, $HeaderContent, $Utf8NoBom)

Write-Host "Successfully compiled shader: $ShaderFile -> $HeaderFile" 