#!/usr/bin/env pwsh
# PowerShell script to embed resources into C++ source files
# This is designed to be cross-platform (Windows, macOS, Linux)

param(
    [Parameter(Mandatory=$true)]
    [string]$ResourcesDir,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputCpp,
    
    [Parameter(Mandatory=$true)]
    [string]$OutputH,
    
    [Parameter(Mandatory=$true, ValueFromRemainingArguments=$true)]
    [string[]]$ResourcesList
)

# Ensure output directories exist
$OutputCppDir = Split-Path -Path $OutputCpp -Parent
$OutputHDir = Split-Path -Path $OutputH -Parent

if (-not (Test-Path -Path $OutputCppDir)) {
    New-Item -ItemType Directory -Path $OutputCppDir -Force | Out-Null
}

if (-not (Test-Path -Path $OutputHDir)) {
    New-Item -ItemType Directory -Path $OutputHDir -Force | Out-Null
}

# Begin generating the header file
$HeaderContent = @"
/* Generated by Godot CMake resource embedder */
/* Auto-generated, do not edit */

#ifndef EDITOR_EMBEDDED_RESOURCES_H
#define EDITOR_EMBEDDED_RESOURCES_H

#include "core/io/resource.h"

// Resource registry function
void register_editor_embedded_resources();

// Resource getter functions
const unsigned char *get_resource_data(const char *p_path, uint64_t *r_len);

#endif // EDITOR_EMBEDDED_RESOURCES_H

"@

# Begin generating the implementation file
$CppContent = @"
/* Generated by Godot CMake resource embedder */
/* Auto-generated, do not edit */

#include "editor_embedded_resources.h"
#include "core/io/resource_loader.h"
#include <unordered_map>
#include <string>

namespace {
    struct EmbeddedResource {
        const unsigned char *data;
        uint64_t size;
    };

    std::unordered_map<std::string, EmbeddedResource> embedded_resources;
}

"@

# Process each resource and add it to the implementation file
foreach ($ResourceFile in $ResourcesList) {
    $ResourcePath = Join-Path -Path $ResourcesDir -ChildPath $ResourceFile
    
    # Skip non-existent files
    if (-not (Test-Path -Path $ResourcePath)) {
        Write-Warning "Resource file not found: $ResourcePath"
        continue
    }
    
    # Read the resource file as binary
    $ResourceBytes = [System.IO.File]::ReadAllBytes($ResourcePath)
    $ResourceSize = $ResourceBytes.Length
    
    # Create a safe variable name
    $SafeName = $ResourceFile.Replace('/', '_').Replace('.', '_').Replace('-', '_')
    
    # Add the resource data to the implementation file
    $CppContent += "// Resource: $ResourceFile`n"
    $CppContent += "static const unsigned char ${SafeName}_data[] = {`n"
    
    # Add the binary data in a formatted way (16 bytes per line)
    for ($i = 0; $i -lt $ResourceSize; $i += 16) {
        $Line = "    "
        $End = [Math]::Min($i + 16, $ResourceSize)
        
        for ($j = $i; $j -lt $End; $j++) {
            $Line += "0x{0:X2}, " -f $ResourceBytes[$j]
        }
        
        $CppContent += "$Line`n"
    }
    
    $CppContent += "};`n`n"
}

# Add the resource registration function
$CppContent += @"
void register_editor_embedded_resources() {
    // Register all embedded resources
"@

foreach ($ResourceFile in $ResourcesList) {
    $SafeName = $ResourceFile.Replace('/', '_').Replace('.', '_').Replace('-', '_')
    $CppContent += "    embedded_resources[`"res://editor/$ResourceFile`"] = {${SafeName}_data, sizeof(${SafeName}_data)};`n"
}

$CppContent += @"
}

const unsigned char *get_resource_data(const char *p_path, uint64_t *r_len) {
    auto it = embedded_resources.find(p_path);
    if (it != embedded_resources.end()) {
        *r_len = it->second.size;
        return it->second.data;
    }
    
    *r_len = 0;
    return nullptr;
}
"@

# Write the files (make sure to use UTF-8 without BOM)
$Utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputH, $HeaderContent, $Utf8NoBom)
[System.IO.File]::WriteAllText($OutputCpp, $CppContent, $Utf8NoBom)

Write-Host "Successfully embedded resources to $OutputCpp and $OutputH" 