# Generated source list for core (root-relative paths)
# GODOT_CORE_SOURCES - Source files for core
set(GODOT_CORE_SOURCES
  core/config/engine.cpp
  core/config/project_settings.cpp
  core/core_bind.cpp
  core/core_constants.cpp
  core/crypto/aes_context.cpp
  core/crypto/crypto_core.cpp
  core/crypto/crypto.cpp
  core/crypto/hashing_context.cpp
  core/debugger/debugger_marshalls.cpp
  core/debugger/engine_debugger.cpp
  core/debugger/engine_profiler.cpp
  core/debugger/local_debugger.cpp
  core/debugger/remote_debugger_peer.cpp
  core/debugger/remote_debugger.cpp
  core/debugger/script_debugger.cpp
  core/doc_data.cpp
  core/error/error_list.cpp
  core/error/error_macros.cpp
  core/extension/extension_api_dump.cpp
  core/extension/gdextension_interface.cpp
  core/extension/gdextension_library_loader.cpp
  core/extension/gdextension_manager.cpp
  core/extension/gdextension_special_compat_hashes.cpp
  core/extension/gdextension.cpp
  core/input/input_event_codec.cpp
  core/input/input_event.cpp
  core/input/input_map.cpp
  core/input/input.cpp
  core/input/shortcut.cpp
  core/io/compression.cpp
  core/io/config_file.cpp
  core/io/dir_access.cpp
  core/io/dtls_server.cpp
  core/io/file_access_compressed.cpp
  core/io/file_access_encrypted.cpp
  core/io/file_access_memory.cpp
  core/io/file_access_pack.cpp
  core/io/file_access_zip.cpp
  core/io/file_access.cpp
  core/io/http_client_tcp.cpp
  core/io/http_client.cpp
  core/io/image_loader.cpp
  core/io/image.cpp
  core/io/ip_address.cpp
  core/io/ip.cpp
  core/io/json.cpp
  core/io/logger.cpp
  core/io/marshalls.cpp
  core/io/missing_resource.cpp
  core/io/net_socket.cpp
  core/io/packed_data_container.cpp
  core/io/packet_peer_dtls.cpp
  core/io/packet_peer_udp.cpp
  core/io/packet_peer.cpp
  core/io/pck_packer.cpp
  core/io/plist.cpp
  core/io/remote_filesystem_client.cpp
  core/io/resource_format_binary.cpp
  core/io/resource_importer.cpp
  core/io/resource_loader.cpp
  core/io/resource_saver.cpp
  core/io/resource_uid.cpp
  core/io/resource.cpp
  core/io/stream_peer_gzip.cpp
  core/io/stream_peer_tcp.cpp
  core/io/stream_peer_tls.cpp
  core/io/stream_peer.cpp
  core/io/tcp_server.cpp
  core/io/translation_loader_po.cpp
  core/io/udp_server.cpp
  core/io/xml_parser.cpp
  core/io/zip_io.cpp
  core/math/a_star_grid_2d.cpp
  core/math/a_star.cpp
  core/math/aabb.cpp
  core/math/basis.cpp
  core/math/color.cpp
  core/math/convex_hull.cpp
  core/math/dynamic_bvh.cpp
  core/math/expression.cpp
  core/math/face3.cpp
  core/math/geometry_2d.cpp
  core/math/geometry_3d.cpp
  core/math/math_fieldwise.cpp
  core/math/math_funcs.cpp
  core/math/plane.cpp
  core/math/projection.cpp
  core/math/quaternion.cpp
  core/math/quick_hull.cpp
  core/math/random_number_generator.cpp
  core/math/random_pcg.cpp
  core/math/rect2.cpp
  core/math/rect2i.cpp
  core/math/static_raycaster.cpp
  core/math/transform_2d.cpp
  core/math/transform_3d.cpp
  core/math/transform_interpolator.cpp
  core/math/triangle_mesh.cpp
  core/math/triangulate.cpp
  core/math/vector2.cpp
  core/math/vector2i.cpp
  core/math/vector3.cpp
  core/math/vector3i.cpp
  core/math/vector4.cpp
  core/math/vector4i.cpp
  core/object/callable_method_pointer.cpp
  core/object/class_db.cpp
  core/object/message_queue.cpp
  core/object/method_bind.cpp
  core/object/object.cpp
  core/object/ref_counted.cpp
  core/object/script_backtrace.cpp
  core/object/script_instance.cpp
  core/object/script_language_extension.cpp
  core/object/script_language.cpp
  core/object/undo_redo.cpp
  core/object/worker_thread_pool.cpp
  core/os/keyboard.cpp
  core/os/main_loop.cpp
  core/os/memory.cpp
  core/os/midi_driver.cpp
  core/os/mutex.cpp
  core/os/os.cpp
  core/os/thread_safe.cpp
  core/os/thread.cpp
  core/os/time.cpp
  core/register_core_types.cpp
  core/string/fuzzy_search.cpp
  core/string/node_path.cpp
  core/string/optimized_translation.cpp
  core/string/print_string.cpp
  core/string/string_builder.cpp
  core/string/string_name.cpp
  core/string/translation_domain.cpp
  core/string/translation_po.cpp
  core/string/translation_server.cpp
  core/string/translation.cpp
  core/string/ustring.cpp
  core/templates/a_hash_map.cpp
  core/templates/command_queue_mt.cpp
  core/templates/hash_map.cpp
  core/templates/interpolated_property.cpp
  core/templates/rid_owner.cpp
  core/variant/array.cpp
  core/variant/callable_bind.cpp
  core/variant/callable.cpp
  core/variant/dictionary.cpp
  core/variant/variant_call.cpp
  core/variant/variant_callable.cpp
  core/variant/variant_construct.cpp
  core/variant/variant_destruct.cpp
  core/variant/variant_op.cpp
  core/variant/variant_parser.cpp
  core/variant/variant_setget.cpp
  core/variant/variant_utility.cpp
  core/variant/variant.cpp
)

# GODOT_CORE_HEADERS - Header files for core
set(GODOT_CORE_HEADERS
  core/config/engine.h
  core/config/project_settings.h
  core/core_bind.h
  core/core_constants.h
  core/core_globals.h
  core/core_string_names.h
  core/crypto/aes_context.h
  core/crypto/crypto_core.h
  core/crypto/crypto.h
  core/crypto/hashing_context.h
  core/debugger/debugger_marshalls.h
  core/debugger/engine_debugger.h
  core/debugger/engine_profiler.h
  core/debugger/local_debugger.h
  core/debugger/remote_debugger_peer.h
  core/debugger/remote_debugger.h
  core/debugger/script_debugger.h
  core/doc_data.h
  core/error/error_list.h
  core/error/error_macros.h
  core/extension/extension_api_dump.h
  core/extension/gdextension_interface.h
  core/extension/gdextension_library_loader.h
  core/extension/gdextension_loader.h
  core/extension/gdextension_manager.h
  core/extension/gdextension_special_compat_hashes.h
  core/extension/gdextension.h
  core/input/default_controller_mappings.h
  core/input/input_enums.h
  core/input/input_event_codec.h
  core/input/input_event.h
  core/input/input_map.h
  core/input/input.h
  core/input/shortcut.h
  core/io/compression.h
  core/io/config_file.h
  core/io/dir_access.h
  core/io/dtls_server.h
  core/io/file_access_compressed.h
  core/io/file_access_encrypted.h
  core/io/file_access_memory.h
  core/io/file_access_pack.h
  core/io/file_access_zip.h
  core/io/file_access.h
  core/io/http_client_tcp.h
  core/io/http_client.h
  core/io/image_loader.h
  core/io/image.h
  core/io/ip_address.h
  core/io/ip.h
  core/io/json.h
  core/io/logger.h
  core/io/marshalls.h
  core/io/missing_resource.h
  core/io/net_socket.h
  core/io/packed_data_container.h
  core/io/packet_peer_dtls.h
  core/io/packet_peer_udp.h
  core/io/packet_peer.h
  core/io/pck_packer.h
  core/io/plist.h
  core/io/remote_filesystem_client.h
  core/io/resource_format_binary.h
  core/io/resource_importer.h
  core/io/resource_loader.h
  core/io/resource_saver.h
  core/io/resource_uid.h
  core/io/resource.h
  core/io/stream_peer_gzip.h
  core/io/stream_peer_tcp.h
  core/io/stream_peer_tls.h
  core/io/stream_peer.h
  core/io/tcp_server.h
  core/io/translation_loader_po.h
  core/io/udp_server.h
  core/io/xml_parser.h
  core/io/zip_io.h
  core/math/a_star_grid_2d.h
  core/math/a_star.h
  core/math/aabb.h
  core/math/audio_frame.h
  core/math/basis.h
  core/math/bvh_abb.h
  core/math/bvh_tree.h
  core/math/bvh.h
  core/math/color.h
  core/math/convex_hull.h
  core/math/delaunay_2d.h
  core/math/delaunay_3d.h
  core/math/disjoint_set.h
  core/math/dynamic_bvh.h
  core/math/expression.h
  core/math/face3.h
  core/math/geometry_2d.h
  core/math/geometry_3d.h
  core/math/math_defs.h
  core/math/math_fieldwise.h
  core/math/math_funcs.h
  core/math/plane.h
  core/math/projection.h
  core/math/quaternion.h
  core/math/quick_hull.h
  core/math/random_number_generator.h
  core/math/random_pcg.h
  core/math/rect2.h
  core/math/rect2i.h
  core/math/static_raycaster.h
  core/math/transform_2d.h
  core/math/transform_3d.h
  core/math/transform_interpolator.h
  core/math/triangle_mesh.h
  core/math/triangulate.h
  core/math/vector2.h
  core/math/vector2i.h
  core/math/vector3.h
  core/math/vector3i.h
  core/math/vector4.h
  core/math/vector4i.h
  core/object/callable_method_pointer.h
  core/object/class_db.h
  core/object/message_queue.h
  core/object/method_bind.h
  core/object/object_id.h
  core/object/object.h
  core/object/ref_counted.h
  core/object/script_backtrace.h
  core/object/script_instance.h
  core/object/script_language_extension.h
  core/object/script_language.h
  core/object/undo_redo.h
  core/object/worker_thread_pool.h
  core/os/condition_variable.h
  core/os/keyboard.h
  core/os/main_loop.h
  core/os/memory.h
  core/os/midi_driver.h
  core/os/mutex.h
  core/os/os.h
  core/os/rw_lock.h
  core/os/safe_binary_mutex.h
  core/os/semaphore.h
  core/os/shared_object.h
  core/os/spin_lock.h
  core/os/thread_safe.h
  core/os/thread.h
  core/os/time_enums.h
  core/os/time.h
  core/register_core_types.h
  core/string/alt_codes.h
  core/string/char_utils.h
  core/string/fuzzy_search.h
  core/string/locales.h
  core/string/node_path.h
  core/string/optimized_translation.h
  core/string/print_string.h
  core/string/string_buffer.h
  core/string/string_builder.h
  core/string/string_name.h
  core/string/translation_domain.h
  core/string/translation_po.h
  core/string/translation_server.h
  core/string/translation.h
  core/string/ucaps.h
  core/string/ustring.h
  core/templates/a_hash_map.h
  core/templates/bin_sorted_array.h
  core/templates/bit_field.h
  core/templates/command_queue_mt.h
  core/templates/cowdata.h
  core/templates/fixed_vector.h
  core/templates/hash_map.h
  core/templates/hash_set.h
  core/templates/hashfuncs.h
  core/templates/interpolated_property.h
  core/templates/list.h
  core/templates/local_vector.h
  core/templates/lru.h
  core/templates/oa_hash_map.h
  core/templates/paged_allocator.h
  core/templates/paged_array.h
  core/templates/pair.h
  core/templates/pass_func.h
  core/templates/pooled_list.h
  core/templates/rb_map.h
  core/templates/rb_set.h
  core/templates/rid_owner.h
  core/templates/rid.h
  core/templates/ring_buffer.h
  core/templates/safe_list.h
  core/templates/safe_refcount.h
  core/templates/search_array.h
  core/templates/self_list.h
  core/templates/simple_type.h
  core/templates/sort_array.h
  core/templates/span.h
  core/templates/tuple.h
  core/templates/vector.h
  core/templates/vset.h
  core/typedefs.h
  core/variant/array.h
  core/variant/binder_common.h
  core/variant/callable_bind.h
  core/variant/callable.h
  core/variant/container_type_validate.h
  core/variant/dictionary.h
  core/variant/method_ptrcall.h
  core/variant/native_ptr.h
  core/variant/type_info.h
  core/variant/typed_array.h
  core/variant/typed_dictionary.h
  core/variant/variant_callable.h
  core/variant/variant_construct.h
  core/variant/variant_destruct.h
  core/variant/variant_internal.h
  core/variant/variant_op.h
  core/variant/variant_parser.h
  core/variant/variant_setget.h
  core/variant/variant_utility.h
  core/variant/variant.h
  core/version.h
)

# GODOT_CORE_FILES - All files for core
set(GODOT_CORE_FILES
  ${GODOT_CORE_SOURCES}
  ${GODOT_CORE_HEADERS}
)
