# Generated source list for editor (root-relative paths)
# GODOT_EDITOR_SOURCES - Source files for editor
set(GODOT_EDITOR_SOURCES
  editor/action_map_editor.cpp
  editor/add_metadata_dialog.cpp
  editor/animation_bezier_editor.cpp
  editor/animation_track_editor_plugins.cpp
  editor/animation_track_editor.cpp
  editor/audio_stream_preview.cpp
  editor/code_editor.cpp
  editor/connections_dialog.cpp
  editor/create_dialog.cpp
  editor/credits_roll.cpp
  editor/debugger/debug_adapter/debug_adapter_parser.cpp
  editor/debugger/debug_adapter/debug_adapter_protocol.cpp
  editor/debugger/debug_adapter/debug_adapter_server.cpp
  editor/debugger/editor_debugger_inspector.cpp
  editor/debugger/editor_debugger_node.cpp
  editor/debugger/editor_debugger_server.cpp
  editor/debugger/editor_debugger_tree.cpp
  editor/debugger/editor_expression_evaluator.cpp
  editor/debugger/editor_file_server.cpp
  editor/debugger/editor_performance_profiler.cpp
  editor/debugger/editor_profiler.cpp
  editor/debugger/editor_visual_profiler.cpp
  editor/debugger/script_editor_debugger.cpp
  editor/dependency_editor.cpp
  editor/directory_create_dialog.cpp
  editor/doc_tools.cpp
  editor/editor_about.cpp
  editor/editor_asset_installer.cpp
  editor/editor_atlas_packer.cpp
  editor/editor_audio_buses.cpp
  editor/editor_autoload_settings.cpp
  editor/editor_build_profile.cpp
  editor/editor_command_palette.cpp
  editor/editor_data.cpp
  editor/editor_dock_manager.cpp
  editor/editor_feature_profile.cpp
  editor/editor_file_system.cpp
  editor/editor_folding.cpp
  editor/editor_help_search.cpp
  editor/editor_help.cpp
  editor/editor_inspector.cpp
  editor/editor_interface.cpp
  editor/editor_layouts_dialog.cpp
  editor/editor_locale_dialog.cpp
  editor/editor_log.cpp
  editor/editor_main_screen.cpp
  editor/editor_native_shader_source_visualizer.cpp
  editor/editor_node.cpp
  editor/editor_paths.cpp
  editor/editor_properties_array_dict.cpp
  editor/editor_properties_vector.cpp
  editor/editor_properties.cpp
  editor/editor_property_name_processor.cpp
  editor/editor_resource_picker.cpp
  editor/editor_resource_preview.cpp
  editor/editor_run_native.cpp
  editor/editor_run.cpp
  editor/editor_script.cpp
  editor/editor_sectioned_inspector.cpp
  editor/editor_settings_dialog.cpp
  editor/editor_settings.cpp
  editor/editor_translation_parser.cpp
  editor/editor_translation.cpp
  editor/editor_undo_redo_manager.cpp
  editor/editor_vcs_interface.cpp
  editor/engine_update_label.cpp
  editor/event_listener_line_edit.cpp
  editor/export/codesign.cpp
  editor/export/editor_export_platform_extension.cpp
  editor/export/editor_export_platform_pc.cpp
  editor/export/editor_export_platform.cpp
  editor/export/editor_export_plugin.cpp
  editor/export/editor_export_preset.cpp
  editor/export/editor_export.cpp
  editor/export/export_template_manager.cpp
  editor/export/lipo.cpp
  editor/export/macho.cpp
  editor/export/project_export.cpp
  editor/export/project_zip_packer.cpp
  editor/fbx_importer_manager.cpp
  editor/file_info.cpp
  editor/filesystem_dock.cpp
  editor/find_in_files.cpp
  editor/group_settings_editor.cpp
  editor/groups_editor.cpp
  editor/gui/editor_bottom_panel.cpp
  editor/gui/editor_dir_dialog.cpp
  editor/gui/editor_file_dialog.cpp
  editor/gui/editor_object_selector.cpp
  editor/gui/editor_quick_open_dialog.cpp
  editor/gui/editor_run_bar.cpp
  editor/gui/editor_scene_tabs.cpp
  editor/gui/editor_spin_slider.cpp
  editor/gui/editor_title_bar.cpp
  editor/gui/editor_toaster.cpp
  editor/gui/editor_validation_panel.cpp
  editor/gui/editor_version_button.cpp
  editor/gui/editor_zoom_widget.cpp
  editor/gui/scene_tree_editor.cpp
  editor/gui/touch_actions_panel.cpp
  editor/history_dock.cpp
  editor/import_defaults_editor.cpp
  editor/import_dock.cpp
  editor/import/3d/collada.cpp
  editor/import/3d/editor_import_collada.cpp
  editor/import/3d/post_import_plugin_skeleton_renamer.cpp
  editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp
  editor/import/3d/post_import_plugin_skeleton_track_organizer.cpp
  editor/import/3d/resource_importer_obj.cpp
  editor/import/3d/resource_importer_scene.cpp
  editor/import/3d/scene_import_settings.cpp
  editor/import/audio_stream_import_settings.cpp
  editor/import/dynamic_font_import_settings.cpp
  editor/import/editor_import_plugin.cpp
  editor/import/resource_importer_bitmask.cpp
  editor/import/resource_importer_bmfont.cpp
  editor/import/resource_importer_csv_translation.cpp
  editor/import/resource_importer_dynamic_font.cpp
  editor/import/resource_importer_image.cpp
  editor/import/resource_importer_imagefont.cpp
  editor/import/resource_importer_layered_texture.cpp
  editor/import/resource_importer_shader_file.cpp
  editor/import/resource_importer_svg.cpp
  editor/import/resource_importer_texture_atlas.cpp
  editor/import/resource_importer_texture_settings.cpp
  editor/import/resource_importer_texture.cpp
  editor/import/resource_importer_wav.cpp
  editor/input_event_configuration_dialog.cpp
  editor/inspector_dock.cpp
  editor/localization_editor.cpp
  editor/multi_node_edit.cpp
  editor/node_dock.cpp
  editor/plugins/abstract_polygon_2d_editor.cpp
  editor/plugins/animation_blend_space_1d_editor.cpp
  editor/plugins/animation_blend_space_2d_editor.cpp
  editor/plugins/animation_blend_tree_editor_plugin.cpp
  editor/plugins/animation_library_editor.cpp
  editor/plugins/animation_player_editor_plugin.cpp
  editor/plugins/animation_state_machine_editor.cpp
  editor/plugins/animation_tree_editor_plugin.cpp
  editor/plugins/asset_library_editor_plugin.cpp
  editor/plugins/audio_stream_editor_plugin.cpp
  editor/plugins/audio_stream_randomizer_editor_plugin.cpp
  editor/plugins/bit_map_editor_plugin.cpp
  editor/plugins/bone_map_editor_plugin.cpp
  editor/plugins/camera_2d_editor_plugin.cpp
  editor/plugins/camera_3d_editor_plugin.cpp
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/plugins/cast_2d_editor_plugin.cpp
  editor/plugins/collision_polygon_2d_editor_plugin.cpp
  editor/plugins/collision_shape_2d_editor_plugin.cpp
  editor/plugins/color_channel_selector.cpp
  editor/plugins/control_editor_plugin.cpp
  editor/plugins/curve_editor_plugin.cpp
  editor/plugins/debugger_editor_plugin.cpp
  editor/plugins/dedicated_server_export_plugin.cpp
  editor/plugins/editor_context_menu_plugin.cpp
  editor/plugins/editor_debugger_plugin.cpp
  editor/plugins/editor_plugin_settings.cpp
  editor/plugins/editor_plugin.cpp
  editor/plugins/editor_preview_plugins.cpp
  editor/plugins/editor_resource_conversion_plugin.cpp
  editor/plugins/editor_resource_tooltip_plugins.cpp
  editor/plugins/embedded_process.cpp
  editor/plugins/font_config_plugin.cpp
  editor/plugins/game_view_plugin.cpp
  editor/plugins/gizmos/audio_listener_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/audio_stream_player_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/camera_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/collision_object_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/collision_polygon_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/collision_shape_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/cpu_particles_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/decal_gizmo_plugin.cpp
  editor/plugins/gizmos/fog_volume_gizmo_plugin.cpp
  editor/plugins/gizmos/geometry_instance_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/gizmo_3d_helper.cpp
  editor/plugins/gizmos/gpu_particles_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/gpu_particles_collision_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/joint_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/label_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/light_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/lightmap_gi_gizmo_plugin.cpp
  editor/plugins/gizmos/lightmap_probe_gizmo_plugin.cpp
  editor/plugins/gizmos/marker_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/mesh_instance_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/occluder_instance_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/particles_3d_emission_shape_gizmo_plugin.cpp
  editor/plugins/gizmos/physics_bone_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/ray_cast_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/reflection_probe_gizmo_plugin.cpp
  editor/plugins/gizmos/shape_cast_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/soft_body_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/spring_arm_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/spring_bone_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/sprite_base_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/vehicle_body_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/visible_on_screen_notifier_3d_gizmo_plugin.cpp
  editor/plugins/gizmos/voxel_gi_gizmo_plugin.cpp
  editor/plugins/gpu_particles_collision_sdf_editor_plugin.cpp
  editor/plugins/gradient_editor_plugin.cpp
  editor/plugins/gradient_texture_2d_editor_plugin.cpp
  editor/plugins/input_event_editor_plugin.cpp
  editor/plugins/light_occluder_2d_editor_plugin.cpp
  editor/plugins/lightmap_gi_editor_plugin.cpp
  editor/plugins/line_2d_editor_plugin.cpp
  editor/plugins/material_editor_plugin.cpp
  editor/plugins/mesh_editor_plugin.cpp
  editor/plugins/mesh_instance_3d_editor_plugin.cpp
  editor/plugins/mesh_library_editor_plugin.cpp
  editor/plugins/multimesh_editor_plugin.cpp
  editor/plugins/node_3d_editor_gizmos.cpp
  editor/plugins/node_3d_editor_plugin.cpp
  editor/plugins/occluder_instance_3d_editor_plugin.cpp
  editor/plugins/packed_scene_editor_plugin.cpp
  editor/plugins/packed_scene_translation_parser_plugin.cpp
  editor/plugins/parallax_background_editor_plugin.cpp
  editor/plugins/particle_process_material_editor_plugin.cpp
  editor/plugins/particles_editor_plugin.cpp
  editor/plugins/path_2d_editor_plugin.cpp
  editor/plugins/path_3d_editor_plugin.cpp
  editor/plugins/physical_bone_3d_editor_plugin.cpp
  editor/plugins/plugin_config_dialog.cpp
  editor/plugins/polygon_2d_editor_plugin.cpp
  editor/plugins/polygon_3d_editor_plugin.cpp
  editor/plugins/resource_preloader_editor_plugin.cpp
  editor/plugins/root_motion_editor_plugin.cpp
  editor/plugins/script_editor_plugin.cpp
  editor/plugins/script_text_editor.cpp
  editor/plugins/shader_editor_plugin.cpp
  editor/plugins/shader_file_editor_plugin.cpp
  editor/plugins/skeleton_2d_editor_plugin.cpp
  editor/plugins/skeleton_3d_editor_plugin.cpp
  editor/plugins/skeleton_ik_3d_editor_plugin.cpp
  editor/plugins/sprite_2d_editor_plugin.cpp
  editor/plugins/sprite_frames_editor_plugin.cpp
  editor/plugins/style_box_editor_plugin.cpp
  editor/plugins/sub_viewport_preview_editor_plugin.cpp
  editor/plugins/text_editor.cpp
  editor/plugins/text_shader_editor.cpp
  editor/plugins/texture_3d_editor_plugin.cpp
  editor/plugins/texture_editor_plugin.cpp
  editor/plugins/texture_layered_editor_plugin.cpp
  editor/plugins/texture_region_editor_plugin.cpp
  editor/plugins/theme_editor_plugin.cpp
  editor/plugins/theme_editor_preview.cpp
  editor/plugins/tiles/atlas_merging_dialog.cpp
  editor/plugins/tiles/tile_atlas_view.cpp
  editor/plugins/tiles/tile_data_editors.cpp
  editor/plugins/tiles/tile_map_layer_editor.cpp
  editor/plugins/tiles/tile_proxies_manager_dialog.cpp
  editor/plugins/tiles/tile_set_atlas_source_editor.cpp
  editor/plugins/tiles/tile_set_editor.cpp
  editor/plugins/tiles/tile_set_scenes_collection_source_editor.cpp
  editor/plugins/tiles/tiles_editor_plugin.cpp
  editor/plugins/tool_button_editor_plugin.cpp
  editor/plugins/version_control_editor_plugin.cpp
  editor/plugins/visual_shader_editor_plugin.cpp
  editor/plugins/voxel_gi_editor_plugin.cpp
  editor/pot_generator.cpp
  editor/progress_dialog.cpp
  editor/project_converter_3_to_4.cpp
  editor/project_manager.cpp
  editor/project_manager/project_dialog.cpp
  editor/project_manager/project_list.cpp
  editor/project_manager/project_tag.cpp
  editor/project_manager/quick_settings_dialog.cpp
  editor/project_settings_editor.cpp
  editor/project_upgrade_tool.cpp
  editor/property_selector.cpp
  editor/register_editor_types.cpp
  editor/rename_dialog.cpp
  editor/renames_map_3_to_4.cpp
  editor/reparent_dialog.cpp
  editor/run_instances_dialog.cpp
  editor/scene_create_dialog.cpp
  editor/scene_tree_dock.cpp
  editor/script_create_dialog.cpp
  editor/shader_create_dialog.cpp
  editor/shader_globals_editor.cpp
  editor/themes/editor_color_map.cpp
  editor/themes/editor_fonts.cpp
  editor/themes/editor_icons.cpp
  editor/themes/editor_scale.cpp
  editor/themes/editor_theme_manager.cpp
  editor/themes/editor_theme.cpp
  editor/window_wrapper.cpp
)

# GODOT_EDITOR_HEADERS - Header files for editor
set(GODOT_EDITOR_HEADERS
  editor/action_map_editor.h
  editor/add_metadata_dialog.h
  editor/animation_bezier_editor.h
  editor/animation_track_editor_plugins.h
  editor/animation_track_editor.h
  editor/audio_stream_preview.h
  editor/code_editor.h
  editor/connections_dialog.h
  editor/create_dialog.h
  editor/credits_roll.h
  editor/debugger/debug_adapter/debug_adapter_parser.h
  editor/debugger/debug_adapter/debug_adapter_protocol.h
  editor/debugger/debug_adapter/debug_adapter_server.h
  editor/debugger/debug_adapter/debug_adapter_types.h
  editor/debugger/editor_debugger_inspector.h
  editor/debugger/editor_debugger_node.h
  editor/debugger/editor_debugger_server.h
  editor/debugger/editor_debugger_tree.h
  editor/debugger/editor_expression_evaluator.h
  editor/debugger/editor_file_server.h
  editor/debugger/editor_performance_profiler.h
  editor/debugger/editor_profiler.h
  editor/debugger/editor_visual_profiler.h
  editor/debugger/script_editor_debugger.h
  editor/dependency_editor.h
  editor/directory_create_dialog.h
  editor/doc_tools.h
  editor/editor_about.h
  editor/editor_asset_installer.h
  editor/editor_atlas_packer.h
  editor/editor_audio_buses.h
  editor/editor_autoload_settings.h
  editor/editor_build_profile.h
  editor/editor_command_palette.h
  editor/editor_data.h
  editor/editor_dock_manager.h
  editor/editor_feature_profile.h
  editor/editor_file_system.h
  editor/editor_folding.h
  editor/editor_help_search.h
  editor/editor_help.h
  editor/editor_inspector.h
  editor/editor_interface.h
  editor/editor_layouts_dialog.h
  editor/editor_locale_dialog.h
  editor/editor_log.h
  editor/editor_main_screen.h
  editor/editor_native_shader_source_visualizer.h
  editor/editor_node.h
  editor/editor_paths.h
  editor/editor_properties_array_dict.h
  editor/editor_properties_vector.h
  editor/editor_properties.h
  editor/editor_property_name_processor.h
  editor/editor_resource_picker.h
  editor/editor_resource_preview.h
  editor/editor_run_native.h
  editor/editor_run.h
  editor/editor_script.h
  editor/editor_sectioned_inspector.h
  editor/editor_settings_dialog.h
  editor/editor_settings.h
  editor/editor_string_names.h
  editor/editor_translation_parser.h
  editor/editor_translation.h
  editor/editor_undo_redo_manager.h
  editor/editor_vcs_interface.h
  editor/engine_update_label.h
  editor/event_listener_line_edit.h
  editor/export/codesign.h
  editor/export/editor_export_platform_extension.h
  editor/export/editor_export_platform_pc.h
  editor/export/editor_export_platform.h
  editor/export/editor_export_plugin.h
  editor/export/editor_export_preset.h
  editor/export/editor_export.h
  editor/export/export_template_manager.h
  editor/export/lipo.h
  editor/export/macho.h
  editor/export/project_export.h
  editor/export/project_zip_packer.h
  editor/fbx_importer_manager.h
  editor/file_info.h
  editor/filesystem_dock.h
  editor/find_in_files.h
  editor/group_settings_editor.h
  editor/groups_editor.h
  editor/gui/editor_bottom_panel.h
  editor/gui/editor_dir_dialog.h
  editor/gui/editor_file_dialog.h
  editor/gui/editor_object_selector.h
  editor/gui/editor_quick_open_dialog.h
  editor/gui/editor_run_bar.h
  editor/gui/editor_scene_tabs.h
  editor/gui/editor_spin_slider.h
  editor/gui/editor_title_bar.h
  editor/gui/editor_toaster.h
  editor/gui/editor_validation_panel.h
  editor/gui/editor_version_button.h
  editor/gui/editor_zoom_widget.h
  editor/gui/scene_tree_editor.h
  editor/gui/touch_actions_panel.h
  editor/history_dock.h
  editor/import_defaults_editor.h
  editor/import_dock.h
  editor/import/3d/collada.h
  editor/import/3d/editor_import_collada.h
  editor/import/3d/post_import_plugin_skeleton_renamer.h
  editor/import/3d/post_import_plugin_skeleton_rest_fixer.h
  editor/import/3d/post_import_plugin_skeleton_track_organizer.h
  editor/import/3d/resource_importer_obj.h
  editor/import/3d/resource_importer_scene.h
  editor/import/3d/scene_import_settings.h
  editor/import/audio_stream_import_settings.h
  editor/import/dynamic_font_import_settings.h
  editor/import/editor_import_plugin.h
  editor/import/resource_importer_bitmask.h
  editor/import/resource_importer_bmfont.h
  editor/import/resource_importer_csv_translation.h
  editor/import/resource_importer_dynamic_font.h
  editor/import/resource_importer_image.h
  editor/import/resource_importer_imagefont.h
  editor/import/resource_importer_layered_texture.h
  editor/import/resource_importer_shader_file.h
  editor/import/resource_importer_svg.h
  editor/import/resource_importer_texture_atlas.h
  editor/import/resource_importer_texture_settings.h
  editor/import/resource_importer_texture.h
  editor/import/resource_importer_wav.h
  editor/input_event_configuration_dialog.h
  editor/inspector_dock.h
  editor/localization_editor.h
  editor/multi_node_edit.h
  editor/node_dock.h
  editor/plugins/abstract_polygon_2d_editor.h
  editor/plugins/animation_blend_space_1d_editor.h
  editor/plugins/animation_blend_space_2d_editor.h
  editor/plugins/animation_blend_tree_editor_plugin.h
  editor/plugins/animation_library_editor.h
  editor/plugins/animation_player_editor_plugin.h
  editor/plugins/animation_state_machine_editor.h
  editor/plugins/animation_tree_editor_plugin.h
  editor/plugins/asset_library_editor_plugin.h
  editor/plugins/audio_stream_editor_plugin.h
  editor/plugins/audio_stream_randomizer_editor_plugin.h
  editor/plugins/bit_map_editor_plugin.h
  editor/plugins/bone_map_editor_plugin.h
  editor/plugins/camera_2d_editor_plugin.h
  editor/plugins/camera_3d_editor_plugin.h
  editor/plugins/canvas_item_editor_plugin.h
  editor/plugins/cast_2d_editor_plugin.h
  editor/plugins/collision_polygon_2d_editor_plugin.h
  editor/plugins/collision_shape_2d_editor_plugin.h
  editor/plugins/color_channel_selector.h
  editor/plugins/control_editor_plugin.h
  editor/plugins/curve_editor_plugin.h
  editor/plugins/debugger_editor_plugin.h
  editor/plugins/dedicated_server_export_plugin.h
  editor/plugins/editor_context_menu_plugin.h
  editor/plugins/editor_debugger_plugin.h
  editor/plugins/editor_plugin_settings.h
  editor/plugins/editor_plugin.h
  editor/plugins/editor_preview_plugins.h
  editor/plugins/editor_resource_conversion_plugin.h
  editor/plugins/editor_resource_tooltip_plugins.h
  editor/plugins/embedded_process.h
  editor/plugins/font_config_plugin.h
  editor/plugins/game_view_plugin.h
  editor/plugins/gdextension_export_plugin.h
  editor/plugins/gizmos/audio_listener_3d_gizmo_plugin.h
  editor/plugins/gizmos/audio_stream_player_3d_gizmo_plugin.h
  editor/plugins/gizmos/camera_3d_gizmo_plugin.h
  editor/plugins/gizmos/collision_object_3d_gizmo_plugin.h
  editor/plugins/gizmos/collision_polygon_3d_gizmo_plugin.h
  editor/plugins/gizmos/collision_shape_3d_gizmo_plugin.h
  editor/plugins/gizmos/cpu_particles_3d_gizmo_plugin.h
  editor/plugins/gizmos/decal_gizmo_plugin.h
  editor/plugins/gizmos/fog_volume_gizmo_plugin.h
  editor/plugins/gizmos/geometry_instance_3d_gizmo_plugin.h
  editor/plugins/gizmos/gizmo_3d_helper.h
  editor/plugins/gizmos/gpu_particles_3d_gizmo_plugin.h
  editor/plugins/gizmos/gpu_particles_collision_3d_gizmo_plugin.h
  editor/plugins/gizmos/joint_3d_gizmo_plugin.h
  editor/plugins/gizmos/label_3d_gizmo_plugin.h
  editor/plugins/gizmos/light_3d_gizmo_plugin.h
  editor/plugins/gizmos/lightmap_gi_gizmo_plugin.h
  editor/plugins/gizmos/lightmap_probe_gizmo_plugin.h
  editor/plugins/gizmos/marker_3d_gizmo_plugin.h
  editor/plugins/gizmos/mesh_instance_3d_gizmo_plugin.h
  editor/plugins/gizmos/occluder_instance_3d_gizmo_plugin.h
  editor/plugins/gizmos/particles_3d_emission_shape_gizmo_plugin.h
  editor/plugins/gizmos/physics_bone_3d_gizmo_plugin.h
  editor/plugins/gizmos/ray_cast_3d_gizmo_plugin.h
  editor/plugins/gizmos/reflection_probe_gizmo_plugin.h
  editor/plugins/gizmos/shape_cast_3d_gizmo_plugin.h
  editor/plugins/gizmos/soft_body_3d_gizmo_plugin.h
  editor/plugins/gizmos/spring_arm_3d_gizmo_plugin.h
  editor/plugins/gizmos/spring_bone_3d_gizmo_plugin.h
  editor/plugins/gizmos/sprite_base_3d_gizmo_plugin.h
  editor/plugins/gizmos/vehicle_body_3d_gizmo_plugin.h
  editor/plugins/gizmos/visible_on_screen_notifier_3d_gizmo_plugin.h
  editor/plugins/gizmos/voxel_gi_gizmo_plugin.h
  editor/plugins/gpu_particles_collision_sdf_editor_plugin.h
  editor/plugins/gradient_editor_plugin.h
  editor/plugins/gradient_texture_2d_editor_plugin.h
  editor/plugins/input_event_editor_plugin.h
  editor/plugins/light_occluder_2d_editor_plugin.h
  editor/plugins/lightmap_gi_editor_plugin.h
  editor/plugins/line_2d_editor_plugin.h
  editor/plugins/material_editor_plugin.h
  editor/plugins/mesh_editor_plugin.h
  editor/plugins/mesh_instance_3d_editor_plugin.h
  editor/plugins/mesh_library_editor_plugin.h
  editor/plugins/multimesh_editor_plugin.h
  editor/plugins/node_3d_editor_gizmos.h
  editor/plugins/node_3d_editor_plugin.h
  editor/plugins/occluder_instance_3d_editor_plugin.h
  editor/plugins/packed_scene_editor_plugin.h
  editor/plugins/packed_scene_translation_parser_plugin.h
  editor/plugins/parallax_background_editor_plugin.h
  editor/plugins/particle_process_material_editor_plugin.h
  editor/plugins/particles_editor_plugin.h
  editor/plugins/path_2d_editor_plugin.h
  editor/plugins/path_3d_editor_plugin.h
  editor/plugins/physical_bone_3d_editor_plugin.h
  editor/plugins/plugin_config_dialog.h
  editor/plugins/polygon_2d_editor_plugin.h
  editor/plugins/polygon_3d_editor_plugin.h
  editor/plugins/resource_preloader_editor_plugin.h
  editor/plugins/root_motion_editor_plugin.h
  editor/plugins/script_editor_plugin.h
  editor/plugins/script_text_editor.h
  editor/plugins/shader_editor_plugin.h
  editor/plugins/shader_file_editor_plugin.h
  editor/plugins/shader/shader_editor.h
  editor/plugins/skeleton_2d_editor_plugin.h
  editor/plugins/skeleton_3d_editor_plugin.h
  editor/plugins/skeleton_ik_3d_editor_plugin.h
  editor/plugins/sprite_2d_editor_plugin.h
  editor/plugins/sprite_frames_editor_plugin.h
  editor/plugins/style_box_editor_plugin.h
  editor/plugins/sub_viewport_preview_editor_plugin.h
  editor/plugins/text_editor.h
  editor/plugins/text_shader_editor.h
  editor/plugins/texture_3d_editor_plugin.h
  editor/plugins/texture_editor_plugin.h
  editor/plugins/texture_layered_editor_plugin.h
  editor/plugins/texture_region_editor_plugin.h
  editor/plugins/theme_editor_plugin.h
  editor/plugins/theme_editor_preview.h
  editor/plugins/tiles/atlas_merging_dialog.h
  editor/plugins/tiles/tile_atlas_view.h
  editor/plugins/tiles/tile_data_editors.h
  editor/plugins/tiles/tile_map_layer_editor.h
  editor/plugins/tiles/tile_proxies_manager_dialog.h
  editor/plugins/tiles/tile_set_atlas_source_editor.h
  editor/plugins/tiles/tile_set_editor.h
  editor/plugins/tiles/tile_set_scenes_collection_source_editor.h
  editor/plugins/tiles/tiles_editor_plugin.h
  editor/plugins/tool_button_editor_plugin.h
  editor/plugins/version_control_editor_plugin.h
  editor/plugins/visual_shader_editor_plugin.h
  editor/plugins/voxel_gi_editor_plugin.h
  editor/pot_generator.h
  editor/progress_dialog.h
  editor/project_converter_3_to_4.h
  editor/project_manager.h
  editor/project_manager/project_dialog.h
  editor/project_manager/project_list.h
  editor/project_manager/project_tag.h
  editor/project_manager/quick_settings_dialog.h
  editor/project_settings_editor.h
  editor/project_upgrade_tool.h
  editor/property_selector.h
  editor/register_editor_types.h
  editor/register_exporters.h
  editor/rename_dialog.h
  editor/renames_map_3_to_4.h
  editor/reparent_dialog.h
  editor/run_instances_dialog.h
  editor/scene_create_dialog.h
  editor/scene_tree_dock.h
  editor/script_create_dialog.h
  editor/shader_create_dialog.h
  editor/shader_globals_editor.h
  editor/themes/editor_color_map.h
  editor/themes/editor_fonts.h
  editor/themes/editor_icons.h
  editor/themes/editor_scale.h
  editor/themes/editor_theme_manager.h
  editor/themes/editor_theme.h
  editor/window_wrapper.h
)

# GODOT_EDITOR_FILES - All files for editor
set(GODOT_EDITOR_FILES
  ${GODOT_EDITOR_SOURCES}
  ${GODOT_EDITOR_HEADERS}
)
