# Generated source list for platform (root-relative paths)
# GODOT_PLATFORM_SOURCES - Source files for platform
set(GODOT_PLATFORM_SOURCES
  platform/android/android_input_handler.cpp
  platform/android/android_keys_utils.cpp
  platform/android/api/api.cpp
  platform/android/audio_driver_opensl.cpp
  platform/android/dialog_utils_jni.cpp
  platform/android/dir_access_jandroid.cpp
  platform/android/display_server_android.cpp
  platform/android/export/export_plugin.cpp
  platform/android/export/export.cpp
  platform/android/export/godot_plugin_config.cpp
  platform/android/export/gradle_export_util.cpp
  platform/android/file_access_android.cpp
  platform/android/file_access_filesystem_jandroid.cpp
  platform/android/game_menu_utils_jni.cpp
  platform/android/java_class_wrapper.cpp
  platform/android/java_godot_io_wrapper.cpp
  platform/android/java_godot_lib_jni.cpp
  platform/android/java_godot_view_wrapper.cpp
  platform/android/java_godot_wrapper.cpp
  platform/android/jni_utils.cpp
  platform/android/net_socket_android.cpp
  platform/android/os_android.cpp
  platform/android/plugin/godot_plugin_jni.cpp
  platform/android/rendering_context_driver_vulkan_android.cpp
  platform/android/thread_jandroid.cpp
  platform/android/tts_android.cpp
  platform/android/variant/callable_jni.cpp
  platform/ios/api/api.cpp
  platform/ios/app_delegate.mm
  platform/ios/device_metrics.m
  platform/ios/display_layer.mm
  platform/ios/display_server_ios.mm
  platform/ios/export/export_plugin.cpp
  platform/ios/export/export.cpp
  platform/ios/export/godot_plugin_config.cpp
  platform/ios/godot_app_delegate.m
  platform/ios/godot_ios.mm
  platform/ios/godot_view_renderer.mm
  platform/ios/godot_view.mm
  platform/ios/ios_terminal_logger.mm
  platform/ios/ios.mm
  platform/ios/key_mapping_ios.mm
  platform/ios/keyboard_input_view.mm
  platform/ios/main.m
  platform/ios/os_ios.mm
  platform/ios/rendering_context_driver_vulkan_ios.mm
  platform/ios/tts_ios.mm
  platform/ios/view_controller.mm
  platform/linuxbsd/crash_handler_linuxbsd.cpp
  platform/linuxbsd/dbus-so_wrap.c
  platform/linuxbsd/export/export_plugin.cpp
  platform/linuxbsd/export/export.cpp
  platform/linuxbsd/fontconfig-so_wrap.c
  platform/linuxbsd/freedesktop_at_spi_monitor.cpp
  platform/linuxbsd/freedesktop_portal_desktop.cpp
  platform/linuxbsd/freedesktop_screensaver.cpp
  platform/linuxbsd/godot_linuxbsd.cpp
  platform/linuxbsd/joypad_linux.cpp
  platform/linuxbsd/libudev-so_wrap.c
  platform/linuxbsd/os_linuxbsd.cpp
  platform/linuxbsd/speechd-so_wrap.c
  platform/linuxbsd/tts_linux.cpp
  platform/linuxbsd/wayland/detect_prime_egl.cpp
  platform/linuxbsd/wayland/display_server_wayland.cpp
  platform/linuxbsd/wayland/dynwrappers/libdecor-so_wrap.c
  platform/linuxbsd/wayland/dynwrappers/wayland-client-core-so_wrap.c
  platform/linuxbsd/wayland/dynwrappers/wayland-cursor-so_wrap.c
  platform/linuxbsd/wayland/dynwrappers/wayland-egl-core-so_wrap.c
  platform/linuxbsd/wayland/egl_manager_wayland_gles.cpp
  platform/linuxbsd/wayland/egl_manager_wayland.cpp
  platform/linuxbsd/wayland/key_mapping_xkb.cpp
  platform/linuxbsd/wayland/rendering_context_driver_vulkan_wayland.cpp
  platform/linuxbsd/wayland/wayland_thread.cpp
  platform/linuxbsd/x11/detect_prime_x11.cpp
  platform/linuxbsd/x11/display_server_x11.cpp
  platform/linuxbsd/x11/dynwrappers/xcursor-so_wrap.c
  platform/linuxbsd/x11/dynwrappers/xext-so_wrap.c
  platform/linuxbsd/x11/dynwrappers/xinerama-so_wrap.c
  platform/linuxbsd/x11/dynwrappers/xinput2-so_wrap.c
  platform/linuxbsd/x11/dynwrappers/xlib-so_wrap.c
  platform/linuxbsd/x11/dynwrappers/xrandr-so_wrap.c
  platform/linuxbsd/x11/dynwrappers/xrender-so_wrap.c
  platform/linuxbsd/x11/gl_manager_x11_egl.cpp
  platform/linuxbsd/x11/gl_manager_x11.cpp
  platform/linuxbsd/x11/key_mapping_x11.cpp
  platform/linuxbsd/x11/rendering_context_driver_vulkan_x11.cpp
  platform/linuxbsd/xkbcommon-so_wrap.c
  platform/macos/crash_handler_macos.mm
  platform/macos/dir_access_macos.mm
  platform/macos/display_server_embedded.mm
  platform/macos/display_server_macos.mm
  platform/macos/editor/embedded_game_view_plugin.mm
  platform/macos/editor/embedded_process_macos.mm
  platform/macos/embedded_debugger.mm
  platform/macos/embedded_gl_manager.mm
  platform/macos/export/export_plugin.cpp
  platform/macos/export/export.cpp
  platform/macos/gl_manager_macos_angle.mm
  platform/macos/gl_manager_macos_legacy.mm
  platform/macos/godot_application_delegate.mm
  platform/macos/godot_application.mm
  platform/macos/godot_button_view.mm
  platform/macos/godot_content_view.mm
  platform/macos/godot_main_macos.mm
  platform/macos/godot_menu_delegate.mm
  platform/macos/godot_menu_item.mm
  platform/macos/godot_open_save_delegate.mm
  platform/macos/godot_status_item.mm
  platform/macos/godot_window_delegate.mm
  platform/macos/godot_window.mm
  platform/macos/key_mapping_macos.mm
  platform/macos/macos_terminal_logger.mm
  platform/macos/native_menu_macos.mm
  platform/macos/os_macos.mm
  platform/macos/rendering_context_driver_vulkan_macos.mm
  platform/macos/tts_macos.mm
  platform/web/api/api.cpp
  platform/web/audio_driver_web.cpp
  platform/web/display_server_web.cpp
  platform/web/editor/web_tools_editor_plugin.cpp
  platform/web/export/editor_http_server.cpp
  platform/web/export/export_plugin.cpp
  platform/web/export/export.cpp
  platform/web/http_client_web.cpp
  platform/web/ip_web.cpp
  platform/web/javascript_bridge_singleton.cpp
  platform/web/net_socket_web.cpp
  platform/web/os_web.cpp
  platform/web/web_main.cpp
  platform/web/web_runtime.cpp
  platform/web/webmidi_driver.cpp
  platform/windows/console_wrapper_windows.cpp
  platform/windows/crash_handler_windows_seh.cpp
  platform/windows/crash_handler_windows_signal.cpp
  platform/windows/display_server_windows.cpp
  platform/windows/drop_target_windows.cpp
  platform/windows/export/export_plugin.cpp
  platform/windows/export/export.cpp
  platform/windows/gl_manager_windows_angle.cpp
  platform/windows/gl_manager_windows_native.cpp
  platform/windows/godot_windows.cpp
  platform/windows/joypad_windows.cpp
  platform/windows/key_mapping_windows.cpp
  platform/windows/native_menu_windows.cpp
  platform/windows/os_windows.cpp
  platform/windows/rendering_context_driver_vulkan_windows.cpp
  platform/windows/tts_windows.cpp
  platform/windows/wgl_detect_version.cpp
  platform/windows/windows_terminal_logger.cpp
  platform/windows/windows_utils.cpp
)

# GODOT_PLATFORM_HEADERS - Header files for platform
set(GODOT_PLATFORM_HEADERS
  platform/android/android_input_handler.h
  platform/android/android_keys_utils.h
  platform/android/api/api.h
  platform/android/api/java_class_wrapper.h
  platform/android/api/jni_singleton.h
  platform/android/audio_driver_opensl.h
  platform/android/dialog_utils_jni.h
  platform/android/dir_access_jandroid.h
  platform/android/display_server_android.h
  platform/android/export/export_plugin.h
  platform/android/export/export.h
  platform/android/export/godot_plugin_config.h
  platform/android/export/gradle_export_util.h
  platform/android/file_access_android.h
  platform/android/file_access_filesystem_jandroid.h
  platform/android/game_menu_utils_jni.h
  platform/android/java_godot_io_wrapper.h
  platform/android/java_godot_lib_jni.h
  platform/android/java_godot_view_wrapper.h
  platform/android/java_godot_wrapper.h
  platform/android/jni_utils.h
  platform/android/net_socket_android.h
  platform/android/os_android.h
  platform/android/platform_config.h
  platform/android/platform_gl.h
  platform/android/plugin/godot_plugin_jni.h
  platform/android/rendering_context_driver_vulkan_android.h
  platform/android/thread_jandroid.h
  platform/android/tts_android.h
  platform/android/variant/callable_jni.h
  platform/ios/api/api.h
  platform/ios/app_delegate.h
  platform/ios/device_metrics.h
  platform/ios/display_layer.h
  platform/ios/display_server_ios.h
  platform/ios/export/export_plugin.h
  platform/ios/export/export.h
  platform/ios/export/godot_plugin_config.h
  platform/ios/godot_app_delegate.h
  platform/ios/godot_view_renderer.h
  platform/ios/godot_view.h
  platform/ios/ios_terminal_logger.h
  platform/ios/ios.h
  platform/ios/key_mapping_ios.h
  platform/ios/keyboard_input_view.h
  platform/ios/os_ios.h
  platform/ios/platform_config.h
  platform/ios/platform_gl.h
  platform/ios/platform_thread.h
  platform/ios/rendering_context_driver_vulkan_ios.h
  platform/ios/tts_ios.h
  platform/ios/view_controller.h
  platform/linuxbsd/crash_handler_linuxbsd.h
  platform/linuxbsd/dbus-so_wrap.h
  platform/linuxbsd/export/export_plugin.h
  platform/linuxbsd/export/export.h
  platform/linuxbsd/fontconfig-so_wrap.h
  platform/linuxbsd/freedesktop_at_spi_monitor.h
  platform/linuxbsd/freedesktop_portal_desktop.h
  platform/linuxbsd/freedesktop_screensaver.h
  platform/linuxbsd/joypad_linux.h
  platform/linuxbsd/libudev-so_wrap.h
  platform/linuxbsd/os_linuxbsd.h
  platform/linuxbsd/platform_config.h
  platform/linuxbsd/platform_gl.h
  platform/linuxbsd/speechd-so_wrap.h
  platform/linuxbsd/tts_linux.h
  platform/linuxbsd/wayland/detect_prime_egl.h
  platform/linuxbsd/wayland/display_server_wayland.h
  platform/linuxbsd/wayland/dynwrappers/libdecor-so_wrap.h
  platform/linuxbsd/wayland/dynwrappers/wayland-client-core-so_wrap.h
  platform/linuxbsd/wayland/dynwrappers/wayland-cursor-so_wrap.h
  platform/linuxbsd/wayland/dynwrappers/wayland-egl-core-so_wrap.h
  platform/linuxbsd/wayland/egl_manager_wayland_gles.h
  platform/linuxbsd/wayland/egl_manager_wayland.h
  platform/linuxbsd/wayland/key_mapping_xkb.h
  platform/linuxbsd/wayland/rendering_context_driver_vulkan_wayland.h
  platform/linuxbsd/wayland/wayland_thread.h
  platform/linuxbsd/x11/detect_prime_x11.h
  platform/linuxbsd/x11/display_server_x11.h
  platform/linuxbsd/x11/dynwrappers/xcursor-so_wrap.h
  platform/linuxbsd/x11/dynwrappers/xext-so_wrap.h
  platform/linuxbsd/x11/dynwrappers/xinerama-so_wrap.h
  platform/linuxbsd/x11/dynwrappers/xinput2-so_wrap.h
  platform/linuxbsd/x11/dynwrappers/xlib-so_wrap.h
  platform/linuxbsd/x11/dynwrappers/xrandr-so_wrap.h
  platform/linuxbsd/x11/dynwrappers/xrender-so_wrap.h
  platform/linuxbsd/x11/gl_manager_x11_egl.h
  platform/linuxbsd/x11/gl_manager_x11.h
  platform/linuxbsd/x11/key_mapping_x11.h
  platform/linuxbsd/x11/rendering_context_driver_vulkan_x11.h
  platform/linuxbsd/xkbcommon-so_wrap.h
  platform/macos/crash_handler_macos.h
  platform/macos/dir_access_macos.h
  platform/macos/display_server_embedded.h
  platform/macos/display_server_macos.h
  platform/macos/editor/embedded_game_view_plugin.h
  platform/macos/editor/embedded_process_macos.h
  platform/macos/embedded_debugger.h
  platform/macos/embedded_gl_manager.h
  platform/macos/export/export_plugin.h
  platform/macos/export/export.h
  platform/macos/gl_manager_macos_angle.h
  platform/macos/gl_manager_macos_legacy.h
  platform/macos/godot_application_delegate.h
  platform/macos/godot_application.h
  platform/macos/godot_button_view.h
  platform/macos/godot_content_view.h
  platform/macos/godot_menu_delegate.h
  platform/macos/godot_menu_item.h
  platform/macos/godot_open_save_delegate.h
  platform/macos/godot_status_item.h
  platform/macos/godot_window_delegate.h
  platform/macos/godot_window.h
  platform/macos/key_mapping_macos.h
  platform/macos/macos_quartz_core_spi.h
  platform/macos/macos_terminal_logger.h
  platform/macos/native_menu_macos.h
  platform/macos/os_macos.h
  platform/macos/platform_config.h
  platform/macos/platform_gl.h
  platform/macos/platform_thread.h
  platform/macos/rendering_context_driver_vulkan_macos.h
  platform/macos/tts_macos.h
  platform/register_platform_apis.h
  platform/web/api/api.h
  platform/web/api/javascript_bridge_singleton.h
  platform/web/audio_driver_web.h
  platform/web/display_server_web.h
  platform/web/editor/web_tools_editor_plugin.h
  platform/web/export/editor_http_server.h
  platform/web/export/export_plugin.h
  platform/web/export/export.h
  platform/web/godot_audio.h
  platform/web/godot_js.h
  platform/web/godot_midi.h
  platform/web/godot_webgl2.h
  platform/web/http_client_web.h
  platform/web/ip_web.h
  platform/web/net_socket_web.h
  platform/web/os_web.h
  platform/web/platform_config.h
  platform/web/platform_gl.h
  platform/web/webmidi_driver.h
  platform/windows/crash_handler_windows.h
  platform/windows/display_server_windows.h
  platform/windows/drop_target_windows.h
  platform/windows/export/export_plugin.h
  platform/windows/export/export.h
  platform/windows/gl_manager_windows_angle.h
  platform/windows/gl_manager_windows_native.h
  platform/windows/joypad_windows.h
  platform/windows/key_mapping_windows.h
  platform/windows/lang_table.h
  platform/windows/native_menu_windows.h
  platform/windows/os_windows.h
  platform/windows/platform_config.h
  platform/windows/platform_gl.h
  platform/windows/rendering_context_driver_vulkan_windows.h
  platform/windows/tts_windows.h
  platform/windows/wgl_detect_version.h
  platform/windows/windows_terminal_logger.h
  platform/windows/windows_utils.h
)

# GODOT_PLATFORM_FILES - All files for platform
set(GODOT_PLATFORM_FILES
  ${GODOT_PLATFORM_SOURCES}
  ${GODOT_PLATFORM_HEADERS}
)
