# Generated source list for drivers (root-relative paths)
# GODOT_DRIVERS_SOURCES - Source files for drivers
set(GODOT_DRIVERS_SOURCES
  drivers/accesskit/accessibility_driver_accesskit.cpp
  drivers/accesskit/dynwrappers/accesskit-dll_wrap.c
  drivers/accesskit/dynwrappers/accesskit-dylib_wrap.c
  drivers/accesskit/dynwrappers/accesskit-so_wrap.c
  drivers/alsa/asound-so_wrap.c
  drivers/alsa/audio_driver_alsa.cpp
  drivers/alsamidi/midi_driver_alsamidi.cpp
  drivers/apple/joypad_apple.mm
  drivers/apple/thread_apple.cpp
  drivers/coreaudio/audio_driver_coreaudio.mm
  drivers/coremidi/midi_driver_coremidi.mm
  drivers/d3d12/d3d12_hooks.cpp
  drivers/d3d12/d3d12ma.cpp
  drivers/d3d12/dxil_hash.cpp
  drivers/d3d12/rendering_context_driver_d3d12.cpp
  drivers/d3d12/rendering_device_driver_d3d12.cpp
  drivers/egl/egl_manager.cpp
  drivers/gles3/effects/copy_effects.cpp
  drivers/gles3/effects/cubemap_filter.cpp
  drivers/gles3/effects/feed_effects.cpp
  drivers/gles3/effects/glow.cpp
  drivers/gles3/effects/post_effects.cpp
  drivers/gles3/environment/fog.cpp
  drivers/gles3/environment/gi.cpp
  drivers/gles3/rasterizer_canvas_gles3.cpp
  drivers/gles3/rasterizer_gles3.cpp
  drivers/gles3/rasterizer_scene_gles3.cpp
  drivers/gles3/shader_gles3.cpp
  drivers/gles3/storage/config.cpp
  drivers/gles3/storage/light_storage.cpp
  drivers/gles3/storage/material_storage.cpp
  drivers/gles3/storage/mesh_storage.cpp
  drivers/gles3/storage/particles_storage.cpp
  drivers/gles3/storage/render_scene_buffers_gles3.cpp
  drivers/gles3/storage/texture_storage.cpp
  drivers/gles3/storage/utilities.cpp
  drivers/metal/metal_device_properties.mm
  drivers/metal/metal_objects.mm
  drivers/metal/pixel_formats.mm
  drivers/metal/rendering_context_driver_metal.mm
  drivers/metal/rendering_device_driver_metal.mm
  drivers/png/image_loader_png.cpp
  drivers/png/png_driver_common.cpp
  drivers/png/resource_saver_png.cpp
  drivers/pulseaudio/audio_driver_pulseaudio.cpp
  drivers/pulseaudio/pulse-so_wrap.c
  drivers/register_driver_types.cpp
  drivers/unix/dir_access_unix.cpp
  drivers/unix/file_access_unix_pipe.cpp
  drivers/unix/file_access_unix.cpp
  drivers/unix/ip_unix.cpp
  drivers/unix/net_socket_unix.cpp
  drivers/unix/os_unix.cpp
  drivers/unix/syslog_logger.cpp
  drivers/unix/thread_posix.cpp
  drivers/vulkan/rendering_context_driver_vulkan.cpp
  drivers/vulkan/rendering_device_driver_vulkan.cpp
  drivers/vulkan/vulkan_hooks.cpp
  drivers/wasapi/audio_driver_wasapi.cpp
  drivers/windows/dir_access_windows.cpp
  drivers/windows/file_access_windows_pipe.cpp
  drivers/windows/file_access_windows.cpp
  drivers/windows/ip_windows.cpp
  drivers/windows/net_socket_winsock.cpp
  drivers/windows/thread_windows.cpp
  drivers/winmidi/midi_driver_winmidi.cpp
  drivers/xaudio2/audio_driver_xaudio2.cpp
)

# GODOT_DRIVERS_HEADERS - Header files for drivers
set(GODOT_DRIVERS_HEADERS
  drivers/accesskit/accessibility_driver_accesskit.h
  drivers/accesskit/dynwrappers/accesskit-dll_wrap.h
  drivers/accesskit/dynwrappers/accesskit-dylib_wrap.h
  drivers/accesskit/dynwrappers/accesskit-so_wrap.h
  drivers/alsa/asound-so_wrap.h
  drivers/alsa/audio_driver_alsa.h
  drivers/alsamidi/midi_driver_alsamidi.h
  drivers/apple/joypad_apple.h
  drivers/apple/thread_apple.h
  drivers/coreaudio/audio_driver_coreaudio.h
  drivers/coremidi/midi_driver_coremidi.h
  drivers/d3d12/d3d12_godot_nir_bridge.h
  drivers/d3d12/d3d12_hooks.h
  drivers/d3d12/dxil_hash.h
  drivers/d3d12/rendering_context_driver_d3d12.h
  drivers/d3d12/rendering_device_driver_d3d12.h
  drivers/egl/egl_manager.h
  drivers/gles3/effects/copy_effects.h
  drivers/gles3/effects/cubemap_filter.h
  drivers/gles3/effects/feed_effects.h
  drivers/gles3/effects/glow.h
  drivers/gles3/effects/post_effects.h
  drivers/gles3/environment/fog.h
  drivers/gles3/environment/gi.h
  drivers/gles3/rasterizer_canvas_gles3.h
  drivers/gles3/rasterizer_gles3.h
  drivers/gles3/rasterizer_scene_gles3.h
  drivers/gles3/shader_gles3.h
  drivers/gles3/storage/config.h
  drivers/gles3/storage/light_storage.h
  drivers/gles3/storage/material_storage.h
  drivers/gles3/storage/mesh_storage.h
  drivers/gles3/storage/particles_storage.h
  drivers/gles3/storage/render_scene_buffers_gles3.h
  drivers/gles3/storage/texture_storage.h
  drivers/gles3/storage/utilities.h
  drivers/metal/inflection_map.h
  drivers/metal/metal_device_properties.h
  drivers/metal/metal_objects.h
  drivers/metal/metal_utils.h
  drivers/metal/pixel_formats.h
  drivers/metal/rendering_context_driver_metal.h
  drivers/metal/rendering_device_driver_metal.h
  drivers/png/image_loader_png.h
  drivers/png/png_driver_common.h
  drivers/png/resource_saver_png.h
  drivers/pulseaudio/audio_driver_pulseaudio.h
  drivers/pulseaudio/pulse-so_wrap.h
  drivers/register_driver_types.h
  drivers/unix/dir_access_unix.h
  drivers/unix/file_access_unix_pipe.h
  drivers/unix/file_access_unix.h
  drivers/unix/ip_unix.h
  drivers/unix/net_socket_unix.h
  drivers/unix/os_unix.h
  drivers/unix/syslog_logger.h
  drivers/unix/thread_posix.h
  drivers/vulkan/godot_vulkan.h
  drivers/vulkan/rendering_context_driver_vulkan.h
  drivers/vulkan/rendering_device_driver_vulkan.h
  drivers/vulkan/vulkan_hooks.h
  drivers/wasapi/audio_driver_wasapi.h
  drivers/windows/dir_access_windows.h
  drivers/windows/file_access_windows_pipe.h
  drivers/windows/file_access_windows.h
  drivers/windows/ip_windows.h
  drivers/windows/net_socket_winsock.h
  drivers/windows/thread_windows.h
  drivers/winmidi/midi_driver_winmidi.h
  drivers/xaudio2/audio_driver_xaudio2.h
)

# GODOT_DRIVERS_FILES - All files for drivers
set(GODOT_DRIVERS_FILES
  ${GODOT_DRIVERS_SOURCES}
  ${GODOT_DRIVERS_HEADERS}
)
